// 识别结果 JSON 夹具(SPEC §5.9 形状): SUNAS 样式(我方型号 + 英文描述)与 UJ23 样式
// (同格英中双语、组合件、零标价)混在一份里, 覆盖各种行状态。全部为虚构数据。
Map<String, dynamic> candidate({
  required String goodsId,
  String? code,
  String? name,
  String? model,
  String? series,
  String? colorName,
  String? listPrice,
  String? discount,
  String? pricingFlag,
  List<String> reasons = const [],
  String? nameEn,
}) => {
  'goodsId': goodsId,
  'code': ?code,
  'name': ?name,
  'model': ?model,
  'series': ?series,
  'colorId': 'color-${colorName ?? 'none'}',
  'colorName': ?colorName,
  'unitId': 'unit-pcs',
  'unitName': '个',
  'nameEn': ?nameEn,
  'score': 96,
  'reasons': reasons,
  // 数字/字符串混排: 解析必须两种都接受。
  'listPrice': ?(listPrice == null ? null : num.parse(listPrice)),
  'discount': ?discount,
  'rateUsed': 1,
  'pricingFlag': ?pricingFlag,
};

Map<String, dynamic> intakeResultJson({
  bool priceMasked = false,
  String clientStatus = 'MATCHED',
  List<Map<String, dynamic>>? enrichment,
}) => {
  'schemaVersion': 2,
  'docType': 'order',
  'file': {
    'name': 'UJ23 quotation.xlsx',
    'kind': 'XLSX',
    'sheet': 'Sheet1',
    'sha256': 'abc',
    'otherSheets': [
      {'name': 'Packing', 'index': 1, 'lineCount': 32},
    ],
  },
  'extraction': {'layoutSource': 'RULES', 'aiUsed': false},
  'header': {
    'buyerName': 'SUNAS TRADING',
    'docNo': 'UJ23',
    'docDate': '2026-07-06',
    'incoterm': 'EXW',
    'paymentTerms': 'T/T 30% deposit, 70% before shipment',
    'remarkSuggestion': 'EXW; T/T 30% deposit, 70% before shipment',
  },
  'currency': {
    'fileCurrency': 'USD',
    'baseCurrencyId': 'cny',
    'baseCurrencyName': '人民币',
    'financeRate': 7.1,
    'rateMissing': false,
  },
  'client': {
    'status': clientStatus,
    'selectedClientId': clientStatus == 'UNMATCHED' ? null : 'client-sunas',
    'candidates': [
      {
        'clientId': 'client-sunas',
        'code': 'WM057',
        'name': '尼日利亚SUNAS',
        'score': 93,
        'reasons': ['邮箱一致'],
      },
    ],
    'enrichment':
        enrichment ??
        [
          {
            'field': 'email',
            'label': '邮箱',
            'current': null,
            'proposed': 'buyer@example.com',
            'defaultChecked': true,
            'differs': false,
          },
          {
            'field': 'address',
            'label': '地址',
            'current': 'Old road 1',
            'proposed': 'New road 9',
            'defaultChecked': false,
            'differs': true,
          },
          // 白名单外的字段必须被丢弃。
          {'field': 'bankAccount', 'label': '账号', 'proposed': '6222'},
        ],
    'newClientProposal': {
      'name': 'SUNAS TRADING',
      'email': 'buyer@example.com',
    },
  },
  'duplicates': [
    {
      'docType': 'order',
      'id': 'order-old',
      'billNo': 'XD26030007',
      'billDate': '2026-03-06',
      'reason': '同一个客户单号',
    },
  ],
  'lines': [
    {
      'key': 'S1R9',
      'lineNo': '1',
      'partNo': 'GZ23/D',
      'description': 'DOUBLE 3 PIN UNIVERSAL SOCKET WITH SWITCH',
      'descriptionAlt': '两开多功能三极插座',
      'series': 'Z9',
      'color': 'WHITE',
      'qty': '1,800',
      'customerUnitPrice': 21,
      'customerAmount': 37800,
      'status': 'MATCHED',
      'confidenceLevel': 'HIGH',
      'selectedGoodsId': 'g-gz23-white',
      'setNameEnDefault': true,
      'nameEnText': 'DOUBLE 3 PIN UNIVERSAL SOCKET WITH SWITCH',
      'candidates': [
        candidate(
          goodsId: 'g-gz23-white',
          code: '280235165',
          name: '两开多功能三极插座',
          model: 'GZ23/D',
          series: 'Z9',
          colorName: '白色',
          listPrice: '21',
          discount: '1',
          pricingFlag: 'OK',
          reasons: ['型号一致', '系列一致', '颜色一致'],
        ),
      ],
      'warnings': <Map<String, dynamic>>[],
    },
    {
      'key': 'S1R10',
      'lineNo': '2',
      'partNo': 'GZ23/D',
      'description': 'DOUBLE 3 PIN SOCKET GOLD',
      'qty': 200,
      'customerUnitPrice': '19.95',
      'status': 'REVIEW',
      'confidenceLevel': 'MEDIUM',
      'reasonText': '颜色没对上',
      'selectedGoodsId': 'g-gz23-gold',
      'setNameEnDefault': false,
      'nameEnText': 'DOUBLE 3 PIN SOCKET GOLD',
      'candidates': [
        candidate(
          goodsId: 'g-gz23-gold',
          code: '280235166',
          name: '两开多功能三极插座',
          model: 'GZ23/D',
          series: 'Z9',
          colorName: '金色',
          listPrice: '21',
          discount: '0.95',
          pricingFlag: 'OK',
          reasons: ['型号一致', '颜色不一致'],
        ),
        candidate(
          goodsId: 'g-gz23-white',
          code: '280235165',
          name: '两开多功能三极插座',
          model: 'GZ23/D',
          colorName: '白色',
          listPrice: '21',
          discount: '0.95',
          pricingFlag: 'OK',
        ),
      ],
    },
    {
      'key': 'S1R11',
      'lineNo': '3',
      'partNo': 'XX-999',
      'description': 'MYSTERY PART',
      'qty': 5,
      'customerUnitPrice': 3,
      'status': 'UNMATCHED',
      'reasonText': '没找到这个货品',
      'candidates': <Map<String, dynamic>>[],
    },
    {
      'key': 'S1R12',
      'lineNo': '4',
      'partNo': 'Q1200046',
      'description': 'Pressure plate',
      'descriptionAlt': 'Q120德式插座压板',
      'qty': 1000,
      'customerUnitPrice': 0.2,
      'status': 'REVIEW',
      'reasonText': '标价为0',
      'selectedGoodsId': 'g-plate',
      'candidates': [
        candidate(
          goodsId: 'g-plate',
          code: 'Q1200046',
          name: 'Q120德式插座压板',
          listPrice: '0',
          pricingFlag: 'NO_LIST_PRICE',
        ),
      ],
      'warnings': [
        {'code': 'NO_LIST_PRICE', 'message': '标价为0'},
      ],
    },
    {
      'key': 'S1R13',
      'lineNo': '5',
      'partNo': 'WTV-03+WTV-04',
      'description': 'TV socket set',
      'qty': 50,
      'customerUnitPrice': 12,
      'bundle': true,
      'bundleParts': [
        {
          'partNo': 'WTV-03',
          'candidates': [
            candidate(
              goodsId: 'g-wtv03',
              code: 'WTV-03',
              name: '电视插座',
              listPrice: '6',
            ),
          ],
        },
        {
          'partNo': 'WTV-04',
          'candidates': [
            candidate(
              goodsId: 'g-wtv04',
              code: 'WTV-04',
              name: '电视插座面板',
              listPrice: '6',
            ),
          ],
        },
      ],
      'status': 'REVIEW',
      'reasonText': '这是组合件',
      'selectedGoodsId': 'g-set',
      'candidates': [
        candidate(
          goodsId: 'g-set',
          code: 'WTV-SET',
          name: '电视插座功能件',
          listPrice: '12',
          discount: '1',
          pricingFlag: 'OK',
        ),
      ],
      'warnings': [
        {'code': 'BUNDLE_LINE', 'message': '组合件'},
      ],
    },
    {
      'key': 'S1R14',
      'lineNo': '6',
      'partNo': 'GK12',
      'description': 'ONE GANG SWITCH',
      'qty': 10,
      'unit': 'CTN',
      'suggestedQty': 600,
      'customerUnitPrice': 9.45,
      'status': 'MATCHED',
      'selectedGoodsId': 'g-gk12',
      'candidates': [
        candidate(
          goodsId: 'g-gk12',
          code: '280235175',
          name: '一开双控开关',
          model: 'GK12',
          listPrice: '9.45',
          discount: '1',
          pricingFlag: 'OK',
        ),
      ],
      'warnings': [
        {'code': 'UNIT_NOT_PCS', 'message': '文件数量单位是 箱(CTN), 已按每箱 60 个换算, 请核对'},
      ],
    },
    // 键重复: 丢弃。
    {'key': 'S1R14', 'partNo': 'DUP', 'qty': 1},
    // 没有键: 丢弃。
    {'partNo': 'NOKEY', 'qty': 1},
  ],
  'summary': {
    'lineCount': 6,
    'matched': 2,
    'review': 3,
    'unmatched': 1,
    'priceMasked': priceMasked,
  },
  'notices': ['AI 未开启, 只识别常见格式的 Excel'],
};

/// 同一个文件改为识别第 2 张工作表(Packing)后的结果: 只有一行, 原来那张(Sheet1)变成「另有工作表」。
Map<String, dynamic> intakeSheetResultJson() => {
  'schemaVersion': 2,
  'docType': 'order',
  'file': {
    'name': 'UJ23 quotation.xlsx',
    'kind': 'XLSX',
    'sheet': 'Packing',
    'sha256': 'abc',
    'otherSheets': [
      {'name': 'Sheet1', 'index': 0, 'lineCount': 6},
    ],
  },
  'header': {'buyerName': 'SUNAS TRADING', 'docNo': 'UJ23-P'},
  'currency': {'baseCurrencyId': 'cny', 'baseCurrencyName': '人民币'},
  'client': {
    'status': 'MATCHED',
    'selectedClientId': 'client-sunas',
    'candidates': [
      {'clientId': 'client-sunas', 'code': 'WM057', 'name': '尼日利亚SUNAS'},
    ],
  },
  'lines': [
    {
      'key': 'S2R5',
      'lineNo': '1',
      'partNo': 'GK12',
      'description': 'ONE GANG SWITCH',
      'qty': 40,
      'customerUnitPrice': 9.45,
      'status': 'MATCHED',
      'selectedGoodsId': 'g-gk12',
      'setNameEnDefault': true,
      'nameEnText': 'ONE GANG SWITCH',
      'candidates': [
        candidate(
          goodsId: 'g-gk12',
          code: '280235175',
          name: '一开双控开关',
          model: 'GK12',
          listPrice: '9.45',
          discount: '1',
          pricingFlag: 'OK',
        ),
      ],
    },
  ],
  'summary': {'lineCount': 1, 'matched': 1, 'review': 0, 'unmatched': 0},
  'notices': <String>[],
};
