-- Finishing early changes the outstanding sales target, not the authorization
-- under which this already manufactured batch was approved. Preserve that exact
-- batch authorization on the existing immutable CAP event; never grow future capacity.
ALTER TABLE production_daily_report_target_events
    ADD COLUMN overproduction_authorizations JSONB,
    ADD CONSTRAINT daily_report_cap_authorizations_shape CHECK (
        overproduction_authorizations IS NULL OR
        (event_type='CAP' AND jsonb_typeof(overproduction_authorizations)='object'
         AND overproduction_authorizations->>'version'='1'
         AND jsonb_typeof(overproduction_authorizations->'segments')='array'));

COMMENT ON COLUMN production_daily_report_target_events.overproduction_authorizations IS
    'DB-captured per-segment allowance before target reduction; authorizes only this approved report exact actual surplus';

CREATE FUNCTION fn_capture_final_report_surplus_authorizations()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE segment RECORD; entry JSONB; entries JSONB:='[]'::jsonb;
        actual_qty NUMERIC; other_reserved NUMERIC; margin NUMERIC; drafts TEXT;
BEGIN
    IF NEW.overproduction_authorizations IS NOT NULL THEN
        RAISE EXCEPTION 'Final-report authorization snapshots are generated by the database'
            USING ERRCODE='23514';
    END IF;
    IF NEW.event_type<>'CAP' THEN RETURN NEW; END IF;

    -- The preceding guard has locked and validated this exact plan item and report.
    -- Lock every affected segment in PostgreSQL UUID order before discovering drafts.
    PERFORM id FROM production_execution_segments
    WHERE source_plan_item_id=NEW.plan_item_id AND NOT is_deleted
      AND status NOT IN ('CANCELLED','REVERSED') ORDER BY id FOR UPDATE;

    SELECT string_agg(DISTINCT report.bill_no, '、' ORDER BY report.bill_no) INTO drafts
    FROM production_daily_reports report
    JOIN production_daily_report_items item ON item.report_id=report.id
    JOIN production_execution_segments affected ON affected.id=item.execution_segment_id
    WHERE affected.source_plan_item_id=NEW.plan_item_id AND NOT affected.is_deleted
      AND affected.status NOT IN ('CANCELLED','REVERSED')
      AND report.id<>NEW.report_id AND report.status=0 AND NOT report.is_deleted AND NOT item.is_deleted;
    IF drafts IS NOT NULL THEN
        RAISE EXCEPTION '该工单还有未审核报工单（%），请先审核或删除这些草稿，再提前完结', drafts
            USING ERRCODE='23514',CONSTRAINT='final_report_pending_drafts';
    END IF;

    FOR segment IN
        SELECT id,planned_qty,allowed_overproduction_rate,overproduction_rate_version
        FROM production_execution_segments
        WHERE source_plan_item_id=NEW.plan_item_id AND NOT is_deleted
          AND status NOT IN ('CANCELLED','REVERSED') ORDER BY id
    LOOP
        SELECT COALESCE(SUM(item.qty),0) INTO actual_qty
        FROM production_daily_report_items item
        WHERE item.report_id=NEW.report_id AND item.execution_segment_id=segment.id
          AND item.is_actual_surplus AND item.fqc_recovery_authorization_id IS NULL AND NOT item.is_deleted;
        SELECT COALESCE(SUM(item.qty),0) INTO other_reserved
        FROM production_daily_report_items item
        JOIN production_daily_reports report ON report.id=item.report_id
        WHERE item.execution_segment_id=segment.id AND item.is_actual_surplus
          AND item.fqc_recovery_authorization_id IS NULL AND NOT item.is_deleted
          AND NOT report.is_deleted AND report.status IN (0,1) AND report.id<>NEW.report_id;
        margin:=trunc(segment.planned_qty*segment.allowed_overproduction_rate,4);
        IF actual_qty>GREATEST(margin-other_reserved,0)
           OR (actual_qty>0 AND NOT fn_execution_overproduction_policy_applies(segment.id)) THEN
            RAISE EXCEPTION 'Actual surplus exceeds the effective approved rate; create a separate reviewed supplemental plan'
                USING ERRCODE='23514',CONSTRAINT='actual_output_effective_rate_limit';
        END IF;
        entry:=jsonb_build_object('segmentId',segment.id,'plannedQty',segment.planned_qty,
            'allowedRate',segment.allowed_overproduction_rate,'rateVersion',segment.overproduction_rate_version,
            'approvedMarginQty',margin,'otherReservedSurplusQty',other_reserved,'actualSurplusQty',actual_qty);
        entries:=entries||jsonb_build_array(entry);
    END LOOP;
    NEW.overproduction_authorizations:=jsonb_build_object('version',1,'segments',entries);
    RETURN NEW;
END;
$$;

-- PostgreSQL runs same-kind triggers by name: the established identity/quantity
-- guard must run first. Its UPDATE/DELETE denial also makes these snapshots immutable.
CREATE TRIGGER trg_z_capture_final_report_surplus_authorizations
BEFORE INSERT ON production_daily_report_target_events
FOR EACH ROW EXECUTE FUNCTION fn_capture_final_report_surplus_authorizations();

CREATE OR REPLACE FUNCTION fn_assert_actual_output_policy_limit_for_report(p_report UUID)
RETURNS VOID LANGUAGE plpgsql AS $$
DECLARE source RECORD; frozen RECORD; available NUMERIC; report_status SMALLINT;
BEGIN
    SELECT status INTO report_status FROM production_daily_reports
    WHERE id=p_report AND status IN(0,1) AND NOT is_deleted;
    IF NOT FOUND THEN RETURN; END IF;

    -- Compare both directions, including a deleted/reclassified surplus slice becoming
    -- zero. An approved snapshot is not permission to edit that physical batch later.
    IF report_status=1 THEN
        FOR frozen IN
            SELECT event.plan_item_id, fact.value
            FROM production_daily_report_target_events event
            CROSS JOIN LATERAL jsonb_array_elements(event.overproduction_authorizations->'segments') fact(value)
            WHERE event.report_id=p_report AND event.event_type='CAP'
              AND event.overproduction_authorizations IS NOT NULL
              AND NOT EXISTS(SELECT 1 FROM production_daily_report_target_events back WHERE back.source_event_id=event.id)
        LOOP
            IF NOT EXISTS(SELECT 1 FROM production_execution_segments segment
                          WHERE segment.id=(frozen.value->>'segmentId')::uuid
                            AND segment.source_plan_item_id=frozen.plan_item_id)
               OR (frozen.value->>'actualSurplusQty')::numeric IS DISTINCT FROM (
                   SELECT COALESCE(SUM(item.qty),0) FROM production_daily_report_items item
                   WHERE item.report_id=p_report AND item.execution_segment_id=(frozen.value->>'segmentId')::uuid
                     AND item.is_actual_surplus AND item.fqc_recovery_authorization_id IS NULL AND NOT item.is_deleted)
               OR (frozen.value->>'actualSurplusQty')::numeric > GREATEST(
                   (frozen.value->>'approvedMarginQty')::numeric-(frozen.value->>'otherReservedSurplusQty')::numeric,0) THEN
                RAISE EXCEPTION 'Final report actual surplus no longer matches its exact approved authorization'
                    USING ERRCODE='23514',CONSTRAINT='final_report_surplus_authorization_identity';
            END IF;
        END LOOP;
    END IF;

    FOR source IN
        SELECT execution_segment_id,SUM(qty) qty FROM production_daily_report_items
        WHERE report_id=p_report AND is_actual_surplus AND fqc_recovery_authorization_id IS NULL AND NOT is_deleted
        GROUP BY execution_segment_id ORDER BY execution_segment_id
    LOOP
        PERFORM id FROM production_execution_segments WHERE id=source.execution_segment_id FOR UPDATE;
        IF report_status=1 AND EXISTS (
            SELECT 1 FROM production_daily_report_target_events event
            CROSS JOIN LATERAL jsonb_array_elements(event.overproduction_authorizations->'segments') fact(value)
            WHERE event.report_id=p_report AND event.event_type='CAP'
              AND event.overproduction_authorizations IS NOT NULL
              AND (fact.value->>'segmentId')::uuid=source.execution_segment_id
              AND (fact.value->>'actualSurplusQty')::numeric=source.qty
              AND NOT EXISTS(SELECT 1 FROM production_daily_report_target_events back WHERE back.source_event_id=event.id)
        ) THEN
            CONTINUE;
        END IF;
        SELECT fn_execution_actual_surplus_available(source.execution_segment_id,p_report) INTO available;
        IF source.qty>available OR NOT fn_execution_overproduction_policy_applies(source.execution_segment_id) THEN
            RAISE EXCEPTION 'Actual surplus exceeds the effective approved rate; create a separate reviewed supplemental plan'
                USING ERRCODE='23514',CONSTRAINT='actual_output_effective_rate_limit';
        END IF;
    END LOOP;
END;
$$;
