-- 2026-10-06 口径（ADR-118 混流修复）：超量报工生成的「固定追加量」批次在带 proof
-- 回原任务行续报之前，一直占用原执行工单的公共超产额度。旧
-- fn_execution_actual_surplus_available 只按 planned×rate−已落 surplus 计算，
-- 无 proof 的超额行可把追加量以公共超产身份落回原工单，或再次触发预检生成
-- 第二张追加计划。新函数 fn_actual_supplement_pending_qty 汇总「已批准、有
-- proof、未红冲、无活跃 CLAIM」的追加量（活跃 CLAIM 判定与
-- fn_actual_supplement_reserved_original_qty 同一口径），再由可用额度扣除。
CREATE FUNCTION fn_actual_supplement_pending_qty(p_segment UUID, p_exclude_report UUID DEFAULT NULL)
RETURNS NUMERIC LANGUAGE sql STABLE AS $$
    SELECT COALESCE(SUM(request.supplement_qty),0) FROM production_actual_output_supplement_requests request
    LEFT JOIN production_actual_output_supplement_proofs proof ON proof.command_id=request.id
    WHERE request.source_execution_segment_id=p_segment AND request.status='APPROVED'
      AND (proof.id IS NULL OR NOT EXISTS(SELECT 1 FROM production_actual_output_supplement_reversals reversal WHERE reversal.proof_id=proof.id))
      AND proof.id IS NOT NULL
      AND NOT EXISTS(SELECT 1 FROM production_actual_output_supplement_claims claim
          JOIN production_daily_reports report ON report.id=claim.report_id
          WHERE claim.proof_id=proof.id AND claim.event_type='CLAIM' AND NOT report.is_deleted
            AND (report.status IN(0,1) OR report.id=p_exclude_report)
            AND NOT EXISTS(SELECT 1 FROM production_actual_output_supplement_claims release WHERE release.source_claim_id=claim.id));
$$;

-- 公共超产可用额度 = planned×rate − 已落 surplus − 未续报承接的固定追加量。
-- 续报（写入活跃 CLAIM）或红冲（reversal）后额度即恢复，追加量只能从
-- 「固定追加量·续报」入口整批带回原任务行申报。
CREATE OR REPLACE FUNCTION fn_execution_actual_surplus_available(p_segment UUID, p_exclude_report UUID DEFAULT NULL)
RETURNS NUMERIC LANGUAGE sql STABLE AS $$
    SELECT GREATEST(trunc(segment.planned_qty*segment.allowed_overproduction_rate,4)-COALESCE((
        SELECT SUM(item.qty) FROM production_daily_report_items item
        JOIN production_daily_reports report ON report.id=item.report_id
        WHERE item.execution_segment_id=segment.id AND item.is_actual_surplus
          AND item.fqc_recovery_authorization_id IS NULL AND NOT item.is_deleted AND NOT report.is_deleted
          AND report.status IN(0,1) AND (p_exclude_report IS NULL OR report.id<>p_exclude_report)),0)
        -fn_actual_supplement_pending_qty(p_segment,p_exclude_report),0)
    FROM production_execution_segments segment WHERE segment.id=p_segment;
$$;

-- V706 末次报工授权快照：捕获函数内联了 margin−other_reserved 公式，同步收紧——
-- 未续报承接的固定追加量计入 otherReservedSurplusQty（快照冻结值，旧快照不受
-- 影响；已被追加批次占用的额度不得再授权给本报告的公共超产行）。fn_assert_
-- actual_output_policy_limit_for_report 调用的是上面的可用额度函数，自动获得
-- 新口径，无需重建。
CREATE OR REPLACE FUNCTION fn_capture_final_report_surplus_authorizations()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE segment RECORD; entry JSONB; entries JSONB:='[]'::jsonb;
        actual_qty NUMERIC; other_reserved NUMERIC; margin NUMERIC; drafts TEXT;
BEGIN
    IF NEW.overproduction_authorizations IS NOT NULL THEN
        RAISE EXCEPTION 'Final-report authorization snapshots are generated by the database'
            USING ERRCODE='23514';
    END IF;
    IF NEW.event_type<>'CAP' THEN RETURN NEW; END IF;

    -- The preceding guard has locked and validated this exact plan item and report.
    -- Lock every affected segment in PostgreSQL UUID order before discovering drafts.
    PERFORM id FROM production_execution_segments
    WHERE source_plan_item_id=NEW.plan_item_id AND NOT is_deleted
      AND status NOT IN ('CANCELLED','REVERSED') ORDER BY id FOR UPDATE;

    SELECT string_agg(DISTINCT report.bill_no, '、' ORDER BY report.bill_no) INTO drafts
    FROM production_daily_reports report
    JOIN production_daily_report_items item ON item.report_id=report.id
    JOIN production_execution_segments affected ON affected.id=item.execution_segment_id
    WHERE affected.source_plan_item_id=NEW.plan_item_id AND NOT affected.is_deleted
      AND affected.status NOT IN ('CANCELLED','REVERSED')
      AND report.id<>NEW.report_id AND report.status=0 AND NOT report.is_deleted AND NOT item.is_deleted;
    IF drafts IS NOT NULL THEN
        RAISE EXCEPTION '该工单还有未审核报工单（%），请先审核或删除这些草稿，再提前完结', drafts
            USING ERRCODE='23514',CONSTRAINT='final_report_pending_drafts';
    END IF;

    FOR segment IN
        SELECT id,planned_qty,allowed_overproduction_rate,overproduction_rate_version
        FROM production_execution_segments
        WHERE source_plan_item_id=NEW.plan_item_id AND NOT is_deleted
          AND status NOT IN ('CANCELLED','REVERSED') ORDER BY id
    LOOP
        SELECT COALESCE(SUM(item.qty),0) INTO actual_qty
        FROM production_daily_report_items item
        WHERE item.report_id=NEW.report_id AND item.execution_segment_id=segment.id
          AND item.is_actual_surplus AND item.fqc_recovery_authorization_id IS NULL AND NOT item.is_deleted;
        SELECT COALESCE(SUM(item.qty),0) INTO other_reserved
        FROM production_daily_report_items item
        JOIN production_daily_reports report ON report.id=item.report_id
        WHERE item.execution_segment_id=segment.id AND item.is_actual_surplus
          AND item.fqc_recovery_authorization_id IS NULL AND NOT item.is_deleted
          AND NOT report.is_deleted AND report.status IN (0,1) AND report.id<>NEW.report_id;
        -- 2026-10-06：已批准未续报承接的固定追加量同属「已被别人占用的额度」；
        -- 通过本报告 CLAIM 回来的批次不算占用（与上面 other_reserved 排除本报告一致）。
        other_reserved:=other_reserved+fn_actual_supplement_pending_qty(segment.id,NEW.report_id);
        margin:=trunc(segment.planned_qty*segment.allowed_overproduction_rate,4);
        IF actual_qty>GREATEST(margin-other_reserved,0)
           OR (actual_qty>0 AND NOT fn_execution_overproduction_policy_applies(segment.id)) THEN
            RAISE EXCEPTION 'Actual surplus exceeds the effective approved rate; create a separate reviewed supplemental plan'
                USING ERRCODE='23514',CONSTRAINT='actual_output_effective_rate_limit';
        END IF;
        entry:=jsonb_build_object('segmentId',segment.id,'plannedQty',segment.planned_qty,
            'allowedRate',segment.allowed_overproduction_rate,'rateVersion',segment.overproduction_rate_version,
            'approvedMarginQty',margin,'otherReservedSurplusQty',other_reserved,'actualSurplusQty',actual_qty);
        entries:=entries||jsonb_build_array(entry);
    END LOOP;
    NEW.overproduction_authorizations:=jsonb_build_object('version',1,'segments',entries);
    RETURN NEW;
END;
$$;
