-- Actual production stays on its original execution/cost source. The allowance
-- classifies this physical batch; it never truncates the quantity or creates a second plan.
ALTER TABLE production_daily_report_items
    ADD COLUMN is_over_limit BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN over_limit_reason TEXT,
    ADD COLUMN overproduction_authorization_snapshot JSONB,
    ADD CONSTRAINT daily_report_over_limit_shape CHECK (
        (NOT is_over_limit AND over_limit_reason IS NULL)
        OR (is_over_limit AND is_actual_surplus AND is_public_output
            AND output_batch_id IS NOT NULL AND destination='WAREHOUSE'
            AND over_limit_reason IS NOT NULL AND length(btrim(over_limit_reason)) BETWEEN 2 AND 500)),
    ADD CONSTRAINT daily_report_overproduction_snapshot_shape CHECK (
        overproduction_authorization_snapshot IS NULL
        OR (is_actual_surplus AND fqc_recovery_authorization_id IS NULL
            AND jsonb_typeof(overproduction_authorization_snapshot)='object'
            AND overproduction_authorization_snapshot->>'version'='1'));

CREATE INDEX idx_daily_report_over_limit ON production_daily_report_items(report_id,execution_segment_id)
    WHERE is_over_limit AND NOT is_deleted;

ALTER TABLE production_daily_report_items
    DROP CONSTRAINT production_daily_report_items_output_route_reason_chk,
    ADD CONSTRAINT production_daily_report_items_output_route_reason_chk CHECK (
        output_route_reason IS NULL OR (destination='WAREHOUSE' AND output_route_reason IN (
            'USER_CHOSEN','RECEIVERS_FULL','PUBLIC_SHARE','ACTUAL_SURPLUS','OVER_LIMIT',
            'SOURCE_SHARE_USED_UP','DEMAND_ALREADY_COVERED','RECEIVER_STATUS','PLAN_NOT_ACTIVE',
            'PACKAGE_NOT_CONFIRMED','DEMAND_CLOSED','WORKSHOP_BIN_NOT_OPEN','DIFFERENT_WORKSHOP',
            'SUBCONTRACT_ROUTE','BUY_ROUTE','NO_PARENT_RELATION','SELF','GOODS_MISMATCH','SOURCE_INVALID',
            'TARGET_INVALID','NO_RECEIVER_ISSUED_YET','NOT_A_COMPONENT')));

-- Baseline gate. V823 adds an exact planning decision; FQC PASS is a separate gate.
CREATE FUNCTION fn_daily_report_output_authorized(p_item UUID) RETURNS BOOLEAN LANGUAGE sql STABLE AS $$
    SELECT COALESCE((SELECT NOT is_over_limit FROM production_daily_report_items WHERE id=p_item),FALSE)
$$;

CREATE FUNCTION fn_execution_tolerance_surplus_qty(p_segment UUID,p_include_drafts BOOLEAN DEFAULT FALSE)
RETURNS NUMERIC LANGUAGE sql STABLE AS $$
    SELECT COALESCE(SUM(item.qty),0)
    FROM production_daily_report_items item JOIN production_daily_reports report ON report.id=item.report_id
    WHERE item.execution_segment_id=p_segment AND item.is_actual_surplus AND NOT item.is_over_limit
      AND item.fqc_recovery_authorization_id IS NULL AND NOT item.is_deleted AND NOT report.is_deleted
      AND (report.status=1 OR (p_include_drafts AND report.status=0))
$$;

CREATE FUNCTION fn_guard_report_over_limit_snapshot() RETURNS TRIGGER LANGUAGE plpgsql AS $$
DECLARE source production_daily_report_items%ROWTYPE;
        segment production_execution_segments%ROWTYPE;
        available NUMERIC; prior_qty NUMERIC; margin NUMERIC; pending NUMERIC;
BEGIN
    IF TG_OP='UPDATE' THEN
        IF OLD.overproduction_authorization_snapshot IS DISTINCT FROM NEW.overproduction_authorization_snapshot
           OR OLD.is_over_limit IS DISTINCT FROM NEW.is_over_limit
           OR OLD.over_limit_reason IS DISTINCT FROM NEW.over_limit_reason
           OR ((OLD.overproduction_authorization_snapshot IS NOT NULL OR OLD.is_over_limit)
               AND (OLD.report_id,OLD.execution_segment_id,OLD.plan_item_id,OLD.output_batch_id,
                    OLD.output_batch_qty,OLD.qty,OLD.is_actual_surplus,OLD.is_public_output,
                    OLD.is_over_limit,OLD.over_limit_reason,OLD.fqc_recovery_authorization_id)
               IS DISTINCT FROM
                   (NEW.report_id,NEW.execution_segment_id,NEW.plan_item_id,NEW.output_batch_id,
                    NEW.output_batch_qty,NEW.qty,NEW.is_actual_surplus,NEW.is_public_output,
                    NEW.is_over_limit,NEW.over_limit_reason,NEW.fqc_recovery_authorization_id)) THEN
            RAISE EXCEPTION 'Reported output allowance identity is immutable; replace the draft through its normal save command'
                USING ERRCODE='23514',CONSTRAINT='report_over_limit_snapshot_identity';
        END IF;
        RETURN NEW;
    END IF;
    IF NEW.overproduction_authorization_snapshot IS NOT NULL THEN
        RAISE EXCEPTION 'Output allowance snapshots are generated by the database'
            USING ERRCODE='23514',CONSTRAINT='report_over_limit_snapshot_identity';
    END IF;
    IF NEW.fqc_recovery_authorization_id IS NOT NULL THEN
        SELECT item.* INTO source FROM production_fqc_recovery_authorizations authority
        JOIN production_daily_report_items item ON item.id=authority.source_report_item_id
        WHERE authority.id=NEW.fqc_recovery_authorization_id;
        IF NOT FOUND OR NEW.is_over_limit IS DISTINCT FROM source.is_over_limit
           OR NEW.over_limit_reason IS DISTINCT FROM source.over_limit_reason THEN
            RAISE EXCEPTION 'Quality recovery must retain its original over-limit responsibility'
                USING ERRCODE='23514',CONSTRAINT='report_over_limit_recovery_identity';
        END IF;
        RETURN NEW;
    END IF;
    IF NOT NEW.is_actual_surplus THEN RETURN NEW; END IF;
    SELECT * INTO segment FROM production_execution_segments WHERE id=NEW.execution_segment_id FOR UPDATE;
    IF NOT FOUND OR NOT fn_execution_overproduction_policy_applies(segment.id)
       OR segment.source_plan_item_id IS DISTINCT FROM NEW.plan_item_id THEN
        RAISE EXCEPTION 'Actual surplus requires its original production task'
            USING ERRCODE='23514',CONSTRAINT='report_over_limit_source';
    END IF;
    SELECT COALESCE(SUM(item.qty),0) INTO prior_qty
    FROM production_daily_report_items item JOIN production_daily_reports report ON report.id=item.report_id
    WHERE item.execution_segment_id=segment.id AND item.is_actual_surplus
      AND item.fqc_recovery_authorization_id IS NULL AND NOT item.is_deleted
      AND NOT report.is_deleted AND report.status IN(0,1);
    pending:=fn_actual_supplement_pending_qty(segment.id,NEW.report_id);
    margin:=trunc(segment.planned_qty*segment.allowed_overproduction_rate,4);
    available:=GREATEST(margin-prior_qty-pending,0);
    IF (NEW.is_over_limit AND (available<>0 OR pending>0))
       OR (NOT NEW.is_over_limit AND NEW.qty>available) THEN
        RAISE EXCEPTION 'Actual production must consume its remaining allowance before the over-limit slice; fixed supplements must resume their original proof'
            USING ERRCODE='23514',CONSTRAINT='report_over_limit_allowance_split';
    END IF;
    NEW.overproduction_authorization_snapshot:=jsonb_build_object(
        'version',1,'reportItemId',NEW.id,'reportId',NEW.report_id,
        'executionSegmentId',segment.id,'outputBatchId',NEW.output_batch_id,
        'qty',NEW.qty,'isOverLimit',NEW.is_over_limit,'plannedQty',segment.planned_qty,
        'allowedRate',segment.allowed_overproduction_rate,'rateVersion',segment.overproduction_rate_version,
        'availableQtyBefore',available,'priorSurplusQty',prior_qty,
        'approvedMarginQty',margin,'pendingSupplementQty',pending);
    RETURN NEW;
END;
$$;
CREATE TRIGGER trg_report_over_limit_snapshot BEFORE INSERT OR UPDATE ON production_daily_report_items
    FOR EACH ROW EXECUTE FUNCTION fn_guard_report_over_limit_snapshot();

-- The physical/cost totals intentionally continue to include BOTH normal and held
-- surplus. Only the ordinary tolerance lower bound excludes an exceptional batch.
DO $rate_bound$
DECLARE definition TEXT;
BEGIN
    SELECT pg_get_functiondef('fn_production_rate_request_ready(uuid)'::regprocedure) INTO definition;
    IF position('fn_execution_actual_surplus_qty(segment.id,TRUE)' IN definition)=0 THEN
        RAISE EXCEPTION 'V822 production rate lower-bound anchor changed';
    END IF;
    EXECUTE replace(definition,'fn_execution_actual_surplus_qty(segment.id,TRUE)',
        'fn_execution_tolerance_surplus_qty(segment.id,TRUE)');
END;
$rate_bound$;

-- CAP keeps the exact ordinary allowance of the early-final report. Exceptional
-- output remains a separate physical fact and cannot be legitimized by CAP.
DO $cap_snapshot$
DECLARE definition TEXT; anchor TEXT;
BEGIN
    SELECT pg_get_functiondef('fn_capture_final_report_surplus_authorizations()'::regprocedure) INTO definition;
    anchor:='WHERE item.report_id=NEW.report_id AND item.execution_segment_id=segment.id';
    IF position(anchor IN definition)=0 THEN RAISE EXCEPTION 'V822 final report capture anchor changed'; END IF;
    EXECUTE replace(definition,anchor,anchor||' AND NOT item.is_over_limit');
END;
$cap_snapshot$;

CREATE OR REPLACE FUNCTION fn_assert_actual_output_policy_limit_for_report(p_report UUID)
RETURNS VOID LANGUAGE plpgsql AS $$
DECLARE source RECORD; frozen RECORD; available NUMERIC; report_status SMALLINT;
BEGIN
    SELECT status INTO report_status FROM production_daily_reports
    WHERE id=p_report AND status IN(0,1) AND NOT is_deleted;
    IF NOT FOUND THEN RETURN; END IF;

    -- Existing CAP snapshots remain valid: all historical rows have is_over_limit=false.
    IF report_status=1 THEN
        FOR frozen IN
            SELECT event.plan_item_id,fact.value
            FROM production_daily_report_target_events event
            CROSS JOIN LATERAL jsonb_array_elements(event.overproduction_authorizations->'segments') fact(value)
            WHERE event.report_id=p_report AND event.event_type='CAP'
              AND event.overproduction_authorizations IS NOT NULL
              AND NOT EXISTS(SELECT 1 FROM production_daily_report_target_events back WHERE back.source_event_id=event.id)
        LOOP
            IF NOT EXISTS(SELECT 1 FROM production_execution_segments segment
                          WHERE segment.id=(frozen.value->>'segmentId')::uuid AND segment.source_plan_item_id=frozen.plan_item_id)
               OR (frozen.value->>'actualSurplusQty')::numeric IS DISTINCT FROM (
                    SELECT COALESCE(SUM(item.qty),0) FROM production_daily_report_items item
                    WHERE item.report_id=p_report AND item.execution_segment_id=(frozen.value->>'segmentId')::uuid
                      AND item.is_actual_surplus AND NOT item.is_over_limit
                      AND item.fqc_recovery_authorization_id IS NULL AND NOT item.is_deleted)
               OR (frozen.value->>'actualSurplusQty')::numeric > GREATEST(
                    (frozen.value->>'approvedMarginQty')::numeric-(frozen.value->>'otherReservedSurplusQty')::numeric,0) THEN
                RAISE EXCEPTION 'Final report actual surplus no longer matches its exact approved authorization'
                    USING ERRCODE='23514',CONSTRAINT='final_report_surplus_authorization_identity';
            END IF;
        END LOOP;
    END IF;

    -- New slice authorization is frozen by the database while holding its segment
    -- lock. Approval, another report, a rate change or CAP cannot rewrite that fact.
    IF EXISTS(SELECT 1 FROM production_daily_report_items item
        WHERE item.report_id=p_report AND NOT item.is_deleted
          AND item.overproduction_authorization_snapshot IS NOT NULL AND (
            (item.overproduction_authorization_snapshot->>'reportItemId')::uuid IS DISTINCT FROM item.id
            OR (item.overproduction_authorization_snapshot->>'reportId')::uuid IS DISTINCT FROM item.report_id
            OR (item.overproduction_authorization_snapshot->>'executionSegmentId')::uuid IS DISTINCT FROM item.execution_segment_id
            OR (item.overproduction_authorization_snapshot->>'outputBatchId')::uuid IS DISTINCT FROM item.output_batch_id
            OR (item.overproduction_authorization_snapshot->>'qty')::numeric IS DISTINCT FROM item.qty
            OR (item.overproduction_authorization_snapshot->>'isOverLimit')::boolean IS DISTINCT FROM item.is_over_limit
            OR (item.is_over_limit AND (item.overproduction_authorization_snapshot->>'availableQtyBefore')::numeric<>0)
            OR (NOT item.is_over_limit AND item.qty>(item.overproduction_authorization_snapshot->>'availableQtyBefore')::numeric))) THEN
        RAISE EXCEPTION 'Actual output no longer matches its captured allowance'
            USING ERRCODE='23514',CONSTRAINT='report_over_limit_snapshot_identity';
    END IF;

    -- Legacy drafts/proofs have no new snapshot and keep their established guard.
    FOR source IN SELECT execution_segment_id,SUM(qty) qty FROM production_daily_report_items
        WHERE report_id=p_report AND is_actual_surplus AND fqc_recovery_authorization_id IS NULL
          AND NOT is_deleted AND overproduction_authorization_snapshot IS NULL
        GROUP BY execution_segment_id ORDER BY execution_segment_id
    LOOP
        PERFORM id FROM production_execution_segments WHERE id=source.execution_segment_id FOR UPDATE;
        IF report_status=1 AND EXISTS(
            SELECT 1 FROM production_daily_report_target_events event
            CROSS JOIN LATERAL jsonb_array_elements(event.overproduction_authorizations->'segments') fact(value)
            WHERE event.report_id=p_report AND event.event_type='CAP' AND event.overproduction_authorizations IS NOT NULL
              AND (fact.value->>'segmentId')::uuid=source.execution_segment_id
              AND (fact.value->>'actualSurplusQty')::numeric=source.qty
              AND NOT EXISTS(SELECT 1 FROM production_daily_report_target_events back WHERE back.source_event_id=event.id)) THEN
            CONTINUE;
        END IF;
        SELECT fn_execution_actual_surplus_available(source.execution_segment_id,p_report) INTO available;
        IF source.qty>available OR NOT fn_execution_overproduction_policy_applies(source.execution_segment_id) THEN
            RAISE EXCEPTION 'Legacy actual surplus exceeds its effective approved allowance'
                USING ERRCODE='23514',CONSTRAINT='actual_output_effective_rate_limit';
        END IF;
    END LOOP;
END;
$$;

COMMENT ON COLUMN production_daily_report_items.is_over_limit IS
    'Actual physical surplus beyond the captured allowance; remains public and on the original cost source, requires an independent planning disposition before stock release';
COMMENT ON COLUMN production_daily_report_items.overproduction_authorization_snapshot IS
    'Database-captured immutable allowance per original actual-output slice. Historical rows and quality recovery keep their existing provenance.';
