-- CreateTable
CREATE TABLE "WebsiteStateAuthority" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "authorityUuid" TEXT NOT NULL,
    "mediaGeneration" INTEGER NOT NULL DEFAULT 0,
    "initializedAt" DATETIME,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "WebsiteStateAuthority_authorityUuid_check" CHECK (
        "authorityUuid" = 'UNBOUND' OR (
            length("authorityUuid") = 36
            AND substr("authorityUuid", 9, 1) = '-'
            AND substr("authorityUuid", 14, 1) = '-'
            AND substr("authorityUuid", 19, 1) = '-'
            AND substr("authorityUuid", 24, 1) = '-'
            AND lower("authorityUuid") = "authorityUuid"
            AND replace("authorityUuid", '-', '') NOT GLOB '*[^0-9a-f]*'
        )
    )
);

-- The UUID is deliberately not generated by a migration or discovered from a
-- mounted volume.  The root installer pins an operator-approved UUID and the
-- stopped activation transaction replaces this sentinel exactly once.
INSERT INTO "WebsiteStateAuthority" (
    "id", "authorityUuid", "mediaGeneration", "initializedAt", "createdAt", "updatedAt"
) VALUES (
    'production', 'UNBOUND', 0, NULL, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

-- CreateTable
CREATE TABLE "WebsiteMediaObject" (
    "publicPath" TEXT NOT NULL PRIMARY KEY,
    "authorityId" TEXT NOT NULL,
    "sha256" TEXT NOT NULL,
    "sizeBytes" INTEGER NOT NULL,
    "state" TEXT NOT NULL DEFAULT 'PENDING',
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    CONSTRAINT "WebsiteMediaObject_authorityId_fkey" FOREIGN KEY ("authorityId") REFERENCES "WebsiteStateAuthority" ("id") ON DELETE RESTRICT ON UPDATE CASCADE,
    CONSTRAINT "WebsiteMediaObject_publicPath_check" CHECK (
        "publicPath" LIKE '/uploads/%'
        AND length("publicPath") BETWEEN 11 AND 500
        AND instr("publicPath", '\\') = 0
        AND instr("publicPath", '//') = 0
        AND instr("publicPath", '/./') = 0
        AND instr("publicPath", '/../') = 0
        AND instr("publicPath", '?') = 0
        AND instr("publicPath", '#') = 0
        AND instr("publicPath", '%') = 0
        AND instr("publicPath", char(9)) = 0
        AND instr("publicPath", char(10)) = 0
        AND instr("publicPath", char(13)) = 0
        AND instr("publicPath", ' ') = 0
        AND substr("publicPath", -2) != '/.'
        AND substr("publicPath", -3) != '/..'
    ),
    CONSTRAINT "WebsiteMediaObject_sha256_check" CHECK (
        length("sha256") = 64
        AND "sha256" NOT GLOB '*[^0-9a-f]*'
    ),
    CONSTRAINT "WebsiteMediaObject_sizeBytes_check" CHECK ("sizeBytes" > 0),
    CONSTRAINT "WebsiteMediaObject_state_check" CHECK ("state" IN ('PENDING', 'COMMITTED'))
);

-- Deterministic bootstrap for already audited legacy media.  Other CMS uploads
-- are reconciled by the stopped authority-initialization gate; nothing is
-- inferred from filenames and no business reference is rewritten here.
INSERT INTO "WebsiteMediaObject" (
    "publicPath", "authorityId", "sha256", "sizeBytes", "state", "createdAt", "updatedAt"
)
SELECT
    "publicPath", 'production', lower("sha256"), "bytes", 'COMMITTED', "createdAt", "updatedAt"
FROM "LegacyMediaAsset"
WHERE "publicPath" LIKE '/uploads/%';

-- CreateIndex
CREATE UNIQUE INDEX "WebsiteStateAuthority_authorityUuid_key" ON "WebsiteStateAuthority"("authorityUuid");

-- CreateIndex
CREATE INDEX "WebsiteMediaObject_authorityId_state_idx" ON "WebsiteMediaObject"("authorityId", "state");

-- CreateIndex
CREATE INDEX "WebsiteMediaObject_state_createdAt_idx" ON "WebsiteMediaObject"("state", "createdAt");

-- A full media verification reads one generation before and after its
-- filesystem scan.  These signed-schema triggers make every relevant DB-side
-- ledger or business-reference mutation observable without coupling the
-- verifier to application code paths.
CREATE TRIGGER "WebsiteMediaObject_media_generation_insert"
AFTER INSERT ON "WebsiteMediaObject"
BEGIN
    UPDATE "WebsiteStateAuthority"
    SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP
    WHERE "id" = 'production';
END;

CREATE TRIGGER "WebsiteMediaObject_media_generation_update"
AFTER UPDATE ON "WebsiteMediaObject"
BEGIN
    UPDATE "WebsiteStateAuthority"
    SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP
    WHERE "id" = 'production';
END;

CREATE TRIGGER "WebsiteMediaObject_media_generation_delete"
AFTER DELETE ON "WebsiteMediaObject"
BEGIN
    UPDATE "WebsiteStateAuthority"
    SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP
    WHERE "id" = 'production';
END;

CREATE TRIGGER "Series_media_generation_insert"
AFTER INSERT ON "Series"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "Series_media_generation_update"
AFTER UPDATE OF "coverImage" ON "Series"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "Series_media_generation_delete"
AFTER DELETE ON "Series"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;

CREATE TRIGGER "SeriesMedia_media_generation_insert"
AFTER INSERT ON "SeriesMedia"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "SeriesMedia_media_generation_update"
AFTER UPDATE OF "image" ON "SeriesMedia"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "SeriesMedia_media_generation_delete"
AFTER DELETE ON "SeriesMedia"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;

CREATE TRIGGER "Product_media_generation_insert"
AFTER INSERT ON "Product"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "Product_media_generation_update"
AFTER UPDATE OF "image", "gallery" ON "Product"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "Product_media_generation_delete"
AFTER DELETE ON "Product"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;

CREATE TRIGGER "ProductVariant_media_generation_insert"
AFTER INSERT ON "ProductVariant"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "ProductVariant_media_generation_update"
AFTER UPDATE OF "image", "gallery" ON "ProductVariant"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "ProductVariant_media_generation_delete"
AFTER DELETE ON "ProductVariant"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;

CREATE TRIGGER "ScenePreset_media_generation_insert"
AFTER INSERT ON "ScenePreset"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "ScenePreset_media_generation_update"
AFTER UPDATE OF "backgroundImage" ON "ScenePreset"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "ScenePreset_media_generation_delete"
AFTER DELETE ON "ScenePreset"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;

CREATE TRIGGER "LegacyMediaAsset_media_generation_insert"
AFTER INSERT ON "LegacyMediaAsset"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "LegacyMediaAsset_media_generation_update"
AFTER UPDATE OF "publicPath" ON "LegacyMediaAsset"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "LegacyMediaAsset_media_generation_delete"
AFTER DELETE ON "LegacyMediaAsset"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;

CREATE TRIGGER "News_media_generation_insert"
AFTER INSERT ON "News"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "News_media_generation_update"
AFTER UPDATE OF "coverImage" ON "News"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "News_media_generation_delete"
AFTER DELETE ON "News"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;

CREATE TRIGGER "CaseItem_media_generation_insert"
AFTER INSERT ON "CaseItem"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "CaseItem_media_generation_update"
AFTER UPDATE OF "coverImage" ON "CaseItem"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "CaseItem_media_generation_delete"
AFTER DELETE ON "CaseItem"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;

CREATE TRIGGER "Setting_media_generation_insert"
AFTER INSERT ON "Setting"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "Setting_media_generation_update"
AFTER UPDATE OF "i18n" ON "Setting"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
CREATE TRIGGER "Setting_media_generation_delete"
AFTER DELETE ON "Setting"
BEGIN
    UPDATE "WebsiteStateAuthority" SET "mediaGeneration" = "mediaGeneration" + 1, "updatedAt" = CURRENT_TIMESTAMP WHERE "id" = 'production';
END;
