$ErrorActionPreference = 'Stop'

$paths = @{
    Nginx = 'nginx/uten-imp.conf.example'
    LegacyLanNginx = 'nginx/uten-imp-http-lan.conf'
    AppUnit = 'systemd/uten-imp.service.example'
    MigratorUnit = 'systemd/uten-imp-migrate.service.example'
    WatchdogUnit = 'systemd/uten-imp-watchdog.service.example'
    WatchdogTimer = 'systemd/uten-imp-watchdog.timer.example'
    EntryWatchdogUnit = 'systemd/uten-imp-entry-watchdog.service.example'
    EntryWatchdogTimer = 'systemd/uten-imp-entry-watchdog.timer.example'
    WatchdogScript = 'watchdog/uten-imp-watchdog.sh'
    EntryWatchdogScript = 'watchdog/uten-imp-entry-watchdog.sh'
    ReadinessGate = 'setup/wait-for-erp-readiness.sh'
    NginxOverride = 'systemd/nginx-uten-imp-override.conf.example'
    DeployReadme = 'README.md'
    CurrentTestServerStatus = 'current-test-server-status.zh-CN.md'
    ReleaseReadme = 'release/README.md'
    OperatorGuide = 'operator-guide.zh-CN.md'
    ServerHandoff = 'server-handoff.example.md'
    WebsiteGuide = '../website/docs/cloud-server-deployment.md'
    Phase1 = 'setup/phase1-hardening.sh'
    Phase1b = 'setup/phase1b-ssh-key-only.sh'
    Phase2 = 'setup/phase2-postgres.sh'
    Phase3 = 'setup/phase3-runtime.sh'
    Phase4 = 'setup/phase4-updater-nginx.sh'
    ServerEnvInstaller = 'setup/install-server-env.sh'
    VerifierBootstrap = 'setup/bootstrap-release-verifier.sh'
    LegacyUpdaterRetirement = 'setup/retire-legacy-updater.sh'
    EnvValidator = 'setup/validate-server-env.sh'
    MigratorEnvValidator = 'setup/validate-migrator-env.sh'
    RoleHardener = 'setup/harden-existing-postgres-roles.sh'
    RestoreDrill = 'setup/drill-restore.sh'
    RetentionInstaller = 'setup/install-release-retention.sh'
    UpdaterService = 'updater/uten-imp-updater.service'
    UpdaterTimer = 'updater/uten-imp-updater.timer'
    UpdaterWrapper = 'updater/uten-imp-updater.sh'
    ActivateWrapper = 'updater/uten-imp-activate.sh'
    RecoverWrapper = 'updater/uten-imp-recover.sh'
    RetentionWrapper = 'updater/uten-imp-retention.sh'
    ReleaseUpdater = 'updater/release_updater.py'
    DatabaseRecoveryVerifier = 'updater/database_recovery_verifier.py'
    RuntimeBootVerifier = 'updater/runtime_boot_verifier.py'
    StorageBootVerifier = 'updater/storage_boot_verifier.py'
    StorageMountObserver = 'updater/storage_mount_observer.py'
    MigrationAuthorization = 'updater/migration_authorization.py'
    StorageObserverUnit = 'systemd/uten-imp-storage-observer.service.example'
    RetentionManager = 'updater/retention_manager.py'
    RetentionPolicy = 'updater/retention-policy.json.example'
    ReleaseGuard = 'updater/release_guard.py'
    OssValidator = 'updater/validate_oss_pull_env.py'
    WheelhouseBuilder = 'updater/build-wheelhouse.sh'
    ReleaseTools = 'release/release_tools.py'
    CloudNginx = 'cloud/nginx-cloud.conf.example'
    CloudSystemd = 'cloud/uten-imp-cloud.service.example'
    CloudReadme = 'cloud/README-cloud.md'
    PreparePrimary = 'postgres/prepare-primary.sh'
    CloneReplica = 'postgres/clone-replica.sh'
    PrepareStandbyHba = 'postgres/prepare-standby-hba.sh'
    ReplicationHarness = 'postgres/verify-replication-docker.ps1'
    BackupReadme = 'postgres/backup/README.zh-CN.md'
    Repo2Renderer = 'postgres/backup/pgbackrest_repo2.py'
    BackupHealth = 'postgres/backup/pgbackrest_health.py'
    BackupAlert = 'postgres/backup/backup_alert.py'
    BackupAcceptance = 'postgres/backup/backup_acceptance.py'
    BackupLockedJob = 'postgres/backup/locked_job.py'
    Repo2BackupUnit = 'systemd/uten-pgbackup-repo2.service.example'
    Repo1BackupUnit = 'systemd/uten-pgbackup.service.example'
    Repo2BackupTimer = 'systemd/uten-pgbackup-repo2.timer.example'
    BackupHealthUnit = 'systemd/uten-pgbackup-health.service.example'
    BackupHealthTimer = 'systemd/uten-pgbackup-health.timer.example'
    Repo1BackupOverride = 'systemd/uten-pgbackup-repo1-override.conf.example'
    PostgresStorageDropIn = 'systemd/postgresql-uten-imp-storage.conf.example'
    BackupAlertUnit = 'systemd/uten-pgbackup-alert@.service.example'
    BackupAlertDrainTimer = 'systemd/uten-pgbackup-alert-drain.timer.example'
    RetentionUnit = 'systemd/uten-imp-retention.service.example'
    RetentionTimer = 'systemd/uten-imp-retention.timer.example'
    RetentionAlertUnit = 'systemd/uten-imp-retention-alert@.service.example'
    InternalTestProfile = '../server/src/main/resources/application-internal-test.yml'
    InternalTestGate = '../server/src/main/java/com/uten/imp/config/InternalTestRuntimeSafetyGate.java'
    InternalTestEnv = 'setup/server.env.internal-test.example'
    InternalTestEnvValidator = 'setup/validate-internal-test-server-env.sh'
    InternalTestStorageValidator = 'setup/validate-internal-test-storage.sh'
    InternalTestUnit = 'systemd/uten-imp-internal-test.service.example'
    InternalTestNginx = 'nginx/uten-imp-internal-test.conf.example'
    InternalTestGuide = 'internal-test-runtime.zh-CN.md'
    InternalTestOnboardingGuide = 'setup/EXISTING_TEST_HOST_INTERNAL_TEST_ONBOARDING.zh-CN.md'
    NvmeCommissioner = 'setup/existing-test-host-nvme-commissioner.py'
    NvmeCommissionerTest = 'setup/test_existing_test_host_nvme_commissioner.py'
    NvmeCommissioningGuide = 'setup/EXISTING_TEST_HOST_NVME_COMMISSIONING.zh-CN.md'
    NvmeEarlyResumeUnit = 'systemd/uten-imp-nvme-commissioning-resume.service.example'
    NvmeLateResumeUnit = 'systemd/uten-imp-nvme-commissioning-late-resume.service.example'
    NvmeLateResumeTimer = 'systemd/uten-imp-nvme-commissioning-late-resume.timer.example'
    NvmeGateAuthorizerUnit = 'systemd/uten-imp-nvme-gate-authorizer.service.example'
    NvmeActiveTransactionGate = 'systemd/uten-imp-nvme-active-transaction-gate.conf.example'
    WebsiteInquiryController = '../server/src/main/java/com/uten/imp/features/webinquiry/WebsiteInquiryController.java'
    AttachmentController = '../server/src/main/java/com/uten/imp/features/attachment/AttachmentController.java'
}

$text = @{}
foreach ($entry in $paths.GetEnumerator()) {
    $path = Join-Path $PSScriptRoot $entry.Value
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Missing deployment file: $($entry.Key) ($path)"
    }
    $text[$entry.Key] = Get-Content -LiteralPath $path -Raw -Encoding UTF8
}

$repoRoot = Split-Path -Parent $PSScriptRoot
$workflowPath = Join-Path $repoRoot '.github/workflows/release.yml'
$oidcAcceptanceWorkflowPath = Join-Path $repoRoot '.github/workflows/aliyun-oidc-acceptance.yml'
$webIndexPath = Join-Path $repoRoot 'web/index.html'
$webUpdatePath = Join-Path $repoRoot 'web/update_check.js'
$websiteConfigPath = Join-Path $repoRoot 'website/next.config.mjs'
$websiteAssemblerPath = Join-Path $repoRoot 'website/deploy/assemble-release.mjs'
$websiteRuntimeValidatorPath = Join-Path $repoRoot 'website/deploy/validate-runtime.sh'
$releaseSecurityTestPath = Join-Path $repoRoot 'deploy/updater/test_release_security.py'
$ossEnvTestPath = Join-Path $repoRoot 'deploy/updater/test_validate_oss_pull_env.py'
foreach ($path in @($workflowPath, $oidcAcceptanceWorkflowPath, $webIndexPath, $webUpdatePath, $websiteConfigPath, $websiteAssemblerPath, $websiteRuntimeValidatorPath, $releaseSecurityTestPath, $ossEnvTestPath)) {
    if (-not (Test-Path -LiteralPath $path -PathType Leaf)) {
        throw "Missing cross-stack deployment file: $path"
    }
}
$workflow = Get-Content -LiteralPath $workflowPath -Raw -Encoding UTF8
$oidcAcceptanceWorkflow = Get-Content -LiteralPath $oidcAcceptanceWorkflowPath -Raw -Encoding UTF8
$webIndex = Get-Content -LiteralPath $webIndexPath -Raw -Encoding UTF8
$webUpdate = Get-Content -LiteralPath $webUpdatePath -Raw -Encoding UTF8
$websiteConfig = Get-Content -LiteralPath $websiteConfigPath -Raw -Encoding UTF8
$websiteAssembler = Get-Content -LiteralPath $websiteAssemblerPath -Raw -Encoding UTF8
$websiteRuntimeValidator = Get-Content -LiteralPath $websiteRuntimeValidatorPath -Raw -Encoding UTF8

function Assert-Contains {
    param([string] $Value, [string] $Expected, [string] $Label)
    if (-not $Value.Contains($Expected)) {
        throw "Missing deployment contract: $Label"
    }
}

function Assert-NotContains {
    param([string] $Value, [string] $Forbidden, [string] $Label)
    if ($Value.Contains($Forbidden)) {
        throw "Forbidden deployment contract: $Label"
    }
}

function Assert-Regex {
    param([string] $Value, [string] $Pattern, [string] $Label)
    if (-not [regex]::IsMatch($Value, $Pattern)) {
        throw "Missing deployment pattern: $Label"
    }
}

# Dedicated internal ERP test profile: production-like network/secrets/runtime
# boundaries with one fixed NVMe local-storage exception. Production/cloud OSS
# contracts below remain independent and unchanged.
$internalProfile = $text.InternalTestProfile
Assert-Contains $internalProfile 'address: 127.0.0.1' 'internal-test loopback backend'
Assert-Contains $internalProfile 'lazy-initialization: false' 'internal-test global lazy initialization disabled'
Assert-Contains $internalProfile 'enabled: false' 'internal-test runtime Flyway and external features closed'
Assert-Contains $internalProfile 'require-https: true' 'internal-test application HTTPS requirement'
Assert-Contains $internalProfile 'swagger-enabled: false' 'internal-test Swagger disabled'
Assert-Contains $internalProfile 'provider: local' 'internal-test local attachment provider'
Assert-Contains $internalProfile 'uploads-enabled: false' 'internal-test attachment intake disabled'
Assert-Contains $internalProfile 'local-dir: /data/uten-imp/attachments' 'fixed internal-test NVMe attachment path'
Assert-NotContains $internalProfile 'UTEN_STORAGE_LOCAL_DIR' 'overrideable internal-test attachment path'
Assert-NotContains $internalProfile 'UTEN_OSS_' 'internal-test OSS credential/config surface'
Assert-Contains $text.InternalTestGate 'internal-test must be the only active Spring profile' 'exclusive internal-test profile gate'
Assert-Contains $text.InternalTestGate 'prod}/{@code cloud}' 'independent production storage gate documentation'
Assert-Contains $text.InternalTestEnv 'UTEN_PROFILE=internal-test' 'internal-test environment identity'
Assert-Contains $text.InternalTestEnvValidator 'expect_exact SPRING_FLYWAY_ENABLED false' 'internal-test runtime Flyway validator'
Assert-Contains $text.InternalTestEnvValidator '#!/bin/bash' 'internal-test fixed shell interpreter'
Assert-Contains $text.InternalTestEnvValidator 'expect_exact UTEN_STORAGE_LOCAL_DIR /data/uten-imp/attachments' 'internal-test environment fixed storage path'
Assert-Contains $text.InternalTestEnvValidator 'validate_supported_environment_keys' 'internal-test environment key allowlist'
Assert-Contains $text.InternalTestEnvValidator 'unsupported environment key:' 'internal-test unknown environment key refusal'
Assert-Contains $text.InternalTestEnvValidator 'ipaddress.ip_network(raw, strict=True)' 'internal-test canonical CIDR parser'
Assert-Contains $text.InternalTestEnvValidator 'network.prefixlen > parent.prefixlen' 'internal-test strict private subnet requirement'
Assert-NotContains $text.InternalTestEnv 'SPRING_MAIN_LAZY_INITIALIZATION' 'internal-test lazy-init environment override surface'
if ([regex]::IsMatch($text.InternalTestEnvValidator, '(?m)^\s*source\s')) {
    throw 'Forbidden deployment contract: internal-test environment shell execution'
}
Assert-NotContains $text.InternalTestEnvValidator 'eval ' 'internal-test environment eval execution'
Assert-Contains $text.InternalTestStorageValidator 'capacity_bytes >= 300 * 1024 * 1024 * 1024' 'internal-test minimum NVMe data capacity'
Assert-Contains $text.InternalTestStorageValidator '-o ROTA "$source_device"' 'internal-test non-rotational storage check'
Assert-NotContains $text.InternalTestStorageValidator 'mkfs' 'storage preflight filesystem mutation'
Assert-Contains $text.InternalTestUnit '-Dspring.profiles.active=internal-test' 'systemd pins internal-test profile'
Assert-Contains $text.InternalTestUnit '-Dspring.main.lazy-initialization=false' 'systemd pins eager internal-test safety gate'
Assert-Contains $text.InternalTestUnit 'ExecStartPre=+/bin/bash --noprofile --norc -p /usr/local/sbin/uten-imp-validate-internal-test-server-env' 'systemd invokes validator through fixed privileged shell mode'
Assert-Contains $text.InternalTestUnit 'UnsetEnvironment=LD_PRELOAD LD_LIBRARY_PATH LD_AUDIT LD_DEBUG GCONV_PATH BASH_ENV ENV SHELLOPTS BASHOPTS PS4 BASH_XTRACEFD' 'systemd strips pre-validator loader and shell controls'
Assert-Contains $text.InternalTestUnit 'JAVA_TOOL_OPTIONS JDK_JAVA_OPTIONS _JAVA_OPTIONS' 'systemd strips Java option injection'
Assert-Contains $text.InternalTestUnit 'SPRING_APPLICATION_JSON SPRING_CONFIG_LOCATION SPRING_CONFIG_ADDITIONAL_LOCATION SPRING_MAIN_LAZY_INITIALIZATION' 'systemd strips Spring control injection'
Assert-Contains $text.InternalTestUnit '-Dspring.flyway.enabled=false' 'systemd pins Flyway disabled'
Assert-Contains $text.InternalTestUnit 'ReadWritePaths=/data/uten-imp/attachments -/run/uten-imp-release' 'systemd fixed local attachment write boundary'
Assert-Contains $text.InternalTestUnit 'IPAddressDeny=any' 'internal-test outbound network deny'
Assert-Contains $text.InternalTestUnit 'IPAddressAllow=localhost' 'internal-test loopback database allowance'
Assert-Contains $text.InternalTestNginx 'server_name __INTERNAL_DOMAIN__;' 'internal-test internal DNS placeholder'
Assert-Contains $text.InternalTestNginx 'ssl_reject_handshake on;' 'internal-test unknown SNI refusal'
Assert-Contains $text.InternalTestNginx 'allow __EXACT_OFFICE_CIDR__;' 'internal-test exact office CIDR'
Assert-Contains $text.InternalTestNginx 'location ~ ^/api/website-inquiries(?:;[^/]*)?/ingest(?:[;/]|$) {' 'external website ingest excluded from ERP host'
Assert-Contains $text.InternalTestNginx 'location ~ ^/api/attachments(?:;[^/]*)?/(?:presign|confirm)(?:[;/]|$) {' 'attachment presign and confirm intake excluded'
Assert-Contains $text.InternalTestNginx 'location ~ ^/api/attachments(?:;[^/]*)?/raw(?:[;/]|$) {' 'attachment raw upload method gate'
Assert-Contains $text.InternalTestNginx 'limit_except GET HEAD {' 'internal-test attachment mutation refusal'
Assert-Contains $text.InternalTestNginx 'Attachment uploads are a three-step protocol: presign, raw PUT, confirm.' 'attachment upload protocol gate'
$internalInquiryLocations = [regex]::Matches($text.InternalTestNginx, '(?m)^\s*location\s+[^\{]*?/api/website-inquiries[^\{]*\{')
if ($internalInquiryLocations.Count -ne 1) {
    throw 'Forbidden deployment contract: website ingest must have exactly one Nginx location'
}
$internalAttachmentLocations = [regex]::Matches($text.InternalTestNginx, '(?m)^\s*location\s+[^\{]*?/api/attachments[^\{]*\{')
if ($internalAttachmentLocations.Count -ne 2) {
    throw 'Forbidden deployment contract: attachment intake must have exactly two reviewed Nginx locations'
}
if (([regex]::Matches($text.WebsiteInquiryController, '@(?:Get|Post|Put|Patch|Delete)Mapping')).Count -ne 6) {
    throw 'Forbidden deployment contract: website inquiry Controller route inventory changed without gateway review'
}
# 9 -> 11（2026-09-11）：GET /{id}/preview 与 PUT /{id}/category。已按本闸门的用意
# 复核网关策略——两条都落在通用 location /api/（不限方法、同一限流区），
# 不需要像 presign/confirm（内网部署一律 404）或 raw（只放行 GET/HEAD）那样单开 location；
# 因此上面「恰好两个已评审的 attachment location」的计数保持 2 不变。
if (([regex]::Matches($text.AttachmentController, '@(?:Get|Post|Put|Patch|Delete)Mapping')).Count -ne 11) {
    throw 'Forbidden deployment contract: attachment Controller route inventory changed without gateway review'
}
Assert-Contains $text.InternalTestGuide '<!-- INTERNAL-TEST-SINGLE-NVME-NOT-PRODUCTION -->' 'internal-test production boundary'
Assert-Contains $text.InternalTestOnboardingGuide 'dataClassification=discardable-test-only' 'internal-test onboarding discardable-data boundary'
Assert-Contains $text.InternalTestOnboardingGuide 'productionAuthority=false' 'internal-test onboarding non-production authority'
Assert-Contains $text.InternalTestOnboardingGuide 'COMMITTED_STORAGE_ONLY_LIVE_VERIFIED' 'internal-test onboarding storage late-finalization prerequisite'
Assert-Contains $text.InternalTestOnboardingGuide 'mutation-authorized.committed.json' 'internal-test host preparation terminal authority'
Assert-Contains $text.InternalTestOnboardingGuide 'active-pointer.committed.json' 'internal-test database terminal pointer'
Assert-Contains $text.InternalTestOnboardingGuide '--first-release' 'internal-test explicit first activation'
Assert-Contains $text.InternalTestOnboardingGuide '--enable-on-boot' 'internal-test explicit boot enablement'
Assert-Contains $text.InternalTestOnboardingGuide '--approve-database-change' 'internal-test onboarding rejects manual database boolean'
Assert-Contains $text.InternalTestOnboardingGuide '<!-- INTERNAL-TEST-NEW-MIGRATION-HARD-NO-GO -->' 'internal-test new migration hard stop'
Assert-NotContains $text.InternalTestOnboardingGuide '192.168.' 'internal-test onboarding topology redaction'

# Even the legacy HTTP template must remain topology-free because source
# snapshots can include it. Live values belong only in ignored private handoff.
Assert-Contains $text.LegacyLanNginx 'server_name __INTERNAL_DOMAIN__ _;' 'legacy LAN DNS placeholder'
Assert-Contains $text.LegacyLanNginx 'allow __EXACT_OFFICE_CIDR__;' 'legacy LAN CIDR placeholder'
if ([regex]::IsMatch($text.LegacyLanNginx, '(?m)^\s*server_name\s+(?:\d{1,3}\.){3}\d{1,3}')) {
    throw 'Forbidden deployment contract: legacy LAN template contains a raw server address'
}

# On-prem Nginx: exact TLS boundary, loopback backend/probe, bounded imports.
$nginx = $text.Nginx
Assert-Contains $nginx 'server 127.0.0.1:8080;' 'loopback backend'
Assert-Contains $nginx 'listen 127.0.0.1:8081;' 'loopback Web probe'
Assert-Contains $nginx 'location = /version.json {' 'signed live-version endpoint'
Assert-Contains $nginx 'listen 80 default_server;' 'unknown Host HTTP reject vhost'
Assert-Contains $nginx 'listen 443 ssl default_server;' 'unknown SNI TLS reject vhost'
Assert-Contains $nginx 'ssl_reject_handshake on;' 'unknown SNI handshake rejection'
Assert-Regex $nginx '(?m)^\s*ssl_protocols TLSv1\.2 TLSv1\.3;\s*$' 'explicit modern TLS protocol policy'
Assert-Contains $nginx 'ssl_session_tickets off;' 'stateless TLS ticket rejection'
Assert-Contains $nginx "ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305';" 'reviewed TLS 1.2 ciphers'
Assert-Contains $nginx 'if ($host != "__LOCAL_DOMAIN__") { return 444; }' 'fixed configured Host enforcement'
Assert-Contains $nginx 'return 308 https://__LOCAL_DOMAIN__$request_uri;' 'non-reflective HTTPS redirect'
Assert-Contains $nginx 'allow __OFFICE_CIDR__;' 'exact office CIDR placeholder'
Assert-Contains $nginx 'allow __VPN_CIDR__;' 'exact VPN CIDR placeholder'
Assert-Contains $nginx 'location ~ ^/api/master/goods/import/(?:detect|commit)$ {' 'exact goods-import boundary'
Assert-Contains $nginx 'client_max_body_size 10m;' 'goods-import transport cap'
Assert-Contains $nginx 'limit_conn uten_goods_import_conn 2;' 'goods-import per-IP concurrency cap'
Assert-Contains $nginx 'root /opt/uten-imp/current/web;' 'immutable Web symlink root'
Assert-NotContains $nginx 'allow 10.0.0.0/8;' 'broad RFC1918 allow rule'
Assert-NotContains $nginx 'allow 192.168.0.0/16;' 'broad office allow rule'
$exactHealth = $nginx.IndexOf('location = /actuator/health {')
$probeHealth = $nginx.IndexOf('location ~ ^/actuator/health/(?:liveness|readiness)$ {')
$actuatorDeny = $nginx.IndexOf('location /actuator/ {')
$spaFallback = $nginx.LastIndexOf('location / {')
if ($exactHealth -lt 0 -or $probeHealth -lt 0 -or $actuatorDeny -lt 0 -or $spaFallback -lt 0 -or
    $actuatorDeny -lt $exactHealth -or $actuatorDeny -lt $probeHealth -or $actuatorDeny -gt $spaFallback) {
    throw 'Actuator allow/deny and SPA fallback ordering is unsafe'
}
if (([regex]::Matches($nginx, [regex]::Escape('{'))).Count -ne
    ([regex]::Matches($nginx, [regex]::Escape('}'))).Count) {
    throw 'Nginx template braces are unbalanced'
}

# App and watchdog services: data/DB hard gates, bounded memory, root-owned probes.
$appUnit = $text.AppUnit
Assert-Contains $appUnit 'RequiresMountsFor=/data' 'data mount systemd hard dependency'
Assert-Contains $appUnit 'Requires=postgresql@16-main.service' 'PostgreSQL service dependency'
Assert-Contains $appUnit 'BindsTo=data.mount postgresql@16-main.service' 'data and database disappearance binding'
Assert-Contains $appUnit 'RestartSteps=5' 'systemd bounded restart backoff steps'
Assert-Contains $appUnit 'RestartMaxDelaySec=60s' 'systemd restart backoff ceiling'
Assert-Contains $appUnit 'StartLimitIntervalSec=10min' 'restart-storm observation window'
Assert-Contains $appUnit 'StartLimitBurst=8' 'restart-storm bounded burst'
Assert-Contains $appUnit 'ExecStartPre=/usr/bin/mountpoint --quiet /data' 'runtime mountpoint guard'
Assert-Contains $appUnit 'ExecStartPre=+/usr/bin/test ! -e /var/lib/uten-imp-release/activation-failed.json' 'persistent failed-activation boot gate'
Assert-Contains $appUnit 'ExecStartPre=+/usr/bin/test ! -e /var/lib/uten-imp-release/boot-enablement-in-progress.json' 'partial boot-enablement gate'
Assert-Contains $appUnit 'ExecStartPre=+/usr/bin/python3 -I /usr/local/libexec/uten-imp-release/runtime_boot_verifier.py' 'signed release/database/storage runtime boot gate'
Assert-Contains $appUnit 'TimeoutStartSec=120s' 'bounded runtime-verification startup deadline'
Assert-Contains $appUnit 'ReadWritePaths=-/run/uten-imp-release' 'one-use activation authorization consume boundary'
Assert-Contains $appUnit '-Dserver.address=127.0.0.1' 'JVM loopback bind'
Assert-Contains $appUnit '-Dspring.flyway.enabled=false' 'backend Flyway hard disable'
Assert-Contains $appUnit '-Xmx4g' 'JVM heap ceiling'
Assert-Contains $appUnit 'MemoryHigh=5G' 'cgroup memory throttle'
Assert-Contains $appUnit 'MemoryMax=6G' 'cgroup memory ceiling'
Assert-NotContains $appUnit 'ReadWritePaths=/data/uten-imp/attachments' 'OSS production JVM data-RAID write grant'
$migratorUnit = $text.MigratorUnit
Assert-Contains $migratorUnit 'Type=oneshot' 'migration-only oneshot unit'
Assert-Contains $migratorUnit 'User=uten-imp-migrate' 'dedicated migration identity'
Assert-Contains $migratorUnit 'Group=uten-imp-migrate' 'dedicated migration group'
Assert-Contains $migratorUnit 'EnvironmentFile=/etc/uten-imp-migrator/migrator.env' 'isolated migration credential file'
Assert-Contains $migratorUnit 'ExecStartPre=+/usr/local/sbin/uten-imp-validate-migrator-env /etc/uten-imp-migrator/migrator.env' 'root migration-env validation'
Assert-Contains $migratorUnit '/opt/uten-imp/current/server/uten-imp-migrator.jar' 'dedicated migration artifact'
Assert-Contains $migratorUnit 'IPAddressDeny=any' 'migration network deny baseline'
Assert-Contains $migratorUnit 'IPAddressAllow=localhost' 'migration loopback-only database access'
Assert-Contains $migratorUnit 'Restart=no' 'migration is never an auto-restarting daemon'
Assert-NotContains $migratorUnit 'WantedBy=' 'migration job never starts automatically at boot'
Assert-Contains $migratorUnit 'After=network-online.target data.mount postgresql@16-main.service' 'migrator ordering-only database and data dependencies'
Assert-Contains $migratorUnit 'Wants=network-online.target' 'migrator only pulls the network-online target'
Assert-NotContains $migratorUnit 'Requires=postgresql@16-main.service' 'migrator must not pull PostgreSQL online'
Assert-NotContains $migratorUnit 'RequiresMountsFor=/data' 'migrator must not pull the data mount online'
Assert-Contains $text.WatchdogUnit '/usr/local/libexec/uten-imp/uten-imp-watchdog' 'root-owned backend watchdog executable'
Assert-Contains $text.EntryWatchdogUnit '/usr/local/libexec/uten-imp/uten-imp-entry-watchdog' 'root-owned entry watchdog executable'
Assert-Contains $text.EntryWatchdogUnit 'After=network-online.target nginx.service' 'entry probe orders after Nginx without starting it'
Assert-Contains $text.EntryWatchdogUnit 'Wants=network-online.target' 'entry probe requests only network-online'
Assert-NotContains $text.EntryWatchdogUnit 'Wants=network-online.target nginx.service' 'entry probe never pulls intentionally disabled or stopped Nginx'
Assert-Contains $text.WatchdogUnit 'ExecStartPre=/usr/bin/test ! -e /var/lib/uten-imp-release/boot-enablement-in-progress.json' 'backend watchdog partial boot gate'
Assert-Contains $text.EntryWatchdogUnit 'ExecStartPre=/usr/bin/test ! -e /var/lib/uten-imp-release/boot-enablement-in-progress.json' 'entry watchdog partial boot gate'
foreach ($marker in @('activation-in-progress.json', 'recovery-in-progress.json')) {
    Assert-Contains $text.WatchdogUnit "ExecStartPre=/usr/bin/test ! -e /var/lib/uten-imp-release/$marker" "backend watchdog $marker transaction gate"
    Assert-Contains $text.EntryWatchdogUnit "ExecStartPre=/usr/bin/test ! -e /var/lib/uten-imp-release/$marker" "entry watchdog $marker transaction gate"
}
Assert-NotContains $text.WatchdogUnit '/opt/uten-imp/current/deploy/' 'release-controlled root watchdog'
Assert-NotContains $text.EntryWatchdogUnit '/opt/uten-imp/current/deploy/' 'release-controlled root entry watchdog'
Assert-NotContains $text.WatchdogUnit 'EnvironmentFile=' 'unvalidated root watchdog override'
Assert-NotContains $text.EntryWatchdogUnit 'EnvironmentFile=' 'unvalidated root entry-watchdog override'
Assert-Contains $text.WatchdogTimer 'OnUnitActiveSec=15s' 'backend watchdog cadence'
Assert-Contains $text.EntryWatchdogTimer 'OnUnitActiveSec=15s' 'entry watchdog cadence'
Assert-Contains $text.WatchdogScript 'flock -n 9' 'single-flight backend watchdog'
Assert-Contains $text.WatchdogScript 'exec 8<"${OPERATION_LOCK}"' 'read-only shared release-operation lock'
Assert-Contains $text.WatchdogScript 'activation-in-progress.json' 'activation race gate before restart'
Assert-Contains $text.WatchdogScript 'recovery-in-progress.json' 'recovery race gate before restart'
Assert-Contains $text.WatchdogScript 'systemctl is-enabled --quiet "${SERVICE}"' 'intentional application disable gate'
Assert-Contains $text.WatchdogScript 'systemctl reset-failed "${SERVICE}"' 'gated start-limit recovery'
Assert-Contains $text.WatchdogScript 'required_delay=1800' 'bounded long-term recovery backoff'
Assert-Contains $text.WatchdogScript 'if ! write_recovery_state "${attempts}" "${now}"; then' 'backend recovery backoff state write is explicit fail-closed'
Assert-Contains $text.EntryWatchdogScript 'entry_is_healthy' 'entry health requires a compound static and readiness proof'
Assert-Contains $text.EntryWatchdogScript 'close_ingress_for_readiness_failure' 'entry watchdog closes ingress after sustained backend readiness failure'
Assert-Contains $text.EntryWatchdogScript 'systemctl stop "${NGINX_SERVICE}"' 'sustained readiness failure stops Nginx without restarting the JVM'
Assert-Contains $text.EntryWatchdogScript '--property=ActiveState --value' 'entry watchdog proves Nginx inactive after fail-closed stop'
Assert-Contains $text.WatchdogUnit 'PrivateDevices=true' 'network watchdog retains private device namespace'
Assert-Contains $text.WatchdogUnit '-/run/uten-imp-storage-observer' 'watchdog can consume only volatile observer evidence'
Assert-Contains $text.WatchdogScript 'prepare_data_mount_observation' 'late data mount publishes a fixed short-lived observer request'
Assert-Contains $text.WatchdogScript 'systemctl start "${STORAGE_OBSERVER_UNIT}"' 'late data mount uses the isolated host observer service'
Assert-Contains $text.WatchdogScript 'verify_and_consume_data_mount_observation' 'late data mount requires one-use receipt consumption'
Assert-Contains $text.StorageObserverUnit 'PrivateDevices=false' 'observer alone receives the host device namespace'
Assert-Contains $text.StorageObserverUnit 'DevicePolicy=closed' 'observer denies unlisted devices'
Assert-NotContains $text.StorageObserverUnit 'DeviceAllow=' 'v3 observer never pins a drifting dm-N device'
if (([regex]::Matches($text.StorageObserverUnit, '(?m)^DeviceAllow=')).Count -ne 0) {
    throw 'Storage observer v3 template must not contain DeviceAllow'
}
Assert-Contains $text.StorageObserverUnit '/sys/dev/block' 'v3 observer receives read-only stable sysfs identity'
Assert-Contains $text.StorageObserverUnit 'PrivateNetwork=true' 'storage observer has no network namespace'
Assert-Contains $text.StorageObserverUnit 'RestrictAddressFamilies=AF_UNIX' 'storage observer address-family boundary'
Assert-NotContains $text.StorageObserverUnit '[Install]' 'storage observer is on-demand only'
Assert-Contains $text.StorageMountObserver 'REQUEST_TTL_NS = 30_000_000_000' 'storage observation short TTL'
Assert-Contains $text.StorageMountObserver '"nonce": secrets.token_hex(32)' 'storage observation nonce binding'
Assert-Contains $text.StorageMountObserver '"bootId": _boot_id()' 'storage observation boot binding'
Assert-Contains $text.StorageMountObserver '"helperSha256": _sha256(helper_raw)' 'storage observation helper digest binding'
Assert-Contains $text.StorageMountObserver '"deviceRdev": rdev' 'storage observation exact rdev evidence'
Assert-Contains $text.StorageMountObserver '"eligible-for-data-mount"' 'storage observation explicit eligibility result'
Assert-Contains $text.WatchdogScript 'if ! verify_mounted_storage; then' 'late data mount reruns the full fixed storage verifier before PostgreSQL'
Assert-Contains $text.EntryWatchdogScript 'exec 8<"${OPERATION_LOCK}"' 'entry watchdog read-only release lock'
Assert-Contains $text.EntryWatchdogScript 'if ! write_recovery_state "${attempts}" "${now}"; then' 'entry recovery backoff state write is explicit fail-closed'
Assert-NotContains $text.EntryWatchdogScript 'systemctl restart "${APPLICATION_SERVICE}"' 'readiness never restarts JVM'
Assert-Contains $text.EntryWatchdogScript '127.0.0.1:8081/index.html' 'entry watchdog exact loopback URL'
Assert-Contains $text.NginxOverride 'Restart=no' 'Nginx failed ExecStartPost cannot enter a restart loop'
Assert-NotContains $text.NginxOverride 'Restart=on-failure' 'Nginx must not restart after a failed ExecStartPost'
Assert-Contains $text.NginxOverride 'BindsTo=uten-imp.service' 'Nginx fail-closed application binding'
Assert-Contains $text.NginxOverride 'PartOf=uten-imp.service' 'Nginx follows application restart transaction'
Assert-Contains $text.NginxOverride 'ExecStartPre=/usr/local/libexec/uten-imp/uten-imp-wait-ready' 'Nginx backend readiness startup gate'
Assert-Contains $text.ReadinessGate 'DEADLINE_SECONDS=75' 'bounded backend readiness deadline'
Assert-Contains $text.ReadinessGate '/actuator/health/readiness' 'exact backend readiness probe'
Assert-Contains $text.Phase3 'the audited runtime and restart-backoff contract supports only Ubuntu 24.04' 'reviewed runtime operating-system gate'
Assert-Contains $text.Phase3 'systemd 255 or newer is required for reviewed RestartSteps/RestartMaxDelaySec semantics' 'systemd backoff-version gate'
Assert-Contains $text.Phase3 'readonly STORAGE_AUTHORITY=/etc/uten-imp/storage-authority.json' 'fixed storage-authority path'
Assert-Contains $text.Phase3 '--expected-data-source' 'legacy v2 rollback retains explicit RAID authority input'
Assert-Contains $text.Phase3 '--expected-data-uuid' 'storage authority requires an independently approved filesystem UUID'
Assert-Contains $text.Phase3 '--expected-data-fstype' 'storage authority requires an independently approved filesystem type'
Assert-Contains $text.Phase3 '--storage-approval-reference' 'storage authority creation is bound to a non-secret approval'
Assert-Contains $text.Phase3 '--confirm-storage-authority' 'storage authority creation uses an identity-bound typed confirmation'
Assert-Contains $text.Phase3 'existing-host storage commissioning requires inactive' 'existing host cannot commission storage while PostgreSQL is active'
Assert-Contains $text.Phase3 'existing-host storage commissioning requires disabled' 'existing host cannot commission storage while PostgreSQL remains boot-enabled'
Assert-Contains $text.Phase3 'publish_database_boot_marker' 'existing-host database boot restoration is durably resumable'
Assert-Contains $text.Phase3 'verify_database_boot_marker' 'database boot restoration revalidates durable evidence'
Assert-Contains $text.Phase3 'DATABASE_BOOT_AUTHORITY_VERIFIED' 'Phase 3 verifies independent database boot authority'
Assert-Contains $text.Phase3 'loaded migrator unit must not pull PostgreSQL or /data' 'Phase 3 validates loaded migrator no-pull contract'
Assert-Contains $text.Phase3 '"dataSource": "%s"' 'persistent data software RAID source is pinned'
Assert-Contains $text.Phase3 '"schemaVersion": 2' 'persistent storage authority schema includes the RAID source'
Assert-Contains $text.StorageBootVerifier 'version not in {2, 3}' 'storage verifier accepts only reviewed v2 rollback and v3 current generations'
Assert-Contains $text.StorageBootVerifier 'lvm-linear-nvme' 'current storage authority pins LVM-on-NVMe topology'
Assert-Contains $text.NvmeCommissioner 'TARGET_LV_BYTES = 350 * 1024**3' 'existing test host NVMe LV has the reviewed fixed size'
Assert-Contains $text.NvmeCommissioner 'validate_committed_late_receipt(' 'committed storage finalization is resumable after receipt publication'
Assert-Contains $text.NvmeCommissioner 'COMMITTED_AWAITING_LIVE_LATE_FINALIZATION' 'early recovery retains committed pointer until live late verification'
Assert-Contains $text.NvmeCommissionerTest 'test_durable_pointer_is_published_before_the_gate_is_closed' 'NVMe arming race regression'
Assert-Contains $text.NvmeCommissionerTest 'test_gate_is_reclosed_before_service_and_storage_mutation_boundaries' 'NVMe post-arm race regression'
Assert-Contains $text.NvmeCommissionerTest 'test_committed_late_reuses_receipt_left_before_power_loss' 'NVMe committed receipt power-loss regression'
Assert-Contains $text.NvmeCommissionerTest 'test_final_rollback_receipt_bypasses_exhausted_attempt_budget' 'NVMe rollback receipt power-loss regression'
Assert-Contains $text.NvmeCommissionerTest 'test_irreversible_disarm_failure_is_append_only_and_returns_nonzero' 'NVMe irreversible disarm failure evidence regression'
Assert-Contains $text.NvmeCommissionerTest 'test_unit_start_grant_is_consumed_before_health_and_reissued_per_unit' 'NVMe one-time unit grant regression'
Assert-Contains $text.NvmeCommissionerTest 'test_partial_gate_publication_failure_still_closes_marker' 'NVMe partial grant publication containment regression'
Assert-Contains $text.NvmeCommissionerTest 'test_os_update_restore_preserves_preexisting_enablement_exactly' 'NVMe OS update enablement regression'
Assert-Contains $text.NvmeEarlyResumeUnit 'recover --from-systemd-early' 'NVMe early boot recovery entry'
Assert-Contains $text.NvmeLateResumeUnit 'ExecStopPost=/usr/bin/python3 -I @VERSIONED_HELPER@ contain-late-failure' 'NVMe late SIGKILL containment'
Assert-Contains $text.NvmeLateResumeTimer 'OnActiveSec=30s' 'NVMe bounded late recovery scheduling'
Assert-Contains $text.NvmeGateAuthorizerUnit 'RemainAfterExit=yes' 'NVMe gate authorizer marker lifetime'
Assert-Contains $text.NvmeActiveTransactionGate 'Requires=uten-imp-nvme-gate-authorizer.service' 'every protected NVMe unit requires authorizer success'
Assert-Contains $text.NvmeActiveTransactionGate 'ConditionPathExists=/run/uten-imp-nvme-gate-authorizer/open/@UNIT_MARKER@' 'unit-specific NVMe gate marker'
Assert-NotContains $text.NvmeActiveTransactionGate 'ConditionPathExists=|' 'NVMe gate cannot merge into a trigger-condition OR group'
Assert-Contains $text.StorageBootVerifier 'lv_uuid,vg_uuid,lv_size,segtype,devices' 'v3 storage verifier proves the live linear LV report'
Assert-Contains $text.StorageBootVerifier 'pv_uuid,vg_uuid,pv_name' 'v3 storage verifier proves the live PV and VG identity'
Assert-Contains $text.Phase3 '"minimumFreeBytes": 2147483648' 'persistent data free-space floor'
Assert-Contains $text.Phase3 '"minimumFreeInodes": 100000' 'persistent data inode floor'
Assert-Contains $text.Phase3 '"requiredOptions": ["nodev", "noexec", "nosuid", "rw"]' 'persistent data mount-option authority'
Assert-Contains $text.Phase3 'new NVMe hosts require a precommissioned v3 authority' 'Phase 3 cannot silently mint a new v3 authority'
Assert-Contains $text.Phase3 '_validate_fstab_and_data_unit(observer_authority, fstab_raw)' 'Phase 3 validates exact fstab and generated data.mount before install writes'
Assert-Contains $text.Phase4 'installed runtime boot verifier differs from the reviewed Phase 4 source' 'root-installed boot verifier byte equality'
Assert-Contains $text.Phase4 '_validate_fstab_and_data_unit(authority, fstab_raw)' 'Phase 4 revalidates exact fstab and generated data.mount before updater writes'
Assert-Contains $text.Phase4 'RUNTIME_BOOT_VERIFIER_SHA256' 'updater-to-boot-verifier digest binding'
Assert-Contains $text.Phase3 'storage_boot_verifier.py" "$STORAGE_BOOT_VERIFIER"' 'PostgreSQL storage verifier root installation'
Assert-Contains $text.Phase3 'storage_mount_observer.py" "$STORAGE_MOUNT_OBSERVER"' 'storage observer helper root installation'
Assert-Contains $text.Phase3 'rendered storage observer unit differs from helper contract' 'Phase 3 exact-device unit renderer parity'
Assert-Contains $text.Phase3 'installed storage observer unit differs from the authority-generation contract' 'Phase 3 atomic observer unit read-back'
Assert-Contains $text.Phase3 'atomic_install_root_file' 'Phase 3 root helper and PostgreSQL gate replacement is atomic'
Assert-Contains $text.Phase3 'mv -fT -- "$temporary_file" "$target_file"' 'Phase 3 atomically publishes prepared root files'
Assert-Contains $text.Phase3 'postgresql-uten-imp-storage.conf.example' 'PostgreSQL storage drop-in installation'
Assert-Contains $text.PostgresStorageDropIn 'BindsTo=data.mount' 'PostgreSQL stops when commissioned data mount disappears'
Assert-Contains $text.PostgresStorageDropIn 'RequiresMountsFor=/data' 'PostgreSQL data mount hard dependency'
Assert-Contains $text.PostgresStorageDropIn 'ExecStartPre=+/usr/bin/python3 -I /usr/local/libexec/uten-imp-release/storage_boot_verifier.py' 'PostgreSQL pre-write storage identity gate'
Assert-Contains $text.RuntimeBootVerifier 'STORAGE_VERIFIER_SHA256' 'application boot reuses pinned storage verifier'
Assert-Contains $text.StorageBootVerifier 'POSTGRES_DATA_TEXT = "/data/postgresql/16/main"' 'PostgreSQL data directory is pinned before postmaster start'
Assert-Contains $text.StorageBootVerifier '"/usr/bin/pg_conftool"' 'PostgreSQL effective cluster configuration uses a fixed trusted query tool'
Assert-Contains $text.StorageBootVerifier 'PostgreSQL 16/main data_directory is outside commissioned /data' 'root-disk PostgreSQL cluster fails closed'
Assert-Contains $text.Phase3 'pg_conftool is required to prove the 16/main data_directory before PostgreSQL starts' 'Phase 3 installs the pre-write cluster path proof'
Assert-Contains $text.Phase4 'PostgreSQL loaded unit lacks the storage boot verifier' 'Phase 4 loaded PostgreSQL storage gate audit'
Assert-Contains $text.Phase4 'verify_database_maintenance_lock' 'Phase 4 validates the fixed shared database-maintenance lock before writes'
Assert-Contains $text.Phase4 'verify_database_boot_contract' 'Phase 4 validates independent database boot authority before writes'
Assert-Contains $text.Phase4 'loaded migrator unit must not pull PostgreSQL or /data' 'Phase 4 validates loaded migrator no-pull contract'
Assert-Contains $text.Phase4 'STORAGE_MOUNT_OBSERVER_SHA256' 'Phase 4 pins storage observer helper digest'
Assert-Contains $text.MigratorUnit 'ExecStartPre=+/usr/bin/python3 -I /usr/local/libexec/uten-imp-release/migration_authorization.py consume' 'migration unit consumes one root authorization before Flyway'
Assert-Contains $text.MigratorUnit 'ReadWritePaths=/run/uten-imp-migration-authorization' 'migration unit has only the fixed volatile grant write path'
Assert-Contains $text.MigrationAuthorization 'os.rename(AUTHORIZATION, archive)' 'migration grant is atomically consumed before validation'
Assert-Contains $text.MigrationAuthorization 'issuerProcStartTime' 'migration grant binds PID reuse-resistant updater identity'
Assert-Contains $text.MigrationAuthorization '_issuer_holds_operation_lock(pid)' 'migration helper requires the live updater lock owner'
Assert-Contains $text.MigrationAuthorization 'guard.verify_ssh_signature(' 'migration helper independently verifies signed current'
Assert-Contains $text.Phase3 'installed migration authorization helper changed during Phase 3' 'Phase 3 installs and byte-compares the fixed migration authorization helper'
Assert-Contains $text.Phase3 'MIGRATION_AUTHORIZATION_HELPER_SHA256=' 'Phase 3 pins the migration authorization helper before installation'
Assert-Contains $text.Phase4 'MIGRATION_AUTHORIZATION_HELPER_SHA256' 'Phase 4 pins migration authorization helper digest'
Assert-Contains $text.Phase4 'migration authorization helper differs from the fixed Phase 4 digest' 'Phase 4 verifies migration helper digest before replacing the stable helper'
Assert-Contains $text.ReleaseUpdater 'prepare_migration_authorization(' 'activation issues an explicit one-use migration grant'
Assert-Contains $text.ReleaseUpdater 'discard_unconsumed_migration_authorization(' 'activation archives any unconsumed migration grant'
Assert-Contains $text.Phase4 'installed storage observer unit differs from its authority generation' 'Phase 4 revalidates rendered observer unit'
Assert-Contains $text.ReleaseUpdater 'def assert_storage_observer_contract()' 'activation validates storage observer contract'
Assert-Contains $text.ReleaseUpdater 'expected_unit.count("DeviceAllow=") != expected_device_lines' 'activation enforces generation-specific DeviceAllow count'
Assert-Contains $text.ReleaseUpdater 'ENTRY_WATCHDOG_UNIT_SHA256' 'activation pins the entry watchdog unit bytes'
Assert-Contains $text.ReleaseUpdater 'ENTRY_WATCHDOG_SCRIPT_SHA256' 'activation pins the fail-closed entry watchdog script bytes'
Assert-Contains $text.ReleaseUpdater 'entry watchdog loaded Wants must contain only network-online.target' 'activation forbids a loaded dependency that pulls Nginx'
Assert-Contains $text.Phase4 'atomic_install_root_file' 'Phase 4 stable verifiers are atomically replaced'
Assert-Contains $text.NginxOverride 'ExecStartPre=/usr/bin/test ! -e /var/lib/uten-imp-release/activation-failed.json' 'Nginx failed-activation boot gate'
Assert-Contains $text.NginxOverride 'ExecStartPre=/usr/bin/test ! -e /var/lib/uten-imp-release/boot-enablement-in-progress.json' 'Nginx partial boot-enablement gate'
Assert-Contains $text.NginxOverride 'ExecStartPre=/usr/bin/test ! -e /var/lib/uten-imp-release/activation-in-progress.json' 'Nginx activation transaction gate'
Assert-Contains $text.NginxOverride 'ExecStartPre=/usr/bin/test ! -e /var/lib/uten-imp-release/recovery-in-progress.json' 'Nginx recovery transaction gate'

# Host identity/firewall/SSH gates.
Assert-Contains $text.Phase1 '--confirm-firewall' 'explicit firewall change confirmation'
Assert-Contains $text.Phase1 "CONSOLE_CONFIRMATION='TESTED PHYSICAL OR EMERGENCY CONSOLE FOR FIREWALL'" 'tested console required for firewall changes'
Assert-Contains $text.Phase1 'current SSH client is outside both approved CIDRs' 'SSH lockout prevention'
Assert-Contains $text.Phase1 'this script never resets a firewall' 'existing firewall preservation'
Assert-Contains $text.Phase1 'the current SSH session is not connected to the approved server port 22' 'current SSH port binding'
Assert-Contains $text.Phase1 'discover_ssh_ancestor_pids' 'direct SSH process-ancestry proof'
Assert-Contains $text.Phase1 'SSH_CONNECTION does not match an established TCP socket owned by an sshd ancestor' 'kernel SSH tuple binding'
Assert-Contains $text.Phase1 'SSH_CONNECTION exists without an sshd process ancestor' 'spoofed SSH context refusal'
Assert-Contains $text.Phase1 'if raw != str(network):' 'Phase1 exact canonical CIDR text refusal'
Assert-Contains $text.Phase1 'effective sshd configuration must expose exactly TCP/22 before UFW changes' 'configured SSH port binding'
Assert-Contains $text.Phase1 'ssh.socket is active; perform the separately reviewed console migration' 'Phase1 ssh.socket-mode refusal'
Assert-Contains $text.Phase1 'direct ssh.service must be enabled for boot' 'Phase1 direct ssh.service boot contract'
Assert-Contains $text.Phase1 'phase1-firewall/in-progress' 'persistent firewall transaction marker'
Assert-Contains $text.Phase1 'LOCK_PATH=/run/uten-imp-host-hardening.lock' 'shared host-hardening maintenance lock'
Assert-Contains $text.Phase1 'comm -23 "$current_rules_probe" "$EXPECTED_RULES"' 'interrupted firewall subset proof'
Assert-Contains $text.Phase1 'cmp -s -- "$current_rules_probe" "$EXPECTED_RULES"' 'exact staged firewall rule proof'
Assert-Contains $text.Phase1 'run_ufw_mutation default deny incoming' 'deny-by-default host firewall'
Assert-Contains $text.Phase1 '^IPV6=yes$' 'UFW IPv6 enablement gate'
Assert-Contains $text.Phase1 'UFW IPv4/IPv6 INPUT policies are not both DROP' 'UFW dual-stack default-deny runtime proof'
Assert-Contains $text.Phase1 'dpkg --verify ufw' 'UFW installed-package byte verification'
Assert-Contains $text.Phase1 'dpkg-query -W -f=''${Conffiles}\n'' ufw' 'UFW conffile recorded-MD5 verification'
Assert-Contains $text.Phase1 'for relative in before.rules before6.rules after.rules after6.rules before.init after.init' 'UFW hidden framework file coverage'
Assert-Contains $text.Phase1 'cmp -s -- "$installed_path" "$source_path"' 'UFW hidden framework package-baseline equality'
Assert-Contains $text.Phase1 'UFW_USER_RULES_SHA256=' 'durable UFW user-rule byte checkpoint'
Assert-Contains $text.Phase1 'verify_ufw_user_checkpoint' 'UFW user-rule checkpoint enforcement'
Assert-Contains $text.Phase1 'iptables-save | sed' 'stable full IPv4 runtime capture'
Assert-Contains $text.Phase1 'ip6tables-save | sed' 'stable full IPv6 runtime capture'
Assert-Contains $text.Phase1 'nft --stateless list ruleset' 'stable nft runtime capture'
Assert-Contains $text.Phase1 'built-in chain bypasses UFW' 'direct raw INPUT/FORWARD/OUTPUT bypass refusal'
Assert-Contains $text.Phase1 'foreign live filter chain' 'foreign raw filter-chain refusal'
Assert-Contains $text.Phase1 'write_runtime_checkpoint' 'durable exact runtime firewall checkpoint'
Assert-Contains $text.Phase1 'verify_disabled_firewall_service nftables.service' 'competing nftables boot-service refusal'
Assert-Contains $text.Phase1 'verify_disabled_firewall_service firewalld.service' 'competing firewalld boot-service refusal'
Assert-Contains $text.Phase1 'verify_disabled_firewall_service fail2ban.service' 'dynamic fail2ban firewall refusal'
Assert-NotContains $text.Phase1 'systemctl enable --now fail2ban' 'dynamic post-checkpoint fail2ban firewall mutation'
Assert-Contains $text.Phase1 'fsync_path /var/lib/uten-imp-commissioning' 'durable commissioning directory entry before firewall marker'
Assert-Regex $text.Phase1 '(?s)fsync_path "\$STATE_DIR".*?atomic_install "\$request_state" "\$IN_PROGRESS"' 'Phase1 state directory is durable before in-progress publication'
Assert-Regex $text.Phase1 '(?s)write_runtime_checkpoint.*?verify_runtime_checkpoint.*?atomic_install "\$request_state" "\$COMPLETE".*?atomic_remove "\$IN_PROGRESS"' 'Phase1 runtime evidence precedes durable completion and marker removal'
Assert-Contains $text.Phase1 'PHASE1_SSH_NO_GO' 'phase1 cannot claim SSH authentication completion'
Assert-NotContains $text.Phase1 '/etc/ssh/sshd_config.d/00-uten-imp.conf' 'non-transactional phase1 SSH mutation'

Assert-Contains $text.Phase1b '--stage-keys' 'two-step SSH key trust staging'
Assert-Contains $text.Phase1b '--commit-key-only' 'explicit key-only SSH commit'
Assert-Contains $text.Phase1b "PASSWORD_CONFIRMATION='ROTATED DISCLOSED SERVER PASSWORD OUT OF BAND'" 'disclosed password rotation gate'
Assert-Contains $text.Phase1b "CONSOLE_CONFIRMATION='TESTED PHYSICAL OR EMERGENCY CONSOLE'" 'tested recovery-console gate'
Assert-Contains $text.Phase1b "KEYS_CONFIRMATION='TESTED BOTH APPROVED SSH KEYS'" 'two approved keys tested gate'
Assert-Contains $text.Phase1b '--expected-keyset-sha256' 'out-of-band exact keyset digest proof'
Assert-Contains $text.Phase1b '--expected-key-fingerprint' 'two out-of-band key fingerprint proof'
Assert-Contains $text.Phase1b 'approved key file must contain exactly two plain Ed25519/FIDO public-key lines and nothing else' 'exact two-key allowlist'
Assert-Contains $text.Phase1b 'AUTHORIZED_KEYS_DIR=/etc/ssh/authorized_keys' 'root-owned administrator key namespace'
Assert-Contains $text.Phase1b 'AuthorizedKeysFile $AUTHORIZED_KEYS_PATH' 'single managed AuthorizedKeysFile'
Assert-Contains $text.Phase1b 'atomic_install "$transaction_dir/new-keys" "$AUTHORIZED_KEYS_PATH" 0 0 0644' 'root-owned but target-UID-readable public key file'
Assert-Contains $text.Phase1b 'AuthorizedKeysCommand none' 'external authorized-keys command disabled'
Assert-Contains $text.Phase1b 'TrustedUserCAKeys none' 'unmanaged SSH user CA disabled'
Assert-Contains $text.Phase1b 'unreviewed Match directive is forbidden' 'conditional SSH override refusal'
Assert-Contains $text.Phase1b 'nested Include directive is forbidden' 'nested SSH include refusal'
Assert-Contains $text.Phase1b 'laddr=$local_address,lport=$local_port' 'real and approved-network sshd contexts'
Assert-Contains $text.Phase1b 'the current SSH connection is not using the approved server port 22' 'phase1b current SSH port binding'
Assert-Contains $text.Phase1b 'discover_ssh_ancestor_pids' 'phase1b direct SSH process-ancestry proof'
Assert-Contains $text.Phase1b 'SSH_CONNECTION does not match an established TCP socket owned by an sshd ancestor' 'phase1b kernel SSH tuple binding'
Assert-Contains $text.Phase1b 'if raw != str(network):' 'Phase1b exact canonical CIDR text refusal'
Assert-Contains $text.Phase1b 'administrator numeric UID $uid is aliased in NSS' 'administrator UID alias refusal'
Assert-Contains $text.Phase1b "stat -c '%u:%g:%a:%h'" 'numeric managed-file ownership verification'
Assert-Contains $text.Phase1b 'administrator primary GID $gid must have exactly one local group name' 'administrator primary GID identity gate'
Assert-Contains $text.Phase1b 'sudo numeric GID $sudo_gid has a group-name alias' 'sudo GID alias refusal'
Assert-Contains $text.Phase1b 'flock -n 9' 'single-flight SSH hardening transaction'
Assert-Contains $text.Phase1b 'LOCK_PATH=/run/uten-imp-host-hardening.lock' 'shared host-hardening maintenance lock'
Assert-Contains $text.Phase1b 'ssh-key-only/in-progress' 'persistent SSH transaction marker'
Assert-Contains $text.Phase1b 'backup_transaction_file config "$CONFIG_PATH"' 'persistent SSH configuration preimage'
Assert-Contains $text.Phase1b 'backup_transaction_file keys "$AUTHORIZED_KEYS_PATH"' 'persistent authorized-key preimage'
Assert-Contains $text.Phase1b 'backup_transaction_file complete "$COMPLETE"' 'persistent SSH state preimage'
Assert-Contains $text.Phase1b 'mv -fT -- "$temporary" "$destination"' 'same-directory atomic SSH file promotion'
Assert-Contains $text.Phase1b 'fsync_path "$destination_dir" || return 1' 'durable SSH directory metadata with explicit failure propagation'
Assert-Contains $text.Phase1b 'destination_dir="$(dirname -- "$destination")" || return 1' 'atomic helper does not depend on errexit'
Assert-Contains $text.Phase1b 'rm -f -- "$destination" || return 1' 'atomic removal failure propagation'
Assert-Contains $text.Phase1b 'fsync_path "$TRANSACTION_ROOT"' 'durable transaction directory publication'
Assert-Contains $text.Phase1b 'fsync_path /etc/ssh' 'durable authorized_keys directory publication'
Assert-Contains $text.Phase1b '[[ -e "$AUTHORIZED_KEYS_DIR" || -L "$AUTHORIZED_KEYS_DIR" ]]' 'authorized_keys directory symlink preflight before install -d'
Assert-Contains $text.Phase1b '[[ -e "$TRANSACTION_ROOT" || -L "$TRANSACTION_ROOT" ]]' 'transaction-root symlink preflight before install -d'
Assert-Contains $text.Phase1b '$transaction_dir/$label-sha256' 'per-file rollback preimage digest'
Assert-Contains $text.Phase1b 'restored_metadata' 'rollback owner-mode-link verification'
Assert-Contains $text.Phase1b '[[ ! -e "$destination" && ! -L "$destination" ]] || return 1' 'rollback absence verification'
Assert-Contains $text.Phase1b 'systemctl reload ssh.service || return 1' 'rollback reloads restored SSH configuration'
Assert-Contains $text.Phase1b 'verify_live_ssh_runtime_contract || return 1' 'rollback live ssh.service reload proof'
Assert-Contains $text.Phase1b 'restored effective sshd configuration differs from preimage' 'rollback effective-config proof'
Assert-Contains $text.Phase1b 'atomic_remove "$IN_PROGRESS" || return 1' 'rollback marker removal only after proven restoration'
Assert-Contains $text.Phase1b 'atomic_remove "$IN_PROGRESS"' 'persistent SSH transaction commit point'
Assert-Contains $text.Phase1b 'PHASE1_FIREWALL_COMPLETE=' 'Phase1 firewall COMPLETE dependency'
Assert-Contains $text.Phase1b 'PHASE1_FIREWALL_EXPECTED_RULES=' 'Phase1 exact firewall rule dependency'
Assert-Contains $text.Phase1b 'verify_phase1_firewall_contract' 'live Phase1 firewall gate before SSH mutation'
Assert-Contains $text.Phase1b 'live IPv4/IPv6/nft firewall runtime differs from Phase1 durable evidence' 'Phase1 kernel-firewall drift refusal'
Assert-Contains $text.Phase1b 'FragmentPath --value ssh.service' 'ssh.service exact fragment binding'
Assert-Contains $text.Phase1b 'DropInPaths --value ssh.service' 'ssh.service drop-in refusal'
Assert-Contains $text.Phase1b 'dpkg --verify openssh-server' 'OpenSSH package byte verification'
Assert-Contains $text.Phase1b 'EnvironmentFiles --value ssh.service' 'ssh.service exact EnvironmentFile binding'
Assert-Contains $text.Phase1b 'ExecStart=/usr/sbin/sshd -D $SSHD_OPTS' 'audited ssh.service ExecStart contract'
Assert-Contains $text.Phase1b 'ssh.socket is active; migrate to audited ssh.service mode first' 'ssh.socket activation refusal'
Assert-Contains $text.Phase1b '(proc / "cmdline").read_bytes()' 'live ssh.service argv binding'
Assert-Contains $text.Phase1b '(proc / "environ").read_bytes()' 'live ssh.service environment binding'
Assert-Contains $text.Phase1b '0::{expected_cgroup}' 'live ssh.service cgroup binding'
Assert-Contains $text.Phase1b 'foreign sshd listener' 'additional sshd listener refusal'
Assert-Contains $text.Phase1b 'pids != {expected_pid}' 'TCP/22 listener exact MainPID binding'
Assert-Regex $text.Phase1b '(?s)install -d -o 0 -g 0 -m 0755 "\$CONFIG_DIR".*?fsync_path /etc/ssh.*?install -d -o 0 -g 0 -m 0755 "\$AUTHORIZED_KEYS_DIR".*?fsync_path /etc/ssh.*?atomic_install "\$transaction_dir/new-keys"' 'SSH trust directories are durable before key publication'
Assert-Regex $text.Phase1b '(?s)install -d -o 0 -g 0 -m 0700 "\$transaction_dir".*?fsync_path "\$transaction_dir".*?fsync_path "\$TRANSACTION_ROOT".*?atomic_install "\$transaction_dir/in-progress-candidate" "\$IN_PROGRESS"' 'transaction directory is durable before in-progress publication'
Assert-Regex $text.Phase1b '(?s)restore_transaction_file "\$transaction_dir" config.*?/usr/sbin/sshd -t \|\| return 1.*?restored effective sshd configuration differs from preimage.*?systemctl reload ssh\.service \|\| return 1.*?verify_live_ssh_runtime_contract \|\| return 1.*?restore_transaction_file "\$transaction_dir" keys.*?restore_transaction_file "\$transaction_dir" complete.*?atomic_remove "\$IN_PROGRESS" \|\| return 1' 'rollback activates the safe preimage policy before restoring keys and clearing its gate'
$rollbackMatch = [regex]::Match($text.Phase1b, '(?ms)^rollback_transaction\(\) \{(?<body>.*?)^\}')
if (-not $rollbackMatch.Success) {
    throw 'Missing deployment contract: rollback transaction body'
}
$rollbackBody = $rollbackMatch.Groups['body'].Value
$rollbackSteps = @(
    'restore_transaction_file "$transaction_dir" config "$CONFIG_PATH" || return 1',
    'systemctl reload ssh.service || return 1',
    'restore_transaction_file "$transaction_dir" keys "$AUTHORIZED_KEYS_DIR/$admin_user" || return 1',
    'restore_transaction_file "$transaction_dir" complete "$COMPLETE" || return 1',
    'atomic_remove "$IN_PROGRESS" || return 1'
)
$previousRollbackStep = -1
foreach ($rollbackStep in $rollbackSteps) {
    if (([regex]::Matches($rollbackBody, [regex]::Escape($rollbackStep))).Count -ne 1) {
        throw "Unsafe rollback contract: expected exactly one step: $rollbackStep"
    }
    $rollbackStepIndex = $rollbackBody.IndexOf($rollbackStep, [System.StringComparison]::Ordinal)
    if ($rollbackStepIndex -le $previousRollbackStep) {
        throw 'Unsafe rollback contract: configuration must be activated before keys are restored'
    }
    $previousRollbackStep = $rollbackStepIndex
}
Assert-NotContains $text.Phase1b '$admin_home/.ssh/authorized_keys' 'user-controlled SSH key trust'
Assert-NotContains $text.Phase1b 'ADMIN_USER="${ADMIN_USER:-}"' 'legacy environment-only administrator identity'

# PostgreSQL/runtime/restore gates.
Assert-Contains $text.Phase2 'readonly SECRETS=/etc/uten-imp-postgres' 'independent PostgreSQL secret directory'
Assert-Contains $text.Phase2 '/dev/md([0-9]+)' 'database data RAID source gate'
Assert-Contains $text.Phase2 'mounted RAID {target} is busy' 'database RAID resync gate'
Assert-Contains $text.Phase2 'fresh commissioning requires at least 100 GiB and 80% free' 'database capacity reserve gate'
Assert-Contains $text.Phase2 'PHASE2_CONTAINMENT_INCOMPLETE' 'Phase 2 does not claim fail-closed when shutdown or evidence cannot be proven'
Assert-Contains $text.Phase2 'systemctl is-active --quiet "$containment_unit"' 'Phase 2 verifies failed-install units are inactive'
Assert-Contains $text.Phase2 'unit_state="$(systemctl is-enabled "$containment_unit"' 'Phase 2 verifies failed-install units are disabled'
Assert-Contains $text.Phase2 'start.conf must contain exactly auto and one newline' 'Phase 2 exact PostgreSQL auto-start configuration'
Assert-Contains $text.Phase2 'postgresql.service does not want the 16/main instance from the generator' 'Phase 2 Debian generator contract'
Assert-Contains $text.Phase2 'database boot unit is not persistently enabled' 'Phase 2 verifies meta and instance boot enablement'
Assert-Contains $text.Phase2 'systemctl disable --now uten-pgbackup.timer' 'Phase 2 leaves backup scheduling disabled for separate commissioning'
Assert-NotContains $text.Phase2 'systemctl enable uten-pgbackup.timer' 'Phase 2 backup timer auto-enable path'
Assert-NotContains $text.Phase2 'pg_dropcluster' 'destructive cluster recreation'
Assert-Contains $text.Phase3 'readonly POSTGRES_SECRETS=/etc/uten-imp-postgres' 'phase3 PostgreSQL secret path'
Assert-Contains $text.Phase3 'PROCESS_SECRET_ISOLATION_INSTALLED' 'Flyway process-secret isolation install result'
Assert-Contains $text.Phase3 'systemctl disable nginx.service uten-imp-migrate.service uten-imp.service' 'migration job remains disabled after install'
Assert-Contains $text.EnvValidator 'root:root:600 || "$env_metadata" == root:uten-imp:640' 'exact server.env owner/group/mode gate'
Assert-Contains $text.EnvValidator 'BOOTSTRAP_ADMIN_PASSWORD' 'bootstrap administrator secret gate'
Assert-Contains $text.EnvValidator 'UTEN_MIGRATOR_DB_PASSWORD' 'backend environment rejects migrator secrets'
Assert-Contains $text.Phase3 'UTEN_OSS_STAGING_BUCKET=REPLACE_WITH_UNVERSIONED_STAGING_BUCKET' 'unversioned attachment staging Bucket placeholder'
Assert-Contains $text.Phase3 'UTEN_OSS_FINAL_BUCKET=REPLACE_WITH_VERSIONED_FINAL_BUCKET' 'versioned attachment final Bucket placeholder'
Assert-Contains $text.Phase3 'UTEN_ATTACHMENT_UPLOADS_ENABLED=false' 'attachment intake remains disabled during commissioning'
Assert-Contains $text.EnvValidator 'UTEN_OSS_STAGING_BUCKET and UTEN_OSS_FINAL_BUCKET must be different' 'split attachment Bucket identity gate'
Assert-Contains $text.EnvValidator 'expect_exact UTEN_ATTACHMENT_UPLOADS_ENABLED false' 'attachment production NO-GO environment gate'
Assert-NotContains $text.Phase3 'UTEN_OSS_BUCKET=' 'legacy single attachment Bucket contract'
Assert-Contains $text.ServerEnvInstaller 'INSTALL VALIDATED UTEN SERVER ENV' 'explicit server environment install confirmation'
Assert-Contains $text.ServerEnvInstaller 'installed environment validator differs from the reviewed Phase 3 source' 'reviewed environment validator parity'
Assert-Contains $text.ServerEnvInstaller 'mv -T -- "$INSTALLING_ENV" "$LIVE_ENV"' 'same-directory atomic server environment promotion'
Assert-Contains $text.ServerEnvInstaller 'fsync_directory "$ENV_DIR"' 'durable server environment directory metadata'
Assert-Contains $text.ServerEnvInstaller 'replacement is forbidden' 'live environment no-replace policy'
Assert-Contains $text.ServerEnvInstaller '--expected-current-sha256' 'legacy live environment digest approval'
Assert-Contains $text.ServerEnvInstaller 'EVIDENCE_ROOT=/var/lib/uten-imp-runtime-evidence' 'root-only legacy environment evidence namespace'
Assert-Contains $text.ServerEnvInstaller 'atomic_write_control "$transaction_dir" "$complete"' 'durable legacy environment completion evidence'
Assert-NotContains $text.ServerEnvInstaller 'source "$PENDING_ENV"' 'pending secret shell execution'
Assert-Contains $text.Phase3 'legacy live server.env failed the new validator' 'legacy live environment fail-closed migration preparation'
Assert-Contains $text.MigratorEnvValidator 'primary group of only $SERVICE_USER' 'exclusive migrator credential group'
Assert-Contains $text.MigratorEnvValidator 'UTEN_MIGRATOR_DB_PASSWORD does not match' 'migrator secret equality gate'
Assert-Contains $text.RestoreDrill 'verified-flyway-checksums' 'single authenticated Flyway restore interface'
Assert-Contains $text.RestoreDrill '--expected-version' 'restore manifest expected-version binding'
Assert-Contains $text.RestoreDrill 'isolated_stop_proven' 'restore-instance stop proof'
Assert-Contains $text.RestoreDrill 'start_attempted' 'restore cleanup race guard'
Assert-Contains $text.RestoreDrill "expected_flyway_version=''" 'restore has no stale Flyway-head default'
Assert-Contains $text.RestoreDrill "expected_migration_count=''" 'restore has no stale migration-count default'
Assert-Contains $text.RestoreDrill "die '--expected-flyway-version is required'" 'restore requires an explicit Flyway head'
Assert-Contains $text.RestoreDrill "die '--expected-migration-count is required'" 'restore requires an explicit migration count'
Assert-Contains $text.RestoreDrill 'readonly RECOVERY_RECEIPT_DIR=/var/lib/uten-imp-release/database-receipts' 'fixed recovery receipt directory'
Assert-Contains $text.RestoreDrill 'os.O_EXCL | os.O_CLOEXEC | os.O_NOFOLLOW' 'exclusive no-follow recovery receipt creation'
Assert-Contains $text.RestoreDrill 'trusted_migration_set_sha256' 'signed Flyway digest recovery receipt binding'
Assert-Regex $text.RestoreDrill '(?s)if \[\[ "\$final_status" -eq 0 && "\$drill_succeeded" == true.*?write_recovery_receipt' 'recovery receipt only after complete restore cleanup'
Assert-NotContains $text.Phase2 '--set=admin_password=' 'database password in process argv'
Assert-NotContains $text.RoleHardener '--set=migrator_password=' 'migrator password in process argv'
Assert-Contains $text.RoleHardener "expected_flyway_version=''" 'hardener has no stale Flyway-head default'
Assert-Contains $text.RoleHardener 'live Flyway versioned-row count differs from the authenticated release manifest' 'manifest-derived hardener migration count'
Assert-NotContains $text.RoleHardener 'only fully enumerated V252, V253, V254, or V255 migration histories are accepted' 'obsolete hardener Flyway allowlist'
Assert-NotContains $text.RoleHardener 'V255 candidate must contain exactly 236 successful versioned Flyway rows' 'obsolete hardener migration count'
Assert-Contains $text.RoleHardener 'verified-flyway-checksums' 'authenticated hardener Flyway inventory'
Assert-Contains $text.RoleHardener 'live Flyway version/script/checksum rows differ from the authenticated release manifest' 'row-by-row hardener parity gate'
Assert-Contains $text.RoleHardener 'TRUSTED_RELEASE_GUARD=/usr/local/libexec/uten-imp-release/release_guard.py' 'fixed hardener guard path'
Assert-Contains $text.RoleHardener 'Flyway history contains an unenumerated successful row' 'hardener complete history coverage'
Assert-Contains $text.RoleHardener 'HARDENING_IN_PROGRESS="$HARDENING_STATE_DIR/in-progress"' 'persistent hardening maintenance gate'
Assert-Contains $text.RoleHardener "psql_admin 'ALTER ROLE uten NOLOGIN" 'committed runtime-login maintenance gate'
Assert-Contains $text.RoleHardener 'write_state_atomically "$HARDENING_COMPLETE"' 'durable role-hardening completion evidence'
Assert-NotContains $text.RoleHardener '--trusted-release-guard)' 'operator-selected hardener guard path'
Assert-Contains $text.RestoreDrill '--port 5432 is reserved for production' 'restore production-port exclusion'
Assert-Contains $text.RestoreDrill 'Flyway history contains an unenumerated successful row' 'restore complete history coverage'

$bootstrap = $text.VerifierBootstrap
Assert-Contains $bootstrap '--expected-guard-sha256' 'out-of-band release guard digest'
Assert-Contains $bootstrap '--expected-signing-fingerprint' 'out-of-band release key fingerprint'
Assert-Contains $bootstrap 'TARGET_GUARD=/usr/local/libexec/uten-imp-release/release_guard.py' 'fixed bootstrap guard target'
Assert-Contains $bootstrap 'TARGET_ALLOWED_SIGNERS=/etc/uten-imp-release-trust/release-allowed-signers' 'fixed bootstrap trust target'
Assert-Contains $bootstrap 'replacement is refused' 'bootstrap no-replace policy'
Assert-NotContains $bootstrap 'systemctl enable' 'bootstrap auto-start mutation'

$legacyRetirement = $text.LegacyUpdaterRetirement
Assert-Contains $legacyRetirement "export PATH=/usr/sbin:/usr/bin:/sbin:/bin" 'legacy retirement fixed PATH'
Assert-Contains $legacyRetirement 'unset PYTHONPATH PYTHONHOME PYTHONSTARTUP PYTHONUSERBASE' 'legacy retirement isolated Python environment'
Assert-Contains $legacyRetirement '--expected-legacy-credential-sha256' 'out-of-band legacy credential digest'
Assert-Contains $legacyRetirement 'LEGACY OSS CREDENTIAL REVOKED OR ROTATED OUT OF BAND' 'out-of-band credential revocation confirmation'
Assert-Contains $legacyRetirement 'secure_root_file "$SCRIPT_FILE"' 'root-owned retirement source-chain gate'
Assert-Contains $legacyRetirement 'assert_units_quiescent' 'inactive and disabled legacy unit gate'
Assert-Contains $legacyRetirement 'nginx.service' 'legacy retirement full ingress maintenance gate'
Assert-Contains $legacyRetirement 'uten-imp-migrate.service' 'legacy retirement migration maintenance gate'
Assert-Contains $legacyRetirement 'uten-imp-entry-watchdog.timer' 'legacy retirement entry watchdog maintenance gate'
Assert-Contains $legacyRetirement 'assert_no_legacy_processes' 'repeated legacy identity process gate'
Assert-Contains $legacyRetirement 'SHARED_OPERATION_LOCK=/var/lib/uten-imp-release/operation.lock' 'shared staging and activation coordination lock'
Assert-Contains $legacyRetirement 'flock -n 8' 'shared staging and activation exclusion'
Assert-Contains $legacyRetirement 'EVIDENCE_ROOT=/var/lib/uten-imp-legacy-evidence' 'fixed root-only legacy evidence namespace'
Assert-Contains $legacyRetirement 'STABLE_TRUST=/etc/uten-imp-release-trust' 'stable verifier trust exclusion'
Assert-Contains $legacyRetirement 'credential_content_not_logged=true' 'secret-content non-disclosure result'
Assert-Contains $legacyRetirement 'sync -f "$(dirname -- "$source")"' 'durable source-parent rename'
Assert-Contains $legacyRetirement 'in-progress.closed.state' 'preserved closed transaction marker'
Assert-NotContains $legacyRetirement 'source "$LEGACY_CREDENTIAL"' 'legacy credential shell execution'
Assert-NotContains $legacyRetirement 'rm -rf' 'legacy evidence recursive deletion'
Assert-Contains $text.Phase4 'validate_legacy_retirement_evidence "$legacy_retirement_evidence"' 'Phase 4 consumes completed legacy retirement evidence'
Assert-Contains $text.Phase4 'legacy updater live credential/config/state remain after the claimed retirement' 'Phase 4 rejects reused legacy updater state'
Assert-Contains $text.Phase4 'quarantined legacy credential bytes differ from completion evidence' 'Phase 4 credential evidence digest binding'

# Signed release/updater privilege boundary.
Assert-Contains $text.ReleaseReadme 'automatic staging' 'signed staging contract'
Assert-Contains $text.ReleaseReadme 'install-only' 'phase4 default-disabled staging contract'
Assert-Contains $text.ReleaseReadme 'quota isolation' 'staging capacity NO-GO'
Assert-NotContains $text.DeployReadme 'deploy/watchdog/uten-imp-watchdog.sh' 'watchdog inside release payload'
Assert-Contains $text.DeployReadme 'server/uten-imp-migrator.jar' 'migration-only JAR in the signed payload inventory'
Assert-Contains $text.DeployReadme 'web/version.json' 'signed browser release identity in the payload inventory'
Assert-Contains $text.DeployReadme '<!-- MANUAL-STAGING-ONLY -->' 'manual-only staging status'
Assert-Contains $text.DeployReadme '<!-- CURRENT-ERP-TEST-SERVER-SCOPE-20260812 -->' 'current internal ERP test-server scope'
Assert-Contains $text.CurrentTestServerStatus '<!-- CURRENT-ERP-TEST-SERVER-SCOPE-20260812 -->' 'authoritative current test-server status sentinel'
Assert-Contains $text.CurrentTestServerStatus '<!-- WEBSITE-NOT-ON-ERP-HOST -->' 'website excluded from current ERP host'
Assert-Contains $text.CurrentTestServerStatus '<!-- FUTURE-MAINTENANCE-WINDOW-0300-ASIA-SHANGHAI -->' 'future maintenance window'
Assert-Contains $text.CurrentTestServerStatus '<!-- OBSERVED-REPO1-FULL-0217 -->' 'observed repo1 schedule distinct from maintenance'
Assert-Contains $text.CurrentTestServerStatus '<!-- MAINTENANCE-SKIPS-ACTIVE-BACKUP -->' 'maintenance cannot interrupt backup'
Assert-Contains $text.CurrentTestServerStatus '<!-- HOST-MAINTENANCE-JOBS-MUTUALLY-EXCLUSIVE -->' 'host maintenance mutual exclusion'
Assert-Regex $text.OperatorGuide '<!-- CURRENT-ERP-TEST-SERVER-SCOPE-[0-9]{8} -->' 'operator current test-server scope'
Assert-Contains $text.ReleaseReadme 'no supported `--enable-staging` path' 'no automatic staging enable path'
Assert-Contains $text.ReleaseReadme '/etc/uten-imp-release-trust/release-allowed-signers: root:root 0640' 'stable trust file mode'
Assert-Contains $text.ReleaseReadme '<!-- ALIYUN-OIDC-PUBLISHER-POLICY-NO-GO -->' 'Aliyun publisher policy commissioning NO-GO'
Assert-Contains $text.OperatorGuide '<!-- AUTHORITATIVE-PRODUCTION-MIGRATION-NO-GO -->' 'authoritative production migration handoff NO-GO'
Assert-Contains $text.OperatorGuide '<!-- UPDATER-TIMER-MUST-REMAIN-DISABLED -->' 'post-activation staging timer proof'
Assert-Contains $text.ServerHandoff 'PostgreSQL `uten_owner`' 'PostgreSQL owner identity handoff'
Assert-Contains $text.ServerHandoff '/etc/uten-imp-migrator/' 'migrator secret namespace handoff'
Assert-Contains $text.ServerHandoff '<!-- WEBSITE-DATASTORE-MUST-MATCH-REAL-PROVIDER -->' 'honest website datastore handoff status'
Assert-Contains $text.ServerHandoff '<!-- CURRENT-ERP-TEST-SERVER-SCOPE-20260812 -->' 'handoff current test-server scope'
Assert-Contains $text.WebsiteGuide 'Current status (2026-08-12): production remains NO-GO' 'website production status'
Assert-Contains $text.WebsiteGuide '<!-- WEBSITE-DEPLOYMENT-DEFERRED-20260812 -->' 'website deployment deferred from ERP host'
Assert-Contains $text.CloudReadme '<!-- LEGACY-CLOUD-RUNBOOK-EXECUTION-FORBIDDEN -->' 'legacy cloud runbook execution stop'
Assert-Contains $text.CloudReadme '<!-- CLOUD-DEPLOYMENT-DEFERRED-20260812 -->' 'cloud deployment deferred for current phase'
Assert-Contains $text.UpdaterService 'User=uten-imp-updater' 'dedicated downloader identity'
Assert-Contains $text.UpdaterService 'EnvironmentFile=/etc/uten-imp-updater/oss-pull.env' 'isolated downloader credentials'
Assert-Contains $text.UpdaterService 'ExecStartPre=/usr/bin/python3 -I /opt/uten-imp/updater/validate_oss_pull_env.py' 'strict OSS env preflight'
Assert-Contains $text.UpdaterService 'ProtectSystem=strict' 'downloader filesystem sandbox'
Assert-Contains $text.UpdaterService 'ReadWritePaths=/var/lib/uten-imp-updater /run/uten-imp-updater /var/lib/uten-imp-release/operation.lock' 'fixed downloader write boundary'
Assert-NotContains $text.UpdaterService 'ReadWritePaths=/opt/' 'downloader release-tree write grant'
Assert-NotContains $text.UpdaterWrapper 'source ' 'shell-sourced OSS credentials'
Assert-Contains $text.ActivateWrapper 'exec "$PYTHON" -I' 'isolated root activation Python'
Assert-Contains $text.RecoverWrapper 'exec "$PYTHON" -I "$UPDATER_DIR/release_updater.py" recover "$@"' 'isolated root recovery Python'
Assert-NotContains $text.RecoverWrapper 'rm ' 'recovery wrapper marker deletion'
Assert-Contains $text.ReleaseUpdater 'def build_recovery_assessment()' 'read-only evidence recovery assessment'
Assert-Contains $text.ReleaseUpdater 'archive_root_evidence(' 'atomic recovery evidence archive'
Assert-Contains $text.ReleaseUpdater 'retry-activation is intentionally unavailable' 'unsafe retry recovery refusal'
Assert-Contains $text.ReleaseUpdater 'def restore_previous_recovery(' 'evidence-driven previous release recovery'
Assert-Contains $text.ReleaseUpdater '"restore-previous"' 'explicit previous release recovery action'
Assert-Contains $text.ReleaseUpdater '"abandon-candidate"' 'explicit preparation-only abandonment action'
Assert-Contains $text.ReleaseUpdater '"remain-contained"' 'explicit fail-closed containment action'
Assert-Contains $text.ReleaseUpdater 'recovery_commands.add_parser("interrupted-assess")' 'interrupted transaction assessment action'
Assert-Contains $text.ReleaseUpdater 'DATABASE_BOOT_UNITS = (POSTGRES_META_UNIT, POSTGRES_UNIT)' 'independent database boot-unit authority'
Assert-Regex $text.ReleaseUpdater 'with StateLock\(DEFAULT_LOCK_FILE\)\.allow_persistent_markers\(\s*activation_compatible_markers\s*\), DatabaseMaintenanceLock\(\):' 'activation fixed release then database-maintenance lock order'
Assert-Regex $text.ReleaseUpdater 'with StateLock\(DEFAULT_LOCK_FILE\)\.allow_persistent_markers\(\s*recovery_state_lock_compatible_markers\(\)\s*\), DatabaseMaintenanceLock\(\):' 'recovery fixed release then database-maintenance lock order'
Assert-Contains $text.ReleaseUpdater 'def assert_database_boot_contract()' 'activation verifies database boot authority'
Assert-Contains $text.ReleaseUpdater 'def verify_live_recovery_database(' 'independent live database recovery gate'
Assert-Contains $text.ReleaseUpdater 'RECOVERY_DETAIL_REFERENCE_RE.fullmatch' 'fixed detailed recovery receipt reference parser'
Assert-Contains $text.ReleaseUpdater 'canonical_live_flyway_identity' 'exact live Flyway row verifier'
Assert-Contains $text.DatabaseRecoveryVerifier 'FROM public.flyway_schema_history' 'fixed public Flyway history query'
Assert-Contains $text.DatabaseRecoveryVerifier 'default_transaction_read_only=on' 'read-only recovery database session'
Assert-NotContains $text.DatabaseRecoveryVerifier 'shell=True' 'database verifier shell prohibition'
Assert-Contains $text.OperatorGuide '<!-- ACTIVATION-FAILED-MARKER-MANUAL-REMOVAL-FORBIDDEN -->' 'activation failure marker manual removal prohibition'
Assert-Contains $text.OperatorGuide '/usr/local/libexec/uten-imp-release/database_recovery_verifier.py' 'operator live database verifier contract'
Assert-Contains $text.OperatorGuide '<!-- FINISH-ACTIVATION-LIVE-DATABASE-BINDING-REQUIRED -->' 'operator exact live Flyway binding'
Assert-Contains $text.OperatorGuide '`restore-previous`' 'operator previous release recovery contract'
Assert-Contains $text.OperatorGuide '`abandon-candidate`' 'operator candidate abandonment contract'
Assert-Contains $text.OperatorGuide '`remain-contained`' 'operator explicit containment contract'
Assert-Contains $text.OperatorGuide '`recover interrupted-assess`' 'operator interrupted transaction containment contract'
Assert-Contains $text.ReleaseUpdater 'automatic staging must run as the dedicated unprivileged updater user' 'non-root staging assertion'
Assert-Contains $text.ReleaseUpdater 'os.O_NOFOLLOW' 'root candidate no-follow snapshot'
Assert-Contains $text.ReleaseUpdater 'snapshot_candidate' 'root-owned evidence snapshot'
Assert-Contains $text.ReleaseUpdater '--approve-database-change' 'explicit database-change approval'
Assert-Contains $text.ReleaseUpdater 'def require_initial_database_onboarding_acceptance(' 'first/legacy exact-target onboarding hard gate'
Assert-Contains $text.ReleaseUpdater 'database onboarding remains hard NO-GO even though the live database' 'first/legacy source-level NO-GO after exact live verification'
Assert-Contains $text.ReleaseUpdater 'def require_online_database_transition_acceptance(' 'signed-current from-to database hard gate'
Assert-Contains $text.ReleaseUpdater 'online Flyway activation remains hard NO-GO' 'boolean approval cannot authorize online migration'
Assert-Contains $text.ReleaseUpdater 'database_migration_required = False' 'first exact-target onboarding skips migration'
Assert-NotContains $text.ReleaseUpdater '--database-onboarding-receipt' 'unreviewed manual onboarding receipt CLI'
Assert-Contains $text.OperatorGuide '<!-- FINISH-ACTIVATION-LIVE-DATABASE-BINDING-REQUIRED -->' 'operator live database activation evidence gate'
Assert-Contains $text.OperatorGuide 'terminal onboarding' 'reviewed onboarding evidence producer remains required'
Assert-Contains $text.ReleaseReadme 'Do not hand-edit `current`, `active.json`, onboarding, backup, or' 'manual onboarding receipt escape hatch prohibition'
Assert-NotContains $text.OperatorGuide '因此当前服务器的完整首版命令形状为：' 'unsafe first activation command removed'
Assert-Contains $text.ReleaseReadme 'explicit first-activation path' 'release contract requires reviewed first activation'
Assert-Contains $text.ReleaseReadme 'signed-current from-to acceptance' 'first receipt cannot authorize later migrations'
Assert-Contains $text.ReleaseReadme '  --first-release \' 'reviewed first activation flag is explicit'
Assert-Contains $text.ReleaseGuard 'verified-flyway-checksums' 'authenticated restore checksum CLI'
Assert-Contains $text.OssValidator 'FORBIDDEN_VALUE_CHARS' 'canonical OSS EnvironmentFile parser'

# Root-controlled retention, quota, quarantine and external alert boundary.
$retention = $text.RetentionManager
Assert-Contains $retention 'POLICY_PATH = Path("/etc/uten-imp-release-retention/policy.json")' 'fixed root retention policy'
Assert-Contains $retention 'LOCK_PATH = ROOT_STATE_DIR / "operation.lock"' 'fixed shared retention lock'
Assert-Contains $retention 'FS_IOC_FSGETXATTR' 'project inheritance ioctl gate'
Assert-Contains $retention 'libc.quotactl(' 'real project quota query'
Assert-Contains $retention 'src_dir_fd=source_parent_fd' 'fd-relative quarantine source'
Assert-Contains $retention 'dst_dir_fd=quarantine_fd' 'fd-relative quarantine destination'
Assert-Contains $retention 'os.O_NOFOLLOW' 'retention no-follow opens'
Assert-Contains $retention 'transaction/recovery marker forbids pruning' 'transaction marker prune stop'
Assert-Contains $retention 'retention quarantine residue requires evidence-driven recovery' 'power-loss quarantine blocker'
Assert-Contains $retention 'incomplete/failed recovery transaction forbids pruning' 'all recovery evidence references protected'
Assert-Contains $retention 'keepVerifiedCandidates' 'candidate minimum retained set'
Assert-Contains $retention 'fallbackPredecessor' 'signed rollback predecessor protection'
Assert-Contains $retention 'project quota could not be re-proven after retention pruning' 'post-prune quota proof'
Assert-Contains $retention 'actions-completed-awaiting-transaction-close' 'durable action evidence before marker close'
Assert-Contains $retention 'external retention alert receipt does not acknowledge this event' 'provider-bound alert receipt'
Assert-Contains $retention '"--event-file"' 'fixed external alert event interface'
Assert-Contains $retention '"--receipt-file"' 'fixed external alert receipt interface'
Assert-NotContains $retention 'shutil.rmtree' 'path-recursive retention deletion'
$retentionParser = $retention.Substring($retention.IndexOf('def parser()'), $retention.IndexOf('def main()') - $retention.IndexOf('def parser()'))
Assert-NotContains $retentionParser '--state-dir' 'retention path override'
Assert-NotContains $retentionParser '--release-dir' 'release path override'
Assert-Contains $text.RetentionWrapper 'exec "$PYTHON" -I -B "$UPDATER_DIR/retention_launcher.py" "$@"' 'isolated root retention trusted launcher'
Assert-NotContains $text.RetentionWrapper 'exec "$PYTHON" -I "$UPDATER_DIR/retention_manager.py" "$@"' 'retention manager direct path execution'
Assert-Contains $text.RetentionInstaller 'readonly LAUNCHER=/usr/local/sbin/uten-imp-release-retention-installer' 'fixed reviewed retention installer launcher'
Assert-Contains $text.RetentionInstaller 'exec /usr/bin/python3 -I -B "$LAUNCHER" -- "$@"' 'isolated reviewed retention installer delegation'
Assert-NotContains $text.RetentionInstaller 'systemctl ' 'deprecated retention installer shim mutation'
Assert-NotContains $text.RetentionInstaller 'flock ' 'deprecated retention installer shim lock impersonation'
Assert-Contains $text.RetentionUnit 'OnFailure=uten-imp-retention-alert@%n.service' 'retention external alert hook'
Assert-Contains $text.RetentionAlertUnit 'Restart=on-failure' 'retention pending alert retry'
Assert-Contains $text.RetentionAlertUnit 'RestrictAddressFamilies=AF_UNIX AF_INET AF_INET6' 'external alert network families'
Assert-Contains $text.RetentionTimer 'Persistent=true' 'retention power-loss catch-up only after commissioning'
Assert-Contains $text.OperatorGuide '<!-- RELEASE-RETENTION-TIMERS-MUST-REMAIN-DISABLED -->' 'retention production NO-GO marker'
$retentionPolicy = $text.RetentionPolicy | ConvertFrom-Json
if ($retentionPolicy.keepVerifiedCandidates -lt 3 -or $retentionPolicy.keepVerifiedInstalled -lt 3) {
    throw 'Retention example must keep at least three verified candidates and installed releases'
}
if ($retentionPolicy.stagingProjectId -eq $retentionPolicy.installedProjectId) {
    throw 'Retention example must use distinct staging and installed project IDs'
}

# Phase4 must remain install-only until storage retention/quota/alerts exist.
$phase4 = $text.Phase4
Assert-Contains $phase4 '--expected-signing-fingerprint' 'out-of-band signing fingerprint'
Assert-Contains $phase4 '--no-index --no-deps --no-compile' 'offline dependency-only wheel install'
Assert-Contains $phase4 '--only-binary=:all: --require-hashes' 'offline hash-locked wheel install'
Assert-Contains $phase4 'PIP_NO_CACHE_DIR=1' 'offline updater install cannot persist a pip cache'
Assert-Contains $phase4 'wheelhouse_supply_chain.py" verify' 'lock-wheel-SBOM-dist-info parity verifier'
Assert-Contains $phase4 'uten-imp-updater-wheelhouse-v1' 'signed wheelhouse attestation namespace'
Assert-Contains $phase4 'local wheelhouse verifier differs from the signed protected source' 'signed verifier source digest binding'
Assert-Contains $phase4 '-m pip uninstall --yes pip' 'updater runtime has no package installer'
Assert-Contains $phase4 'runuser -u uten-imp-updater' 'unprivileged dependency build and candidate inspection'
Assert-Contains $phase4 'operation lock must be root:uten-imp-updater 0660 with one hard link' 'fixed root-owned shared lock'
Assert-Contains $phase4 '"$ROOT_STATE/recovery-evidence" "$ROOT_STATE/database-receipts"' 'root-only recovery evidence directories'
Assert-Contains $phase4 'uten-imp-recover.sh" /usr/local/sbin/uten-imp-recover' 'root recovery wrapper installation'
Assert-Contains $phase4 'STABLE_DB_RECOVERY_VERIFIER=/usr/local/libexec/uten-imp-release/database_recovery_verifier.py' 'fixed database recovery verifier install path'
Assert-Contains $phase4 'installed {name} digest differs from updater policy' 'database/runtime verifier digest pin'
Assert-Contains $phase4 'runtime boot verifier {name} dependency digest is stale' 'runtime verifier dependency digest pin'
Assert-Contains $phase4 '"$UPDATER_SOURCE/retention_manager.py" "$new_updater/retention_manager.py"' 'Phase 4 preserves installed retention manager'
Assert-Contains $phase4 'ordinary reinstall may not collapse trust' 'signing-key rotation overlap guard'
Assert-Contains $phase4 'ssl_reject_handshake on;' 'expanded TLS catch-all audit'
Assert-Contains $phase4 '--enable-staging is intentionally NO-GO' 'staging fail-closed until retention'
Assert-Contains $phase4 'STAGING_NOT_ENABLED' 'default install-only outcome'
Assert-NotContains $phase4 'pip install --quiet --no-cache-dir oss2' 'legacy root online pip install'
Assert-NotContains $phase4 'uten-imp-http-lan.conf' 'legacy plaintext LAN site installation'
Assert-Contains $phase4 'pre-existing updater credential/config/state requires the audited retirement helper' 'legacy downloader credential/config/state rejection'
Assert-Contains $phase4 '/usr/local/sbin/uten-imp-validate-migrator-env /etc/uten-imp-migrator/migrator.env' 'phase4 migrator environment preflight'
Assert-Contains $phase4 'installed migrator unit differs from the reviewed phase3 template' 'phase4 fixed migrator unit contract'
Assert-Contains $phase4 'installed application unit differs from the reviewed phase3 template' 'phase4 fixed application unit contract'
Assert-Contains $phase4 'uten-imp-migrate.service' 'phase4 migrator inactivity and disable gate'
Assert-Contains $phase4 'stable privileged release guard differs from the reviewed Phase 4 source' 'stable verifier byte parity gate'
Assert-Contains $phase4 'Phase 4 release key differs from the independently bootstrapped stable trust policy' 'stable-to-updater key parity gate'
Assert-NotContains $phase4 'chown root:uten-imp /etc/uten-imp/oss-pull.env' 'legacy application-readable downloader credential installation'

# PostgreSQL repo2, continuous WAL, external alert and PITR acceptance boundaries.
Assert-Contains $text.BackupReadme '<!-- REAL-REPO2-WORM-PITR-ALERTS-NO-GO -->' 'repo2 source-only NO-GO'
Assert-Contains $text.BackupReadme '<!-- CURRENT-ERP-TEST-SERVER-SCOPE-20260812 -->' 'backup schedule current test-host scope'
Assert-Contains $text.Repo2Renderer 'render-candidate never writes under /etc' 'repo2 renderer cannot install active config'
Assert-Contains $text.Repo2Renderer 'WORM evidence SHA-256 differs from the out-of-band approved digest' 'WORM out-of-band digest binding'
Assert-Contains $text.Repo2Renderer 'active WORM evidence differs from the approved digest' 'active WORM read-back digest gate'
Assert-Contains $text.Repo2Renderer 'active repo2 config exact key set differs from the renderer' 'active repo2 semantic config gate'
Assert-Contains $text.Repo2Renderer 'repo2-storage-verify-tls=y' 'repo2 TLS verification'
Assert-Contains $text.BackupHealth 'restore points are not from {minimum_points} distinct UTC dates' 'seven daily restore-point gate'
Assert-Contains $text.BackupHealth 'repo1 and repo2 latest archived WAL identities differ' 'dual-repository WAL parity gate'
Assert-Contains $text.BackupHealth 'both repositories are behind PostgreSQL last archived WAL' 'dual-repository archived-WAL target gate'
Assert-Contains $text.BackupHealth 'walInventoryContinuityProvenByThisCheck' 'WAL inventory continuity non-claim'
Assert-Contains $text.BackupHealth 'repositoryCheckPerformedByThisRun' 'five-minute health repository-check non-claim'
Assert-NotContains $text.BackupHealth '_run_check(' 'five-minute health must not probe archive paths'
Assert-Contains $text.BackupHealth 'does not identify exactly one current PostgreSQL system' 'backup inventory system identifier binding'
Assert-Contains $text.BackupHealth 'canonicalHistorySha256' 'canonical Flyway history digest'
Assert-Contains $text.BackupHealth 'signedProjectionSha256' 'live Flyway signed-row projection digest'
Assert-Contains $text.BackupHealth 'spec_from_file_location("pgbackrest_repo2", sibling)' 'isolated health sibling import'
Assert-Contains $text.BackupAlert 'FIXED_SENDER = Path("/usr/local/libexec/uten-imp-alerting/submit")' 'fixed external alert sender'
Assert-Contains $text.BackupAlert 'external alert receipt does not acknowledge this event' 'provider receipt event binding'
Assert-Contains $text.BackupAcceptance 'remoteImmutabilityVerifiedSeparately' 'WORM evidence remains separate from health'
Assert-Contains $text.BackupAcceptance 'active_repo2_preflight = validate_active(' 'final receipt revalidates active repo2 approval/config'
Assert-Contains $text.BackupAcceptance 'isolatedRepo2PitrVerifiedSeparately' 'repo2 PITR evidence gate'
Assert-Contains $text.BackupAcceptance 'verified-flyway-checksums' 'root-installed signed Flyway inventory verifier'
Assert-Contains $text.BackupAcceptance 'live Flyway versions/scripts/checksums differ from the signed manifest' 'live database exact signed Flyway row gate'
Assert-Contains $text.BackupAcceptance 'restore receipt backup set differs from PITR acceptance' 'restore receipt backup-set binding'
Assert-Contains $text.BackupAcceptance 'def _fixed_sibling(' 'isolated acceptance sibling import'
Assert-Contains $text.BackupAcceptance 'evidenceReference": f"path={detail_path};sha256={detail_sha}"' 'narrow recovery receipt binds detailed evidence'
Assert-Contains $text.Repo2BackupUnit 'ExecStart=/usr/bin/python3 -I /usr/local/libexec/uten-imp-backup/locked_job.py repo2' 'repo2 fixed durable locked-job entrypoint'
Assert-Contains $text.BackupLockedJob 'REPO2_PREFLIGHT = (' 'repo2 preflight is fixed inside the locked job'
Assert-Contains $text.BackupLockedJob '"/usr/local/libexec/uten-imp-backup/pgbackrest_repo2.py"' 'repo2 fixed active-config verifier path'
Assert-Contains $text.BackupLockedJob 'PGBACKREST_BASE + ("--repo=2", "check")' 'repo2 repository check precedes the backup'
Assert-NotContains $text.Repo2BackupUnit 'ConditionPathExists=' 'repo2 missing approval must fail, not skip'
Assert-Contains $text.BackupHealthUnit 'ExecStart=/usr/bin/python3 -I /usr/local/libexec/uten-imp-backup/locked_job.py health' 'health fixed durable locked-job entrypoint'
Assert-Contains $text.BackupLockedJob '+ ("--repo=2", "--no-expire-auto", "--type=full", "backup")' 'separate repo2 daily full with explicit post-success expiry'
Assert-Contains $text.Repo2BackupUnit 'network-online.target uten-pgbackup.service' 'repo1 and repo2 reboot catch-up ordering'
Assert-Contains $text.Repo2BackupTimer 'OnCalendar=*-*-* 03:17:00' 'repo2 backup schedule'
Assert-Contains $text.Repo2BackupTimer 'Persistent=true' 'repo2 power-loss catch-up'
Assert-Contains $text.BackupHealthTimer 'OnUnitActiveSec=5m' 'continuous WAL health cadence'
Assert-Contains $text.BackupHealthUnit 'uten-pgbackup.service uten-pgbackup-repo2.service' 'health waits for concurrent backup jobs'
Assert-Contains $text.Repo1BackupUnit 'OnFailure=uten-pgbackup-alert@%n.service' 'repo1 backup external alert wiring'
Assert-Contains $text.Repo1BackupUnit 'ExecStart=/usr/bin/python3 -I /usr/local/libexec/uten-imp-backup/locked_job.py repo1' 'repo1 fixed durable locked-job entrypoint'
Assert-Contains $text.BackupLockedJob '+ ("--repo=1", "--no-expire-auto", "--type=full", "backup")' 'repo1 backup explicit repository selection'
Assert-Contains $text.Repo2Renderer 'repo1 backup override differs from the reviewed explicit-repository contract' 'repo2 activation requires exact repo1 override'
Assert-Contains $text.Repo2Renderer 'repo1OverrideSha256' 'repo2 approval binds repo1 override digest'
Assert-Contains $text.BackupAlertUnit 'StateDirectory=uten-imp-backup-alerts' 'durable root alert spool'
Assert-Contains $text.BackupAlertDrainTimer 'OnBootSec=5m' 'pending alert retry after downtime'
Assert-NotContains $text.BackupAlertDrainTimer 'Persistent=true' 'monotonic alert timer must not misclaim calendar persistence'

# Browser release identity and public website packaging boundaries.
Assert-Contains $webIndex '<meta name="uten-release-version" content="__UTEN_RELEASE_VERSION__">' 'build-stamped Web release identity'
Assert-Contains $webUpdate 'new URL("version.json", document.baseURI)' 'cache-bypassed signed release probe'
Assert-Contains $webUpdate 'uten-release-version' 'initial-page release baseline'
Assert-NotContains $webUpdate 'flutter_bootstrap.js' 'unstable bootstrap fingerprint'
Assert-Contains $websiteConfig "output: 'standalone'" 'Next standalone output'
Assert-Contains $websiteAssembler 'Release target must not overlap a release source' 'website release/source overlap guard'
Assert-Contains $websiteRuntimeValidator '"$release/.next/cache") ;;' 'website runtime symlink allowlist'
Assert-Contains $websiteRuntimeValidator 'immutable release must not contain or link a runtime uploads path' 'website release-local uploads rejection'
Assert-Contains $websiteRuntimeValidator 'file:/var/lib/uten-website/runtime/website.db' 'website persistent database pin'
Assert-Contains $websiteRuntimeValidator 'website.env exact key set is incomplete' 'website strict environment key set'
Assert-Contains $websiteRuntimeValidator 'uten-website:uten-website:600:1' 'website SQLite owner and mode gate'
Assert-Contains $websiteRuntimeValidator 'SQLite 3 file header' 'website SQLite file identity gate'
Assert-Contains $websiteRuntimeValidator 'runtime state must be exact mode 0750' 'website writable state mode gate'

# CI: complete quality gates and isolated protected publication.
Assert-NotContains $workflow '-DskipTests' 'skipped backend tests in release workflow'
Assert-Contains $workflow 'mvn -f server/pom.xml --batch-mode --no-transfer-progress clean verify' 'clean backend release gate'
Assert-Contains $workflow 'server/target/classes/META-INF/sbom/application.cdx.json' 'Spring Boot canonical backend SBOM path'
Assert-NotContains $workflow 'server/target/bom.json' 'nonexistent backend SBOM path'
Assert-Contains $workflow 'flutter test' 'Flutter release tests'
Assert-Contains $workflow 'python3 -m unittest discover -s deploy/updater -p "test*.py" -v' 'all updater security regression tests'
Assert-Contains $workflow 'python3 -m unittest discover -s deploy/postgres/backup -p "test*.py" -v' 'all backup, repo2, PITR receipt and external alert regression tests'
Assert-Contains $workflow 'python3 -m unittest discover -s deploy/setup -p "test*.py" -v' 'all reviewed-host setup and commissioning regression tests'
Assert-Contains $workflow 'python3 -m unittest discover -s deploy/monitoring -p "test*.py" -v' 'all host monitoring and installer regression tests'
Assert-Contains $workflow 'python3 -m unittest discover -s deploy/aliyun-oidc -p "test*.py" -v' 'all rendered Aliyun OIDC policy regression tests'
Assert-Contains $workflow '  publish-release:' 'isolated publish job'
Assert-Contains $workflow '      - build-release-candidate' 'fresh publish job artifact dependency'
Assert-Contains $workflow 'environment: production-release-publisher' 'protected publisher environment'
Assert-Contains $workflow 'environment: production-release-bootstrap' 'protected bootstrap environment'
Assert-Contains $workflow 'ALIYUN_RELEASE_PUBLISHER_ROLE_ARN' 'independent publisher role'
Assert-Contains $workflow 'ALIYUN_RELEASE_BOOTSTRAP_ROLE_ARN' 'independent bootstrap role'
Assert-NotContains $workflow 'ALIYUN_RELEASE_ROLE_ARN' 'legacy shared Aliyun release role'
Assert-Contains $workflow 'readback_exact' 'publisher exact object readback'
Assert-Contains $workflow '"releases/$V/$ARTIFACT" artifact.tar.gz' 'publisher artifact byte readback'
Assert-Contains $workflow '"$CANDIDATE/backend.cdx.json" "$READBACK/backend.cdx.json"' 'bootstrap SBOM byte readback'
Assert-Contains $workflow '/tmp/token "$RUNNER_TEMP/token"' 'transient action OIDC token cleanup'
Assert-Contains $oidcAcceptanceWorkflow 'expected_release_ref:' 'OIDC acceptance exact ref input'
Assert-Contains $oidcAcceptanceWorkflow 'RELEASE_REF_PROTECTED' 'OIDC acceptance protected-tag gate'
Assert-Contains $oidcAcceptanceWorkflow 'ALIBABA_CLOUD_SECURITY_TOKEN' 'OIDC acceptance STS token proof'
Assert-NotContains $oidcAcceptanceWorkflow 'actions/checkout' 'OIDC acceptance checkout'
Assert-NotContains $oidcAcceptanceWorkflow 'put-object' 'OIDC acceptance OSS write'
Assert-Contains $workflow 'id-token: write' 'short-lived publish identity permission'
Assert-Contains $workflow 'FlywayChecksumManifestExporterTest' 'official Flyway checksum exporter gate'
Assert-Contains $workflow 'bash deploy/updater/build-wheelhouse.sh' 'digest-pinned updater wheelhouse build'
Assert-Contains $workflow 'bash deploy/updater/test-wheelhouse-offline.sh' 'Ubuntu 24.04 network-isolated updater test'
Assert-Contains $text.WheelhouseBuilder '--network none --read-only --cap-drop ALL' 'networkless least-privilege source-wheel build'
Assert-Contains $text.WheelhouseBuilder 'must run as an unprivileged host user and group' 'non-root wheelhouse builder identity'
Assert-Contains $workflow 'deploy/updater/wheelhouse/source-requirements.lock' 'protected source-archive hash lock binding'
Assert-Contains $workflow 'deploy/updater/wheelhouse/build-requirements.lock' 'protected build-tool hash lock binding'
Assert-Contains $workflow 'uten-imp-updater-wheelhouse-v1' 'dedicated signed updater attestation namespace'
Assert-Contains $workflow 'updater-wheelhouse.attestation.sig' 'signed updater attestation publication'
Assert-Contains $text.ReleaseTools 'flywayChecksum' 'signed Flyway int32 checksum field'

# Cloud templates remain separate and do not weaken the on-prem boundary.
Assert-Contains $text.CloudNginx 'server 127.0.0.1:8080;' 'cloud loopback backend'
Assert-Contains $text.CloudNginx 'ssl_certificate __TLS_CERT_PATH__;' 'cloud TLS placeholder'
Assert-Contains $text.CloudSystemd 'ProtectSystem=full' 'cloud service filesystem hardening'
Assert-Contains $text.CloudSystemd 'LEGACY-CLOUD-UNIT-DO-NOT-INSTALL' 'legacy cloud unit execution stop'
Assert-Contains $text.CloudReadme 'UTEN_PROFILE=cloud,prod' 'cloud production profile'
Assert-Regex $text.CloudReadme 'Bucket[^\r\n]+storage_key \+ versionId' 'OSS version cleanup guard'

# Existing physical-replication guardrails are still part of the deployment contract.
Assert-Contains $text.PreparePrimary 'RECREATE_INVALID_SLOT="${RECREATE_INVALID_SLOT:-no}"' 'slot recreation defaults closed'
Assert-Contains $text.PreparePrimary 'pg_create_physical_replication_slot(' 'physical replication slot creation'
Assert-Contains $text.CloneReplica '--wal-method stream' 'streaming base backup'
Assert-Contains $text.CloneReplica 'primary_slot_name' 'permanent standby slot assignment'
Assert-NotContains $text.CloneReplica '--slot "$SLOT_NAME"' 'live standby permanent-slot theft'
Assert-Contains $text.PrepareStandbyHba 'refusing to prepare standby HBA on a writable primary' 'standby-only HBA guard'
Assert-Contains $text.ReplicationHarness 'Re-cloning while the permanent slot is active' 'live-slot regression scenario'

if ([regex]::IsMatch($text.DeployReadme, '(?m)^\+\s{2,}')) {
    throw 'Deployment README contains patch-residue plus markers'
}

'Deployment template contract checks passed.'
