package com.uten.imp.application.port;

import java.util.Map;

/**
 * A bounded chat capability owned by a business feature. The model may suggest arguments, never
 * authority. Implementations recheck current identity, permissions and row scope on every call.
 * Only read operations and operation previews belong here; writes require a separate authenticated
 * confirmation endpoint with the normal business validation, step-up and audit trail.
 */
public interface AiChatToolPort {
    String name();
    String title();
    String description();
    /** SELF, SALES, PRODUCTION, PURCHASE, WAREHOUSE, FINANCE, QUALITY, SUBCONTRACT, HR, RD or ADMIN. */
    String domain();
    /** JSON Schema for the bounded argument object, including additionalProperties=false. */
    Map<String, Object> parameters();
    boolean available();
    /** Opt-in for read-query parameters only. Never retain results, proposals or authorization actions. */
    default boolean rememberQueryArguments() { return false; }
    /**
     * Returns a short, plain-language {@code reply} with business results (normally at most five
     * rows), plus optional {@code detailReply} for an explicit request to expand. Keep units,
     * periods and material uncertainty; do not append access-policy, source-system or audit prose.
     * Authorization and evidence remain server-side. Neither reply is sent back to the model.
     */
    Map<String, Object> execute(Map<String, Object> arguments);
    /**
     * Recheck server-owned object evidence before returning a stored answer. Implementations which
     * expose rows must override this: functional permission stamps do not track object reassignment.
     * The evidence is generated by execute as _toolEvidence, never accepted from a model or client.
     */
    default void authorizeResultRead(Map<String, Object> evidence) {}
}
