package com.uten.imp.features.production.mrp;

import org.junit.jupiter.api.Test;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertTrue;

class ProductionMakeSubplanLifecycleContractTest {

    @Test
    void v1ConfirmationRegistersEveryGeneratedSubplanAsPackageDocument()
            throws Exception {
        String source = source("ProductionExecutionPackageCommandService.java");

        int generate = source.indexOf("generateSelfMadeSubplansForPackage");
        int record = source.indexOf("ledger.recordDocument(", generate);
        int result = source.indexOf("return new PlanningPackageResult(", record);

        assertTrue(generate >= 0 && record > generate && result > record);
        assertTrue(source.substring(record, result).contains("\"SUBPLAN\""));
        assertTrue(source.substring(record, result).contains("subplan.planId()"));
        assertTrue(source.substring(record, result).contains("subplan.billNo()"));
    }

    @Test
    void v1SelfMadeSubplanUsesOnlyDirectAllocationShortage() throws Exception {
        String mrp = source("MrpService.java");
        int start = mrp.indexOf(
                "generateSelfMadeSubplansForPackage(");
        int end = mrp.indexOf(
                "    private static List<DirectMakeRequirement>", start);

        assertTrue(start >= 0 && end > start);
        String method = mrp.substring(start, end);
        assertTrue(method.contains("List<DirectMakeRequirement>"));
        assertTrue(method.contains("item.setQty(row.shortageQty())"));
        assertTrue(method.contains("item.setOqty(row.requiredQty())"));
        assertTrue(!method.contains("explode(planId)"));
        assertTrue(method.contains("if (make.isEmpty())"));
        assertTrue(method.contains("return List.of();"));
        assertTrue(method.contains("if (existing.intValue() > 0)"));
        assertTrue(method.contains("该父计划已存在有效的执行分段(EXECUTION_V1)子计划，不能重复生成"));

        String command = source(
                "ProductionExecutionPackageCommandService.java");
        assertTrue(command.contains(
                "directMakeRequirements(allocation)"));
    }

    @Test
    void genericPlanLifecycleCannotOrphanExecutionV1Subplan()
            throws Exception {
        String source = Files.readString(Path.of(
                "src/main/java/com/uten/imp/features/production/plan/ProductionPlanService.java"));

        int delete = source.indexOf("public void delete(UUID id)");
        int approve = source.indexOf("public PlanDetail approve(UUID id)");
        int reverse = source.indexOf("public PlanDetail reverse(UUID id)");
        int progress = source.indexOf("// ====================== 生产进度看板聚合", reverse);

        assertTrue(delete >= 0 && approve > delete);
        assertTrue(reverse >= 0 && progress > reverse);
        assertTrue(source.substring(delete, approve).contains(
                "rejectDirectLifecycleOfExecutionV1Subplan(id, \"删除\")"));
        assertTrue(source.substring(reverse, progress).contains(
                "rejectDirectLifecycleOfExecutionV1Subplan(id, \"红冲\")"));
        assertTrue(source.contains("link.source = 'EXECUTION_V1'"));
        assertTrue(source.contains("请从父计划的计划包执行取消或红冲"));
    }

    @Test
    void parentPackageLifecycleRejectsChildWithConfirmedExecutionPackage()
            throws Exception {
        String source = source("ProductionPlanningPackageService.java");
        int downstream = source.indexOf("private boolean hasActiveSubplanDownstream");
        int nextMethod = source.indexOf("private boolean isAutoGeneratedPlan", downstream);

        assertTrue(downstream >= 0 && nextMethod > downstream);
        String method = source.substring(downstream, nextMethod);
        assertTrue(method.contains("FROM production_planning_packages package"));
        assertTrue(method.contains("package.plan_id = :id"));
        assertTrue(method.contains("package.status = 'CONFIRMED'"));
    }

    private static String source(String file) throws Exception {
        return Files.readString(Path.of(
                "src/main/java/com/uten/imp/features/production/mrp/" + file));
    }
}
