\set ON_ERROR_STOP on
-- Test-only destruction explicitly confirmed by the user: business facts and
-- their old history are cleared. Current masters/configuration remain; reset
-- control receipts survive so a reconnecting client can resolve its old attempt.
-- Ordinary deletion/expiry still retains history. This script creates no backup.
-- Stop the application/workers first, and finish the explicit object cleanup.
-- Required arguments: -v confirm=CLEAR_BUSINESS -v expected_database=<database>
--                     -v expected_system_identifier=<pg_control_system identity>
-- The installed business_data_reset() is the sole implementation for app/psql.
-- This independent table policy is checked both before and after that function;
-- policy drift, object-cleanup refusal or any validation error rolls back SQL.

\if :{?confirm}
\else
  \set confirm 'MISSING'
\endif
\if :{?expected_database}
\else
  \set expected_database 'MISSING'
\endif
\if :{?expected_system_identifier}
\else
  \set expected_system_identifier 'MISSING'
\endif
SELECT set_config('app.reset_business_confirm',:'confirm',false),
       set_config('app.reset_business_expected_database',:'expected_database',false),
       set_config('app.reset_business_expected_system_identifier',:'expected_system_identifier',false);

BEGIN;
SET LOCAL lock_timeout='10s';
SET LOCAL statement_timeout='30min';
SELECT set_config('app.actor_account','ops:reset_business_data',true),
       set_config('app.audit_request_id',gen_random_uuid()::text,true);

DO $offline_identity$
DECLARE actual_system_identifier text; other_connections bigint;
    applied_max_version integer; applied_migration_count bigint;
BEGIN
    IF current_setting('app.reset_business_confirm',true) IS DISTINCT FROM 'CLEAR_BUSINESS' THEN
        RAISE EXCEPTION '拒绝执行：confirm 必须等于 CLEAR_BUSINESS';
    END IF;
    IF current_database() IS DISTINCT FROM current_setting('app.reset_business_expected_database',true) THEN
        RAISE EXCEPTION '拒绝执行：目标数据库不匹配';
    END IF;
    SELECT system_identifier::text INTO actual_system_identifier FROM pg_control_system();
    IF actual_system_identifier IS DISTINCT FROM current_setting('app.reset_business_expected_system_identifier',true) THEN
        RAISE EXCEPTION '拒绝执行：目标 PostgreSQL system_identifier 不匹配';
    END IF;
    SELECT count(*) INTO other_connections FROM pg_stat_activity
    WHERE datname=current_database() AND pid <> pg_backend_pid() AND backend_type = 'client backend';
    IF other_connections<>0 THEN RAISE EXCEPTION '拒绝执行：请先停止应用和 worker，仍有 % 个连接',other_connections; END IF;
    SELECT max(version::integer),count(*) INTO applied_max_version,applied_migration_count
    FROM flyway_schema_history WHERE success AND type='SQL' AND version ~ '^[0-9]+$';
    -- Historical catalog accounting remains independently recountable. Execution
    -- requires V784+ so earlier reset functions cannot erase goods master settings.
    -- V507/469、V508/470及V511至V793完整目录
    IF applied_max_version<784 OR (applied_max_version, applied_migration_count) NOT IN (
        (443, 405),
        (446, 408),
        (447, 409),
        (448, 410),
        (449, 411),
        (450, 412),
        (451, 413),
        (452, 414),
        (453, 415),
        (454, 416),
        (455, 417),
        (456, 418),
        (457, 419),
        (458, 420),
        (459, 421),
        (460, 422),
        (461, 423),
        (462, 424),
        (463, 425),
        (464, 426),
        (465, 427),
        (466, 428),
        (467, 429),
        (468, 430),
        (469, 431),
        (470, 432),
        (471, 433),
        (472, 434),
        (473, 435),
        (474, 436),
        (475, 437),
        (476, 438),
        (477, 439),
        (478, 440),
        (479, 441),
        (480, 442),
        (481, 443),
        (482, 444),
        (483, 445),
        (484, 446),
        (485, 447),
        (486, 448),
        (487, 449),
        (488, 450),
        (489, 451),
        (490, 452),
        (491, 453),
        (492, 454),
        (493, 455),
        (494, 456),
        (495, 457),
        (496, 458),
        (497, 459),
        (498, 460),
        (499, 461),
        (500, 462),
        (501, 463),
        (502, 464),
        (503, 465),
        (504, 466),
        (505, 467),
        (506, 468),
        (507, 469),
        (508, 470),
        (511, 471),
        (513, 472),
        (514, 473),
        (515, 474),
        (516, 475),
        (517, 476),
        (518, 477),
        (519, 478),
        (520, 479),
        (521, 480),
        (522, 481),
        (523, 482),
        (524, 483),
        (525, 484),
        (526, 485),
        (527, 486),
        (528, 487),
        (529, 488),
        (530, 489),
        (531, 490),
        (532, 491),
        (533, 492),
        (534, 493),
        (535, 494),
        (536, 495),
        (537, 496),
        (538, 497),
        (539, 498),
        (540, 499),
        (541, 500),
        (542, 501),
        (543, 502),
        (545, 503),
        (546, 504),
        (547, 505),
        (548, 506),
        (549, 507),
        (550, 508),
        (551, 509),
        (552, 510),
        (553, 511),
        (554, 512),
        (555, 513),
        (556, 514),
        (557, 515),
        (558, 516),
        (559, 517),
        (560, 518),
        (561, 519),
        (562, 520),
        (563, 521),
        (564, 522),
        (565, 523),
        (566, 524),
        (567, 525),
        (568, 526),
        (569, 527),
        (570, 528),
        (571, 529),
        (572, 530),
        (573, 531),
        (574, 532),
        (575, 533),
        (577, 534),
        (578, 535),
        (579, 536),
        (580, 537),
        (581, 538),
        (582, 539),
        (583, 540),
        (584, 541),
        (585, 542),
        (586, 543),
        (587, 544),
        (588, 545),
        (589, 546),
        (590, 547),
        (591, 548),
        (592, 549),
        (593, 550),
        (594, 551),
        (595, 552),
        (596, 553),
        (597, 554),
        (598, 555),
        (599, 556),
        (600, 557),
        (601, 558),
        (602, 559),
        (603, 560),
        (605, 561),
        (606, 562),
        (607, 563),
        (608, 564),
        (609, 565),
        (610, 566),
        (611, 567),
        (612, 568),
        (613, 569),
        (614, 570),
        (615, 571),
        (616, 572),
        (617, 573),
        (618, 574),
        (619, 575),
        (620, 576),
        (621, 577),
        (622, 578),
        (623, 579),
        (624, 580),
        (625, 581),
        (626, 582),
        (627, 583),
        (628, 584),
        (629, 585),
        (630, 586),
        (631, 587),
        (632, 588),
        (634, 589),
        (636, 590),
        (638, 591),
        (640, 592),
        (641, 593),
        (642, 594),
        (644, 595),
        (645, 596),
        (646, 597),
        (647, 598),
        (670, 599),
        (671, 600),
        (672, 601),
        (673, 602),
        (674, 603),
        (675, 604),
        (676, 605),
        (677, 606),
        (678, 607),
        (679, 608),
        (680, 609),
        (681, 610),
        (682, 611),
        (683, 612),
        (684, 613),
        (685, 614),
        (686, 615),
        (687, 616),
        (688, 617),
        (689, 618),
        (690, 619),
        (691, 620),
        (692, 621),
        (693, 622),
        (694, 623),
        (695, 624),
        (696, 625),
        (697, 626),
        (698, 627),
        (699, 628),
        (700, 629),
        (701, 630),
        (702, 631),
        (703, 632),
        (704, 633),
        (705, 634),
        (706, 635),
        (707, 636),
        (708, 637),
        (709, 638),
        (710, 639),
        (711, 640),
        (712, 641),
        (713, 642),
        (714, 643),
        (715, 644),
        (716, 645),
        (717, 646),
        (718, 647),
        (719, 648),
        (720, 649),
        (721, 650),
        (722, 651),
        (723, 652),
        (724, 653),
        (725, 654),
        (726, 655),
        (727, 656),
        (728, 657),
        (729, 658),
        (730, 659),
        (731, 660),
        (732, 661),
        (733, 662),
        (734, 663),
        (735, 664),
        (736, 665),
        (738, 666),
        (739, 667),
        (740, 668),
        (741, 669),
        (742, 670),
        (743, 671),
        (744, 672),
        (745, 673),
        (746, 674),
        (747, 675),
        (748, 676),
        (749, 677),
        (750, 678),
        (751, 679),
        (752, 680),
        (753, 681),
        (754, 682),
        (755, 683),
        (756, 684),
        (757, 685),
        (758, 686),
        (759, 687),
        (760, 688),
        (763, 689),
        (764, 690),
        (765, 691),
        (766, 692),
        (767, 693),
        (768, 694),
        (769, 695),
        (770, 696),
        (771, 697),
        (772, 698),
        (773, 699),
        (774, 700),
        (775, 701),
        (776, 702),
        (777, 703),
        (778, 704),
        (779, 705),
        (780, 706),
        (781, 707),
        (782, 708),
        (783, 709),
        (784, 710),
        (785, 711),
        (786, 712),
        -- V787：手工出入库单行级仓库与库位学习（原占位 V782 撞号顺延）。
        (787, 713),
        (788, 714),
        (789, 715),
        -- V790：客户信用汇总窄口径查看权限（只插目录与权限面，不加表）。
        (790, 716),
        -- V791：报价模板采用证据钉版本；V792：销售订单重新报价证据围栏。
        (791, 717),
        (792, 718),
        -- V793：单设备登录撤销原因放行（重建 CHECK，不加表）。
        (793, 719)
    ) THEN
        RAISE EXCEPTION '测试清空要求已核对的完整目录（最低 V784/710，现已登记 V793/719），实际 V%/%',applied_max_version,applied_migration_count;
    END IF;
    IF to_regprocedure('public.fn_business_test_reset_active()') IS NULL THEN
        RAISE EXCEPTION '显式测试清空能力未安装，拒绝执行';
    END IF;
END $offline_identity$;

CREATE TEMP TABLE reset_business_expected_policy(
    table_name text PRIMARY KEY,disposition text NOT NULL CHECK(disposition IN('CLEAR','PRESERVE'))
) ON COMMIT DROP;
INSERT INTO reset_business_expected_policy(table_name,disposition) VALUES
('account_balance_adjustment_batches', 'CLEAR'),
('account_balance_adjustment_items', 'CLEAR'),
('account_flow_monthly_summaries', 'CLEAR'),
('accounts', 'PRESERVE'),
('ai_call_logs', 'CLEAR'),
('ai_input_original_bindings', 'CLEAR'),
('ai_input_originals', 'CLEAR'),
('ai_jobs', 'CLEAR'),
('ai_provider_history', 'CLEAR'),
('ai_providers', 'PRESERVE'),
('ar_ap_ledger', 'CLEAR'),
('ar_ap_source_refs', 'CLEAR'),
('attachment_object_outbox', 'PRESERVE'),
('attachment_reconciliation_findings', 'PRESERVE'),
('attachment_upload_sessions', 'PRESERVE'),
('attachments', 'PRESERVE'),
('audit_log', 'PRESERVE'),
('audit_log_archive', 'PRESERVE'),
('auth_sessions', 'CLEAR'),
('auth_step_up_states', 'CLEAR'),
('authorization_state', 'PRESERVE'),
('business_column_definitions', 'PRESERVE'),
('business_document_sequences', 'PRESERVE'),
('business_identifier_conflicts', 'PRESERVE'),
('business_identifier_namespaces', 'PRESERVE'),
('business_identifier_reservation_members', 'PRESERVE'),
('business_identifier_reservations', 'PRESERVE'),
('business_outbox', 'CLEAR'),
('business_prefix_reservation_members', 'PRESERVE'),
('business_prefix_reservations', 'PRESERVE'),
('business_record_history', 'CLEAR'),
('business_record_identities', 'CLEAR'),
('business_record_retention_registry', 'PRESERVE'),
('business_test_object_cleanup_intents', 'CLEAR'),
('category_master_code_sequences', 'PRESERVE'),
('client_access_change_events', 'PRESERVE'),
('client_categories', 'PRESERVE'),
('client_default_settlement_migration_issues', 'PRESERVE'),
('client_goods_aliases', 'PRESERVE'),
('client_ship_addresses', 'PRESERVE'),
('client_visibility_grants', 'PRESERVE'),
('clients', 'PRESERVE'),
('colors', 'PRESERVE'),
('currencies', 'PRESERVE'),
('customer_open_item_offset_batches', 'CLEAR'),
('customer_open_item_offsets', 'CLEAR'),
('da_amortization_log', 'CLEAR'),
('deferred_expenses', 'CLEAR'),
('department_permissions', 'PRESERVE'),
('departments', 'PRESERVE'),
('doc_number_sequences', 'PRESERVE'),
('emergency_contacts', 'PRESERVE'),
('employee_compensation', 'PRESERVE'),
('employee_contracts', 'PRESERVE'),
('employee_credentials', 'PRESERVE'),
('employee_data_handover_scopes', 'PRESERVE'),
('employee_data_handovers', 'PRESERVE'),
('employee_education', 'PRESERVE'),
('employee_offboarding_events', 'PRESERVE'),
('employee_phones', 'PRESERVE'),
('employee_secondary_departments', 'PRESERVE'),
('employee_sensitive', 'PRESERVE'),
('employee_vehicles', 'PRESERVE'),
('employees', 'PRESERVE'),
('employment_history', 'PRESERVE'),
('execution_segment_sales_allocations', 'CLEAR'),
('expense_claim_events', 'CLEAR'),
('expense_claim_invoices', 'CLEAR'),
('expense_claim_items', 'CLEAR'),
('expense_claim_settings', 'PRESERVE'),
('expense_claims', 'CLEAR'),
('fa_depreciation_log', 'CLEAR'),
('finance_asset_accounting_periods', 'CLEAR'),
('finance_asset_approval_steps', 'CLEAR'),
('finance_asset_books', 'CLEAR'),
('finance_asset_categories', 'PRESERVE'),
('finance_asset_events', 'CLEAR'),
('finance_asset_posting_lines', 'CLEAR'),
('finance_asset_posting_runs', 'CLEAR'),
('finance_bank_transfer_lines', 'CLEAR'),
('finance_bank_transfers', 'CLEAR'),
('finance_check_register', 'CLEAR'),
('finance_deferral_schedule_lines', 'CLEAR'),
('finance_deferral_schedule_versions', 'CLEAR'),
('finance_expense_items', 'CLEAR'),
('finance_expenses', 'CLEAR'),
('finance_other_income_items', 'CLEAR'),
('finance_other_incomes', 'CLEAR'),
('finance_payment_lines', 'CLEAR'),
('finance_payment_methods', 'PRESERVE'),
('finance_payments', 'CLEAR'),
('finance_receipt_lines', 'CLEAR'),
('finance_receipt_source_allocations', 'CLEAR'),
('finance_receipts', 'CLEAR'),
('finance_reconciliations', 'CLEAR'),
('finance_report_line_bindings', 'PRESERVE'),
('fixed_assets', 'CLEAR'),
('flyway_schema_history', 'PRESERVE'),
('gl_entries', 'CLEAR'),
('gl_vouchers', 'CLEAR'),
('goods', 'PRESERVE'),
('goods_bom_actual_usages', 'PRESERVE'),
('goods_bom_items', 'PRESERVE'),
('goods_bom_learning_profiles', 'PRESERVE'),
('goods_cost_commands', 'PRESERVE'),
('goods_cost_import_mappings', 'PRESERVE'),
('goods_cost_imports', 'PRESERVE'),
('goods_cost_sheets', 'PRESERVE'),
('goods_cost_snapshots', 'PRESERVE'),
('goods_cost_templates', 'PRESERVE'),
('goods_import_batches', 'PRESERVE'),
('goods_import_creations', 'PRESERVE'),
('goods_periodic_material_choices', 'PRESERVE'),
('goods_weight_estimates', 'PRESERVE'),
('goods_weight_observations', 'PRESERVE'),
('goods_weight_profiles', 'PRESERVE'),
('hr_task_claims', 'CLEAR'),
('inbound_expectation_items', 'CLEAR'),
('inbound_expectations', 'CLEAR'),
('inventory_cost_gl_links', 'CLEAR'),
('inventory_cost_gl_period_choices', 'CLEAR'),
('inventory_cost_gl_periods', 'CLEAR'),
('inventory_cost_gl_policy', 'PRESERVE'),
('legacy_departments', 'PRESERVE'),
('legacy_finance_import_sources', 'PRESERVE'),
('legacy_migration_checkpoints', 'PRESERVE'),
('legacy_migration_reconciliation_items', 'PRESERVE'),
('legacy_migration_rejects', 'PRESERVE'),
('legacy_migration_run_files', 'PRESERVE'),
('legacy_migration_runs', 'PRESERVE'),
('legacy_procurement_receipt_import_sources', 'PRESERVE'),
('legacy_subcontract_order_import_sources', 'PRESERVE'),
('legacy_warehouse_workshop_links', 'PRESERVE'),
('manager_permission_delegations', 'PRESERVE'),
('master_code_change_batches', 'PRESERVE'),
('master_code_history', 'PRESERVE'),
('master_code_reservation_members', 'PRESERVE'),
('master_code_reservations', 'PRESERVE'),
('master_code_sequences', 'PRESERVE'),
('material_categories', 'PRESERVE'),
('mould_categories', 'PRESERVE'),
('moulds', 'PRESERVE'),
('mrp_generations', 'CLEAR'),
('notice_acknowledgments', 'CLEAR'),
('notice_blessing_history', 'CLEAR'),
('notice_blessings', 'CLEAR'),
('notice_celebration_subjects', 'CLEAR'),
('notice_user_states', 'CLEAR'),
('notices', 'CLEAR'),
('organization_permission_leader_assignments', 'PRESERVE'),
('party_activity_records', 'PRESERVE'),
('party_addresses', 'PRESERVE'),
('party_contact_methods', 'PRESERVE'),
('password_history', 'PRESERVE'),
('payment_styles', 'PRESERVE'),
('payroll_batches', 'CLEAR'),
('payroll_items', 'CLEAR'),
('payroll_slips', 'CLEAR'),
('payroll_variable_inputs', 'CLEAR'),
('permission_surface_permissions', 'PRESERVE'),
('permission_surfaces', 'PRESERVE'),
('permissions', 'PRESERVE'),
('plan_draw_links', 'CLEAR'),
('plan_order_item_links', 'CLEAR'),
('platform_column_definitions', 'PRESERVE'),
('platform_column_usage', 'CLEAR'),
('platform_record_field_versions', 'CLEAR'),
('platform_record_fields', 'PRESERVE'),
('positions', 'PRESERVE'),
('preplan_aggregate_batch_events', 'CLEAR'),
('preplan_aggregate_batches', 'CLEAR'),
('preplan_aggregate_direct_transfer_slices', 'CLEAR'),
('preplan_aggregate_material_aliases', 'CLEAR'),
('preplan_analysis_stock_exact_pegs', 'CLEAR'),
('preplan_future_supply_transfer_cancellations', 'CLEAR'),
('preplan_future_supply_transfers', 'CLEAR'),
('preplan_make_entitlement_delegations', 'CLEAR'),
('preplan_make_public_claim_cancellations', 'CLEAR'),
('preplan_make_public_claims', 'CLEAR'),
('preplan_material_reallocations', 'CLEAR'),
('preplan_public_supply_events', 'CLEAR'),
('preplan_reallocation_make_supplements', 'CLEAR'),
('preplan_root_output_events', 'CLEAR'),
('preplan_stock_entitlement_events', 'CLEAR'),
('preplan_subcontract_entitlement_handoff_slices', 'CLEAR'),
('preplan_subcontract_make_batch_reversals', 'CLEAR'),
('preplan_subcontract_make_task_batches', 'CLEAR'),
('preplan_subcontract_make_tasks', 'CLEAR'),
('preplan_subcontract_requirement_handoff_events', 'CLEAR'),
('preplan_subcontract_requirement_handoff_items', 'CLEAR'),
('preplan_subcontract_requirement_handoffs', 'CLEAR'),
('preplan_subcontract_requirement_supply_claims', 'CLEAR'),
('preplan_supply_action_allocations', 'CLEAR'),
('preplan_supply_actions', 'CLEAR'),
('procurement_arrival_exception_events', 'CLEAR'),
('procurement_arrival_exceptions', 'CLEAR'),
('procurement_inspection_events', 'CLEAR'),
('procurement_inspection_items', 'CLEAR'),
('procurement_iqc_consideration_reversals', 'CLEAR'),
('procurement_iqc_consideration_review_approvals', 'CLEAR'),
('procurement_iqc_credit_case_allocations', 'CLEAR'),
('procurement_iqc_credit_documents', 'CLEAR'),
('procurement_iqc_credit_slices', 'CLEAR'),
('procurement_iqc_funding_settlements', 'CLEAR'),
('procurement_iqc_funding_slices', 'CLEAR'),
('procurement_iqc_quality_consideration_parts', 'CLEAR'),
('procurement_iqc_rejection_cases', 'CLEAR'),
('procurement_iqc_rejection_commands', 'CLEAR'),
('procurement_iqc_rejection_events', 'CLEAR'),
('procurement_iqc_replacement_allocations', 'CLEAR'),
('procurement_iqc_stock_consideration_parts', 'CLEAR'),
('procurement_iqc_stock_in_batch_items', 'CLEAR'),
('procurement_iqc_stock_in_batches', 'CLEAR'),
('procurement_order_approval_cases', 'CLEAR'),
('procurement_order_approval_events', 'CLEAR'),
('procurement_order_qty_change_logs', 'CLEAR'),
('procurement_order_source_revision_allocations', 'CLEAR'),
('procurement_order_source_revision_peg_changes', 'CLEAR'),
('procurement_order_source_revisions', 'CLEAR'),
('procurement_receipt_consideration_parts', 'CLEAR'),
('production_actual_output_supplement_claims', 'CLEAR'),
('production_actual_output_supplement_proofs', 'CLEAR'),
('production_actual_output_supplement_requests', 'CLEAR'),
('production_actual_output_supplement_reversals', 'CLEAR'),
('production_bom_learning_refresh_queue', 'CLEAR'),
('production_bom_learning_samples', 'CLEAR'),
('production_daily_report_commands', 'CLEAR'),
('production_daily_report_items', 'CLEAR'),
('production_daily_report_material_release_events', 'CLEAR'),
('production_daily_report_material_usages', 'CLEAR'),
('production_daily_report_target_events', 'CLEAR'),
('production_daily_report_workers', 'CLEAR'),
('production_daily_reports', 'CLEAR'),
('production_draw_issue_batches', 'CLEAR'),
('production_execution_material_changes', 'CLEAR'),
('production_execution_periodic_materials', 'CLEAR'),
('production_execution_segment_events', 'CLEAR'),
('production_execution_segment_growth_events', 'CLEAR'),
('production_execution_segment_splits', 'CLEAR'),
('production_execution_segments', 'CLEAR'),
('production_finished_arrival_registration_items', 'CLEAR'),
('production_finished_arrival_registration_reversals', 'CLEAR'),
('production_finished_arrival_registrations', 'CLEAR'),
('production_finished_in_confirm_batch_items', 'CLEAR'),
('production_finished_in_confirm_batches', 'CLEAR'),
('production_finished_in_confirmation_items', 'CLEAR'),
('production_finished_in_confirmation_reversal_items', 'CLEAR'),
('production_finished_in_confirmation_reversals', 'CLEAR'),
('production_finished_in_confirmations', 'CLEAR'),
('production_fqc_cancellation_events', 'CLEAR'),
('production_fqc_contribution_adjustments', 'CLEAR'),
('production_fqc_decision_events', 'CLEAR'),
('production_fqc_inspection_sheet_items', 'CLEAR'),
('production_fqc_inspection_sheets', 'CLEAR'),
('production_fqc_inspections', 'CLEAR'),
('production_fqc_legacy_exemptions', 'CLEAR'),
('production_fqc_pass_all_batch_items', 'CLEAR'),
('production_fqc_pass_all_batches', 'CLEAR'),
('production_fqc_recovery_allocation_events', 'CLEAR'),
('production_fqc_recovery_authorizations', 'CLEAR'),
('production_fqc_recovery_cancellation_events', 'CLEAR'),
('production_fqc_release_allocations', 'CLEAR'),
('production_fqc_release_commands', 'CLEAR'),
('production_fqc_replenishment_analysis_links', 'CLEAR'),
('production_fqc_replenishment_attempts', 'CLEAR'),
('production_fqc_replenishment_cycle_cancellations', 'CLEAR'),
('production_fqc_replenishment_cycles', 'CLEAR'),
('production_fqc_replenishment_draw_links', 'CLEAR'),
('production_fqc_replenishment_ready_events', 'CLEAR'),
('production_fqc_replenishment_ready_reversals', 'CLEAR'),
('production_fqc_replenishment_supply_gaps', 'CLEAR'),
('production_fqc_replenishment_tasks', 'CLEAR'),
('production_material_analyses', 'CLEAR'),
('production_material_analysis_borrows', 'CLEAR'),
('production_material_analysis_commands', 'CLEAR'),
('production_material_analysis_items', 'CLEAR'),
('production_material_analysis_materials', 'CLEAR'),
('production_material_analysis_plan_links', 'CLEAR'),
('production_material_demands', 'CLEAR'),
('production_material_discovery_lines', 'CLEAR'),
('production_material_discovery_requests', 'CLEAR'),
('production_material_increment_decisions', 'CLEAR'),
('production_material_increment_requests', 'CLEAR'),
('production_material_increment_reversals', 'CLEAR'),
('production_material_make_receipt_allocations', 'CLEAR'),
('production_material_movement_links', 'CLEAR'),
('production_material_peg_transfers', 'CLEAR'),
('production_material_receipt_allocations', 'CLEAR'),
('production_material_return_receiving_confirmations', 'CLEAR'),
('production_material_return_request_cancellations', 'CLEAR'),
('production_material_return_request_items', 'CLEAR'),
('production_material_return_requests', 'CLEAR'),
('production_material_settlement_events', 'CLEAR'),
('production_material_settlement_postings', 'CLEAR'),
('production_material_stock_events', 'CLEAR'),
('production_material_stock_postings', 'CLEAR'),
('production_material_subcontract_peg_transfers', 'CLEAR'),
('production_material_subcontract_receipt_allocations', 'CLEAR'),
('production_material_supply_pegs', 'CLEAR'),
('production_overproduction_rate_decisions', 'CLEAR'),
('production_overproduction_rate_requests', 'CLEAR'),
('production_plan_costs', 'CLEAR'),
('production_plan_items', 'CLEAR'),
('production_planning_drafts', 'CLEAR'),
('production_planning_package_document_items', 'CLEAR'),
('production_planning_package_documents', 'CLEAR'),
('production_planning_packages', 'CLEAR'),
('production_planning_urges', 'CLEAR'),
('production_plans', 'CLEAR'),
('production_product_no_sequences', 'CLEAR'),
('production_workshop_custody_handoff_reversals', 'CLEAR'),
('production_workshop_custody_reverse_preparations', 'CLEAR'),
('production_workshop_direct_legacy_anomalies', 'CLEAR'),
('production_workshop_direct_source_allocations', 'CLEAR'),
('production_workshop_direct_source_events', 'CLEAR'),
('production_workshop_direct_transfer_items', 'CLEAR'),
('production_workshop_direct_transfer_reversals', 'CLEAR'),
('production_workshop_direct_transfers', 'CLEAR'),
('production_workshop_material_custody_handoffs', 'CLEAR'),
('production_workshop_material_custody_moves', 'CLEAR'),
('production_workshop_material_custody_preparations', 'CLEAR'),
('production_workshop_material_custody_reversals', 'CLEAR'),
('production_workshop_material_return_slices', 'CLEAR'),
('production_workshop_return_preplan_events', 'CLEAR'),
('profile_change_requests', 'PRESERVE'),
('purchase_order_item_sources', 'CLEAR'),
('purchase_order_items', 'CLEAR'),
('purchase_orders', 'CLEAR'),
('purchase_receipt_items', 'CLEAR'),
('purchase_receipts', 'CLEAR'),
('purchase_request_items', 'CLEAR'),
('purchase_requests', 'CLEAR'),
('purchase_return_items', 'CLEAR'),
('purchase_returns', 'CLEAR'),
('rd_task_forwarders', 'CLEAR'),
('rd_tasks', 'CLEAR'),
('refresh_tokens', 'PRESERVE'),
('report_materialized_view_refresh_state', 'PRESERVE'),
('sales_alias_document_evidence', 'PRESERVE'),
('sales_document_learning_receipts', 'CLEAR'),
('sales_intake_layout_learning_evidence', 'CLEAR'),
('sales_intake_layouts', 'PRESERVE'),
('sales_order_cost_items', 'CLEAR'),
('sales_order_items', 'CLEAR'),
('sales_order_qty_change_logs', 'CLEAR'),
('sales_order_revision_logs', 'CLEAR'),
('sales_orders', 'CLEAR'),
('sales_other_shipment_items', 'CLEAR'),
('sales_other_shipments', 'CLEAR'),
('sales_quote_customer_templates', 'PRESERVE'),
('sales_quote_items', 'CLEAR'),
('sales_quote_revision_logs', 'CLEAR'),
('sales_quote_template_candidate_history', 'CLEAR'),
('sales_quote_template_candidates', 'CLEAR'),
('sales_quote_template_evidence', 'CLEAR'),
('sales_quote_template_versions', 'PRESERVE'),
('sales_quotes', 'CLEAR'),
('sales_return_disposition_events', 'CLEAR'),
('sales_return_items', 'CLEAR'),
('sales_return_quality_events', 'CLEAR'),
('sales_return_quality_items', 'CLEAR'),
('sales_returns', 'CLEAR'),
('sales_shipment_finance_release_events', 'CLEAR'),
('sales_shipment_items', 'CLEAR'),
('sales_shipment_submission_events', 'CLEAR'),
('sales_shipment_warehouse_events', 'CLEAR'),
('sales_shipments', 'CLEAR'),
('settlement_methods', 'PRESERVE'),
('stock_balance_adjustment_requests', 'CLEAR'),
('stock_balances', 'CLEAR'),
('stock_count_request_events', 'CLEAR'),
('stock_count_request_lines', 'CLEAR'),
('stock_count_requests', 'CLEAR'),
('stock_document_items', 'CLEAR'),
('stock_documents', 'CLEAR'),
('stock_draw_issue_batches', 'CLEAR'),
('stock_movements', 'CLEAR'),
('stock_reservations', 'CLEAR'),
('stock_value_acquisition_sources', 'CLEAR'),
('stock_value_edges', 'CLEAR'),
('stock_value_events', 'CLEAR'),
('stock_value_jobs', 'CLEAR'),
('stock_value_legacy_balance_case_events', 'CLEAR'),
('stock_value_legacy_balance_cases', 'CLEAR'),
('stock_value_node_revisions', 'CLEAR'),
('stock_value_nodes', 'CLEAR'),
('stock_value_openings', 'CLEAR'),
('stock_value_pools', 'CLEAR'),
('stock_value_position_transfers', 'CLEAR'),
('stock_value_postings', 'CLEAR'),
('stock_value_production_cost_dirty', 'CLEAR'),
('stock_value_production_cost_inputs', 'CLEAR'),
('stock_value_production_cost_objects', 'CLEAR'),
('stock_value_production_cost_outputs', 'CLEAR'),
('stock_value_production_cost_revisions', 'CLEAR'),
('stock_value_production_cost_shares', 'CLEAR'),
('stock_value_production_cost_tasks', 'CLEAR'),
('stock_value_tasks', 'CLEAR'),
('stock_weight_adjustments', 'CLEAR'),
('subcontract_application_items', 'CLEAR'),
('subcontract_applications', 'CLEAR'),
('subcontract_component_stock_handoffs', 'CLEAR'),
('subcontract_inquiries', 'CLEAR'),
('subcontract_inquiry_items', 'CLEAR'),
('subcontract_loss_case_lines', 'CLEAR'),
('subcontract_loss_cases', 'CLEAR'),
('subcontract_loss_events', 'CLEAR'),
('subcontract_loss_fulfillment_allocations', 'CLEAR'),
('subcontract_loss_resolutions', 'CLEAR'),
('subcontract_material_issue_items', 'CLEAR'),
('subcontract_material_issues', 'CLEAR'),
('subcontract_material_plan_items', 'CLEAR'),
('subcontract_material_plans', 'CLEAR'),
('subcontract_material_return_items', 'CLEAR'),
('subcontract_material_returns', 'CLEAR'),
('subcontract_order_cost_items', 'CLEAR'),
('subcontract_order_item_sources', 'CLEAR'),
('subcontract_order_items', 'CLEAR'),
('subcontract_orders', 'CLEAR'),
('subcontract_outbound_issue_reservation_allocations', 'CLEAR'),
('subcontract_outbound_preparation_commands', 'CLEAR'),
('subcontract_receipt_items', 'CLEAR'),
('subcontract_receipt_material_consumptions', 'CLEAR'),
('subcontract_receipts', 'CLEAR'),
('subcontract_return_items', 'CLEAR'),
('subcontract_returns', 'CLEAR'),
('subcontract_short_delivery_case_events', 'CLEAR'),
('subcontract_short_delivery_cases', 'CLEAR'),
('subcontract_waste_items', 'CLEAR'),
('subcontract_wastes', 'CLEAR'),
('subplan_links', 'CLEAR'),
('suggestion_likes', 'CLEAR'),
('suggestion_replies', 'CLEAR'),
('suggestions', 'CLEAR'),
('supplier_categories', 'PRESERVE'),
('supplier_claim_cash_receipts', 'CLEAR'),
('supplier_claim_receivables', 'CLEAR'),
('supplier_open_item_offsets', 'CLEAR'),
('supplier_return_tasks', 'CLEAR'),
('supplier_settlement_batch_events', 'CLEAR'),
('supplier_settlement_batch_lines', 'CLEAR'),
('supplier_settlement_batches', 'CLEAR'),
('suppliers', 'PRESERVE'),
('system_master_category_registry', 'PRESERVE'),
('system_posting_style_roles', 'PRESERVE'),
('system_settings', 'PRESERVE'),
('task_claims', 'CLEAR'),
('unit_measurement_profiles', 'PRESERVE'),
('units', 'PRESERVE'),
('user_data_scopes', 'PRESERVE'),
('user_permission_overrides', 'PRESERVE'),
('user_preferences', 'PRESERVE'),
('users', 'PRESERVE'),
('visitor_accounts', 'CLEAR'),
('visitor_applications', 'CLEAR'),
('visitor_approval_steps', 'CLEAR'),
('visitor_refresh_tokens', 'CLEAR'),
('visitor_sms_codes', 'CLEAR'),
('warehouse_arrival_exception_stock_in_batch_items', 'CLEAR'),
('warehouse_arrival_exception_stock_in_batches', 'CLEAR'),
('warehouse_arrival_registration_commands', 'CLEAR'),
('warehouse_goods_place_preferences', 'CLEAR'),
('warehouse_keepers', 'PRESERVE'),
('warehouses', 'PRESERVE'),
('website_inquiries', 'CLEAR'),
('workshop_machine_containers', 'PRESERVE'),
('workshop_machines', 'PRESERVE'),
('workshop_material_close_allocations', 'CLEAR'),
('workshop_material_close_materials', 'CLEAR'),
('workshop_material_close_theory_lines', 'CLEAR'),
('workshop_material_commands', 'CLEAR'),
('workshop_material_count_adjustment_postings', 'CLEAR'),
('workshop_material_count_lines', 'CLEAR'),
('workshop_material_count_postings', 'CLEAR'),
('workshop_material_counts', 'CLEAR'),
('workshop_material_other_issues', 'CLEAR'),
('workshop_material_period_closes', 'CLEAR'),
('workshop_material_period_lines', 'CLEAR'),
('workshop_material_periods', 'CLEAR'),
('workshop_material_requisition_lines', 'CLEAR'),
('workshop_material_requisition_postings', 'CLEAR'),
('workshop_material_requisitions', 'CLEAR'),
('workshop_material_settings', 'CLEAR'),
('workshop_material_stock_documents', 'CLEAR');

-- Verify the exact installed classifier before any destructive function call.
DO $review_installed_policy$
DECLARE definition text; difference text;
BEGIN
    SELECT pg_get_functiondef('public.business_data_reset()'::regprocedure) INTO definition;
    WITH installed AS (
        SELECT parts[1] AS table_name,parts[2] AS disposition
        FROM regexp_matches(definition,$pattern$\('([a-z][a-z0-9_]*)'\s*,\s*'(CLEAR|PRESERVE)'\)$pattern$,'g') AS matched(parts)
    ), policy_diff AS (
        SELECT COALESCE(expected.table_name,installed.table_name) AS table_name
        FROM reset_business_expected_policy expected FULL JOIN installed USING(table_name)
        WHERE expected.disposition IS DISTINCT FROM installed.disposition
        UNION ALL SELECT table_name FROM installed GROUP BY table_name HAVING count(*)<>1
    ) SELECT string_agg(table_name,', ' ORDER BY table_name) INTO difference FROM policy_diff;
    IF difference IS NOT NULL THEN RAISE EXCEPTION '脚本与已安装清空分类不一致：%',difference; END IF;
END $review_installed_policy$;

CREATE TEMP TABLE reset_business_operator_result ON COMMIT DROP AS
SELECT * FROM public.business_data_reset();

-- The function checks unknown/missing tables, protected references, object
-- completion proofs, all zeroed facts/amounts, preserved rows and refreshed views.
-- Compare its actual reviewed policy too; never trust only a count or a comment.
DO $review_executed_policy$
DECLARE difference text;
BEGIN
    SELECT string_agg(COALESCE(expected.table_name,actual.table_name),', ')
      INTO difference
      FROM reset_business_expected_policy expected FULL JOIN reset_business_table_policy actual USING(table_name)
     WHERE expected.disposition IS DISTINCT FROM actual.disposition;
    IF difference IS NOT NULL THEN RAISE EXCEPTION '实际清空分类发生漂移，整体回滚：%',difference; END IF;
END $review_executed_policy$;

INSERT INTO public.audit_log(actor_account,action,target_type,target_id,result,request_id,event_source,risk_level,event_category,device_capture_status)
SELECT 'ops:reset_business_data','business_data_reset','system_test',current_setting('app.audit_request_id'),
       format('cleared_tables=%s,cleared_rows=%s,preserved_tables=%s,epoch=%s,deleted_attachment_files=0',
           cleared_table_count,cleared_rows,preserved_table_count,authorization_epoch_after),
       current_setting('app.audit_request_id')::uuid,'business','critical','system','missing'
FROM reset_business_operator_result;
SELECT * FROM reset_business_operator_result;
COMMIT;
