package com.uten.imp.audit;

import java.time.OffsetDateTime;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.UUID;

/**
 * Sanitized client-declared device snapshot attached to one audit event.
 *
 * <p>The installation ID is generated by the app and is deliberately not a
 * hardware identifier. None of these fields prove physical-device ownership;
 * server-observed IP, status and time remain separate audit facts.
 */
public record AuditDeviceEvidence(
        UUID clientEventId,
        UUID installationId,
        String deviceName,
        String manufacturer,
        String model,
        String platform,
        String osVersion,
        String appVersion,
        String appBuild,
        String formFactor,
        String browserName,
        String locale,
        String timeZone,
        Integer timeZoneOffsetMinutes,
        Boolean physicalDevice,
        OffsetDateTime clientEventAt,
        String captureStatus,
        String profileHash,
        boolean clientDeclared) {

    static AuditDeviceEvidence from(AuditLog value) {
        String status = value.getDeviceCaptureStatus();
        return new AuditDeviceEvidence(
                value.getClientEventId(),
                value.getDeviceInstallationId(),
                value.getDeviceName(),
                value.getDeviceManufacturer(),
                value.getDeviceModel(),
                value.getDevicePlatform(),
                value.getDeviceOsVersion(),
                value.getAppVersion(),
                value.getAppBuild(),
                value.getDeviceFormFactor(),
                value.getDeviceBrowser(),
                value.getDeviceLocale(),
                value.getDeviceTimeZone(),
                value.getDeviceTimeZoneOffsetMinutes(),
                value.getDeviceIsPhysical(),
                value.getClientEventAt(),
                status,
                value.getDeviceProfileHash(),
                status != null
                        && !"missing".equals(status)
                        && !"legacy".equals(status));
    }

    void applyTo(AuditLog value) {
        value.setClientEventId(clientEventId);
        value.setDeviceInstallationId(installationId);
        value.setDeviceName(deviceName);
        value.setDeviceManufacturer(manufacturer);
        value.setDeviceModel(model);
        value.setDevicePlatform(platform);
        value.setDeviceOsVersion(osVersion);
        value.setAppVersion(appVersion);
        value.setAppBuild(appBuild);
        value.setDeviceFormFactor(formFactor);
        value.setDeviceBrowser(browserName);
        value.setDeviceLocale(locale);
        value.setDeviceTimeZone(timeZone);
        value.setDeviceTimeZoneOffsetMinutes(timeZoneOffsetMinutes);
        value.setDeviceIsPhysical(physicalDevice);
        value.setClientEventAt(clientEventAt);
        value.setDeviceCaptureStatus(captureStatus);
        value.setDeviceProfileHash(profileHash);
    }

    Map<String, Object> toSessionMap() {
        Map<String, Object> values = new LinkedHashMap<>();
        put(values, "clientEventId", clientEventId);
        put(values, "installationId", installationId);
        put(values, "deviceName", deviceName);
        put(values, "manufacturer", manufacturer);
        put(values, "model", model);
        put(values, "platform", platform);
        put(values, "osVersion", osVersion);
        put(values, "appVersion", appVersion);
        put(values, "appBuild", appBuild);
        put(values, "formFactor", formFactor);
        put(values, "browserName", browserName);
        put(values, "locale", locale);
        put(values, "timeZone", timeZone);
        put(values, "timeZoneOffsetMinutes", timeZoneOffsetMinutes);
        put(values, "physicalDevice", physicalDevice);
        put(values, "clientEventAt",
                clientEventAt == null ? null : clientEventAt.toString());
        put(values, "captureStatus", captureStatus);
        put(values, "profileHash", profileHash);
        return values;
    }

    public String displayLabel() {
        if (notBlank(deviceName) && notBlank(model)
                && !deviceName.equalsIgnoreCase(model)) {
            return deviceName + " · " + model;
        }
        if (notBlank(deviceName)) {
            return deviceName;
        }
        if (notBlank(model)) {
            return model;
        }
        if (notBlank(platform)) {
            return platform;
        }
        return "未提供设备信息";
    }

    private static void put(Map<String, Object> values, String key, Object value) {
        if (value != null) {
            values.put(key, value);
        }
    }

    private static boolean notBlank(String value) {
        return value != null && !value.isBlank();
    }
}
