package com.uten.imp.features.production.plan;

import com.uten.imp.common.domain.SoftDeletableEntity;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Table;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;

import java.time.LocalDate;
import java.util.UUID;

/**
 * 生产计划单头（生产管理 · 源 F_Plan，7,235 行）。
 *
 * <p>状态机：status 0 草稿 / 1 已审 / -1 红冲。审核由服务层校验并建立
 * {@code plan_order_item_links}，回写销售订单行的计划数量与业务链状态，并重算
 * {@code is_closed}。执行分段、物料需求、报工和成品入库由各自业务表与服务维护。
 *
 * <p>计划头本身不直接过账库存或应收应付；红冲会在下游门禁通过后回退销售来源联动。
 *
 * <p>车间字段：老库 WorkShop varchar(250) 装数字/名字（样本 "37"/"38"），新库 {@link #departmentId}
 * UUID 能对齐才填，{@link #workshopName} 原样文本留底（待 workshop_legacy_map 回填）。
 */
@Getter
@Setter
@NoArgsConstructor
@Entity
@Table(name = "production_plans")
public class ProductionPlan extends SoftDeletableEntity {

    @Column(name = "legacy_id", unique = true)
    private Integer legacyId;

    @Column(name = "bill_no", nullable = false)
    private String billNo;

    @Column(name = "bill_date", nullable = false)
    private LocalDate billDate;

    /** FStyle 生产类型（老库样本为空）。 */
    @Column(name = "f_style")
    private String fStyle;

    /** DDate 交货日期。 */
    @Column(name = "delivery_date")
    private LocalDate deliveryDate;

    /** WorkShop → departments（能对齐才填；老库 varchar 装名字/数字）。 */
    @Column(name = "department_id")
    private UUID departmentId;

    /** WorkShop varchar(250) 原样留底（车间编号/名字字符串）。 */
    @Column(name = "workshop_name")
    private String workshopName;

    /** WorkerID varchar(250) 多值名字，原样文本。 */
    @Column(name = "worker_name")
    private String workerName;

    /** Seller varchar(250) 跟单员，原样文本。 */
    @Column(name = "seller_name")
    private String sellerName;

    /** 跟单员 → employees（V82 加列；前端员工选择器所选 id，历史单留空）。 */
    @Column(name = "seller_id")
    private UUID sellerId;

    /** 生产工 → employees（V82 加列；同上）。 */
    @Column(name = "worker_id")
    private UUID workerId;

    /** MakeID → employees（迁移留空，B_Worker 与 employees 无 legacy_id 对齐）。 */
    @Column(name = "maker_id")
    private UUID makerId;

    @Column(name = "approver_id")
    private UUID approverId;

    /** MakeID 老 ID 留底（后续 worker_legacy_map 回填）。 */
    @Column(name = "maker_legacy_id")
    private Integer makerLegacyId;

    @Column(name = "approver_legacy_id")
    private Integer approverLegacyId;

    /** 制单员名（迁移期冻结老库 Sys_Operator.fname / B_Worker.Emp_Name；未来 employees.legacy_id 对齐后报表 COALESCE 优先真名，V69 加列）。 */
    @Column(name = "maker_name")
    private String makerName;

    /** 审核员名（同上）。 */
    @Column(name = "approver_name")
    private String approverName;

    /** Remark（text 大字段）。 */
    private String remark;

    /** 0 草稿 / 1 已审 / -1 红冲。 */
    @Column(name = "status", nullable = false)
    private Short status = 0;

    /** Fulfill 派生（CheckFulfill4 → Service 派生：所有明细 qty - iqty ≤ 0）。 */
    @Column(name = "is_closed", nullable = false)
    private boolean closed = false;

    /** Stop（手工中止）。 */
    @Column(name = "is_stopped", nullable = false)
    private boolean stopped = false;

    /** Cancel（取消）。 */
    @Column(name = "is_canceled", nullable = false)
    private boolean canceled = false;

    /** 看板置顶（V127）：进行中/已完成列表始终排最前。 */
    @Column(name = "is_pinned", nullable = false)
    private boolean pinned = false;

    /** 看板重要标注（V127）：卡片星标高亮。 */
    @Column(name = "is_important", nullable = false)
    private boolean important = false;

    /** 软关联占位（销售订单号等）。 */
    @Column(name = "source_doc_no")
    private String sourceDocNo;

    /** MAKE 树距根深度（0=根，1=直层 MAKE 子…）；NULL=非 orchestrator 计划。V130/#13：驱动傻瓜式 UI 最深层可开工优先。 */
    @Column(name = "bom_depth")
    private Integer bomDepth;

    /** TRUE=自底向上 orchestrator 自动创建的子计划（状态由服务端翻转，无人工审核）。V130/#13。 */
    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated = false;
}
