import 'stock_doc.dart';
import '../../../shared/models/production_material_discovery.dart';

/// Read-only reviewed facts retained solely for replaying the identical interrupted request.
Map<String, dynamic> stockDocumentDraftFacts(StockDocDetail doc) => {
  'id': doc.id,
  'docType': doc.docType,
  'billNo': doc.billNo,
  'billDate': doc.billDate,
  'warehouseId': doc.warehouseId,
  'toWarehouseId': doc.toWarehouseId,
  'remark': doc.remark,
  'totalLocal': doc.totalLocal,
  'status': doc.status,
  'closed': doc.closed,
  'sourceDocNo': doc.sourceDocNo,
  'sourceDailyReportId': doc.sourceDailyReportId,
  'sourcePlanId': doc.sourcePlanId,
  'planNo': doc.planNo,
  'workerId': doc.workerId,
  'makerId': doc.makerId,
  'assTeam': doc.assTeam,
  'departmentId': doc.departmentId,
  'issueStatus': doc.issueStatus,
  'makerName': doc.makerName,
  'workerName': doc.workerName,
  'createdAt': doc.createdAt,
  'productionLinked': doc.productionLinked,
  'productionMaterialReturn': doc.productionMaterialReturn,
  'materialReturnSourceWarehouseId': doc.materialReturnSourceWarehouseId,
  'materialReturnMainWarehouseId': doc.materialReturnMainWarehouseId,
  'canEdit': doc.canEdit,
  'canDelete': doc.canDelete,
  'restrictionReason': doc.restrictionReason,
  'finishedInboundDecision': doc.finishedInboundDecision,
  'finishedInboundVarianceReason': doc.finishedInboundVarianceReason,
  'items': [
    for (final item in doc.items)
      {
        'id': item.id,
        'lineNo': item.lineNo,
        'goodsId': item.goodsId,
        'colorId': item.colorId,
        'unitId': item.unitId,
        'qty': item.qty,
        'reportedQty': item.reportedQty,
        'baseQty': item.baseQty,
        'price': item.price,
        'amountLocal': item.amountLocal,
        'weight': item.weight,
        'surplusQty': item.surplusQty,
        'countQty': item.countQty,
        'place': item.place,
        'remark': item.remark,
        'unitRate': item.unitRate,
        'upstreamItemId': item.upstreamItemId,
        'executionSegmentId': item.executionSegmentId,
        'executionSegmentSalesAllocationId':
            item.executionSegmentSalesAllocationId,
        'sourceDailyReportItemId': item.sourceDailyReportItemId,
        'sourceDocNo': item.sourceDocNo,
        'issuedQty': item.issuedQty,
        'requestedQty': item.requestedQty,
      },
  ],
};

Map<String, dynamic> discoveryDraftFacts(
  ProductionMaterialDiscoveryDetail request,
) => {
  'requestId': request.requestId,
  'segmentId': request.segmentId,
  'segmentCode': request.segmentCode,
  'planNo': request.planNo,
  'productCode': request.productCode,
  'productName': request.productName,
  'productUnitName': request.productUnitName,
  'workshopName': request.workshopName,
  'status': request.status,
  'plannedQty': request.plannedQty,
  'version': request.version,
  'items': request.items,
  'suggestedItems': request.suggestedItems,
  'drawDocIds': request.drawDocIds,
};
