package com.uten.imp.config;

import com.uten.imp.common.platformcolumns.DisplayPlatformColumnAdapter;
import com.uten.imp.common.platformcolumns.PlatformColumnResourceAdapter;
import com.uten.imp.common.platformcolumns.PlatformColumnResourceAdapter.FactDefinition;
import com.uten.imp.security.SecurityContextCurrentUser;
import lombok.RequiredArgsConstructor;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import java.util.*;

/** Explicit page-family configuration. Calculations consume only the current page's authorized facts. */
@Configuration
@RequiredArgsConstructor
public class PlatformDisplayColumnsConfiguration {
    private final SecurityContextCurrentUser current;
    private static final List<FactDefinition> FACTS=List.of(
        new FactDefinition("qty","数量",false),new FactDefinition("quantity","数量",false),
        new FactDefinition("goodQty","良品数量",false),new FactDefinition("defectQty","不良数量",false),
        new FactDefinition("weight","重量（千克）",false),new FactDefinition("count","数量统计",false),
        new FactDefinition("requiredQty","需求数量",false),new FactDefinition("availableQty","可用数量",false),
        new FactDefinition("publicAvailableQty","公共可用数量",false),new FactDefinition("netShortageQty","还需安排数量",false),
        new FactDefinition("orderQty","下单数量",false),new FactDefinition("appendQty","追加数量",false),
        new FactDefinition("approvedRemainingQty","批准剩余数量",false),
        new FactDefinition("operations","人工操作次数",false),new FactDefinition("failures","失败次数",false),
        new FactDefinition("postLogout","退出后操作次数",false),
        new FactDefinition("plannedQty","计划数量",false),new FactDefinition("reportedQty","已报数量",false),
        new FactDefinition("price","单价",true),new FactDefinition("discount","折扣",true),
        new FactDefinition("amount","金额",true),new FactDefinition("amountOriginal","原币金额",true),
        new FactDefinition("amountLocal","本币金额",true),new FactDefinition("totalOriginal","原币合计",true),
        new FactDefinition("totalLocal","本币合计",true),new FactDefinition("balance","余额",true),
        new FactDefinition("grossIncome","应发金额",true),new FactDefinition("netIncome","实发金额",true),
        new FactDefinition("totalDeduction","扣减金额",true),new FactDefinition("days","天数",false),
        new FactDefinition("openingBalance","期初余额",true),new FactDefinition("accumulatedAmount","累计金额",true),
        new FactDefinition("closingBalance","期末余额",true),new FactDefinition("openingBalanceOriginal","期初原币余额",true),
        new FactDefinition("periodPostedOriginal","本期原币立账",true),new FactDefinition("periodPaidOriginal","本期原币付款",true),
        new FactDefinition("periodOffsetOriginal","本期原币冲抵",true),new FactDefinition("closingBalanceOriginal","期末原币余额",true),
        new FactDefinition("unitBookValueLocal","单位本币账面价值",true),new FactDefinition("lossBookValueLocal","本币损耗价值",true),
        new FactDefinition("actualLossQty","实际损耗数量",false),new FactDefinition("allowedLossQty","允许损耗数量",false),
        new FactDefinition("excessLossQty","超耗数量",false),new FactDefinition("warehouseAvailableQty","仓库可用数量",false),
        new FactDefinition("directReceivedQty","直送已收数量",false),new FactDefinition("issuedQty","已发数量",false),
        new FactDefinition("shortageQty","缺口数量",false),new FactDefinition("atSupplierQty","委外商处数量",false),
        new FactDefinition("consumedQty","耗用数量",false),new FactDefinition("returnedQty","退回数量",false),
        new FactDefinition("wastedQty","损耗数量",false),new FactDefinition("supplierEnding","委外结余",false),
        // Registered numeric report fields; source rows remain domain-authorized and masked.
        new FactDefinition("totalAmount","总额",true),
        new FactDefinition("girth","围数",false),
        new FactDefinition("returnedAmount","退货金额",true),
        new FactDefinition("boxQty","胶箱数量",false),
        new FactDefinition("openingQty","期初结存",false),
        new FactDefinition("issueQty","发胚数量",false),
        new FactDefinition("returnQty","退成品",false),
        new FactDefinition("mReturnQty","退原胚",false),
        new FactDefinition("wasteQty","退不良品",false),
        new FactDefinition("receiptQty","收货数量",false),
        new FactDefinition("closingQty","期末结存",false),
        new FactDefinition("pendingQty","待检量",false),
        new FactDefinition("pendingStockInQty","合格待入库",false),
        new FactDefinition("costAmount","库存台账金额",true),
        new FactDefinition("moreQty","多排数量",false),
        new FactDefinition("circumference","围数",false),
        new FactDefinition("machiningPrice","机加价",true),
        new FactDefinition("inboundQty","进仓数量",false),
        new FactDefinition("shippedQty","发货数量",false),
        new FactDefinition("stockQty","库存数量",false),
        new FactDefinition("dealAmount","成交金额",true),
        new FactDefinition("parcelCount","总件数",false),
        new FactDefinition("cartonCount","箱数",false),
        new FactDefinition("parcelQty","把/箱",false),
        new FactDefinition("materialPrice","材料价",true),
        new FactDefinition("dieCastPrice","压铸价",true),
        new FactDefinition("actualAmount","实际金额",true),
        new FactDefinition("docCount","单据数",false),
        new FactDefinition("totalQty","数量合计",false),
        new FactDefinition("receivedQty","收货数量",false),
        new FactDefinition("unreceivedQty","未收数量",false),
        new FactDefinition("safeStock","安全库存",false),
        new FactDefinition("orderedQty","采订数量",false),
        new FactDefinition("laborCost","人工费",true),
        new FactDefinition("giftQty","备品数",false),
        new FactDefinition("oqty","订货数量",false),
        new FactDefinition("iqty","完工数量",false),
        new FactDefinition("level","级次",false),
        new FactDefinition("opening","期初余额",true),
        new FactDefinition("debit","本期借方",true),
        new FactDefinition("credit","本期贷方",true),
        new FactDefinition("closing","期末余额",true),
        new FactDefinition("lineNo","行次",false),
        new FactDefinition("periodEnd","期末余额",true),
        new FactDefinition("yearStart","年初余额",true),
        new FactDefinition("monthAmount","本月金额",true),
        new FactDefinition("yearAmount","本年累计金额",true),
        new FactDefinition("salesRatio","占销售比%",true),
        new FactDefinition("receivable","应收金额",true),
        new FactDefinition("payable","应付金额",true),
        new FactDefinition("rate","汇率",true),
        new FactDefinition("writeOffOriginal","费用冲销金额",true),
        new FactDefinition("offsetOriginal","往来抵销金额",true),
        new FactDefinition("writeOffLocal","费用冲销人民币",true),
        new FactDefinition("offsetLocal","往来抵销人民币",true),
        new FactDefinition("balanceLocal","未结人民币",true),
        new FactDefinition("orderOriginal","订单原币金额",true),
        new FactDefinition("recognizedOriginal","已发运立账原币",true),
        new FactDefinition("expectedOriginal","未发运待收原币",true),
        new FactDefinition("creditFloor","铺底额",true),
        new FactDefinition("prevBalance","上月余额",true),
        new FactDefinition("shippedAmount","发货金额",true),
        new FactDefinition("receivedAmount","回款金额",true),
        new FactDefinition("returnAmount","退货金额",true),
        new FactDefinition("offsetAmount","货款冲销",true),
        new FactDefinition("exchangeDiff","汇兑差额",true),
        new FactDefinition("arReductionAmount","本期冲减应收",true),
        new FactDefinition("overFloor","超出铺底额",true),
        new FactDefinition("materialAmount","物料金额",true),
        new FactDefinition("unverifiedOriginalCount","币种/原币待核验项数",false),
        new FactDefinition("goodsAmount","采购入库",true),
        new FactDefinition("subcontractAmount","委外加工入库",true),
        new FactDefinition("purchaseReturnAmount","采购退货/质检贷项抵减",true),
        new FactDefinition("subcontractReturnAmount","委外退货/质检贷项抵减",true),
        new FactDefinition("wasteDeductionAmount","历史委外损耗扣款(兼容)",true),
        new FactDefinition("claimOffsetAmount","委外索赔贷项立账",true),
        new FactDefinition("reversedAmount","立账红冲净额",true),
        new FactDefinition("paidAmount","实际付款",true),
        new FactDefinition("settledAmount","账面核销",true),
        new FactDefinition("exchangeDifferenceLocal","付款汇兑差额",true),
        new FactDefinition("creditReleasedAmount","贷项已使用",true),
        new FactDefinition("totalBalance","应付合计",true),
        new FactDefinition("receiptRate","收款汇率",true),
        new FactDefinition("receivableOriginal","应收款金额",true),
        new FactDefinition("balanceBeforeOriginal","收款前未收",true),
        new FactDefinition("appliedLocal","本次冲减应收",true),
        new FactDefinition("balanceAfterOriginal","本次后未收",true),
        new FactDefinition("bankFee","手续费",true),
        new FactDefinition("otherFee","其它费用",true),
        new FactDefinition("receiptCount","收款单数",false),
        new FactDefinition("amountTotal","实际到账原币",true),
        new FactDefinition("paid","已付金额",true),
        new FactDefinition("unpaid","未付金额",true),
        new FactDefinition("thisPay","本次付款",true),
        new FactDefinition("thisBalance","本次余额",true),
        new FactDefinition("lineAmount","支出金额",true),
        new FactDefinition("incomeAmount","收入金额",true),
        new FactDefinition("thisReceiptOriginal","本次收款",true),
        new FactDefinition("thisReceiptLocal","本次收款人民币",true),
        new FactDefinition("returned","退货金额",true),
        new FactDefinition("inAmount","收款金额",true),
        new FactDefinition("outAmount","支出金额",true),
        new FactDefinition("prepaymentCashOriginal","预收现金(原币)",true),
        new FactDefinition("prepaymentCashLocal","预收现金(本币)",true),
        new FactDefinition("appliedOriginal","转销应收(原币)",true),
        new FactDefinition("sourceBookLocal","预收账面本币",true),
        new FactDefinition("designQty","设计用量",false),
        new FactDefinition("actualQty","实际用量",false),
        new FactDefinition("perProducedQty","每实产用量",false),
        new FactDefinition("netQty","净使用数量",false),
        new FactDefinition("exposureOutputQty","累计产出数量",false),
        new FactDefinition("defectRate","不良比例（1=100%）",false),
        new FactDefinition("sampleCount","样本数",false),
        new FactDefinition("allocatedQty","已分配数量",false),
        new FactDefinition("fulfilledQty","已完成数量",false),
        new FactDefinition("openQty","待完成数量",false),
        new FactDefinition("outstandingQty","未完成数量",false),
        new FactDefinition("reservedQty","已预留数量",false),
        new FactDefinition("producedQty","已生产数量",false),
        new FactDefinition("unplannedQty","待排数量",false),
        new FactDefinition("needQty","需求数量",false),
        new FactDefinition("analysisCoveredQty","已分析覆盖数量",false),
        new FactDefinition("requestQty","申请数量",false),
        new FactDefinition("perQty","每件用量",false),
        new FactDefinition("onhand","现有库存",false),
        new FactDefinition("remaining","剩余数量",false),
        new FactDefinition("maxReport","计划内或恢复数量",false),
        new FactDefinition("passedQty","合格数量",false),
        new FactDefinition("failedQty","不合格数量",false),
        new FactDefinition("remainingQty","剩余数量",false),
        new FactDefinition("authorizedInboundQty","允许入库数量",false),
        new FactDefinition("passQty","本次合格数量",false),
        new FactDefinition("failQty","本次不合格数量",false),
        new FactDefinition("receivedBaseQty","到检基本数量",false),
        new FactDefinition("remainingBaseQty","待检基本数量",false),
        new FactDefinition("planned","已排数量",false),
        new FactDefinition("produced","已生产入库数量",false),
        new FactDefinition("shipped","已发数量",false),
        new FactDefinition("available","本次可发数量",false),
        new FactDefinition("pending","办理中数量",false),
        new FactDefinition("allowedLossPct","允许损耗百分数（10=10%）",false),
        new FactDefinition("floorQty","最低交付数量",false),
        new FactDefinition("deliveredQty","已交付数量",false),
        new FactDefinition("shortfallQty","短交数量",false),
        new FactDefinition("shortfallPct","短交百分数（10=10%）",false),
        new FactDefinition("arrivalCount","到货次数",false),
        new FactDefinition("lossQty","损耗数量",false),
        new FactDefinition("lossPct","损耗百分数（10=10%）",false),
        new FactDefinition("estimatedRemainingQty","估计剩余数量",false),
        new FactDefinition("bookQty","账面数量",false),
        new FactDefinition("periodInQty","本期调入数量",false),
        new FactDefinition("periodReturnQty","本期退回数量",false),
        new FactDefinition("periodOtherQty","本期其它数量",false),
        new FactDefinition("estimatedUsedQty","估计耗用数量",false),
        new FactDefinition("lineCount","明细行数",false),
        new FactDefinition("declaredQty","申报数量",false),
        new FactDefinition("acceptedQty","接收数量",false),
        new FactDefinition("unacceptedQty","未接收数量",false),
        new FactDefinition("inQty","收入数量",false),
        new FactDefinition("outQty","发出数量",false),
        new FactDefinition("balanceQty","结存数量",false),
        new FactDefinition("boxQuantity","胶箱数量",false),
        new FactDefinition("returnedQuantity","退回数量",false),
        new FactDefinition("wastedQuantity","损耗数量",false),
        new FactDefinition("atSupplierQuantity","委外商处数量",false),
        new FactDefinition("consumedQuantity","耗用数量",false),
        new FactDefinition("supplierEndingQuantity","委外结余数量",false),
        new FactDefinition("endingQuantity","结余数量",false),
        new FactDefinition("standardQuantity","标准数量",false),
        new FactDefinition("wasteRate","损耗百分数（10=10%）",false),
        new FactDefinition("iqcPassedBaseQuantity","质检合格数量",false),
        new FactDefinition("iqcStockedBaseQuantity","质检已入库数量",false),
        new FactDefinition("iqcPendingStockInBaseQuantity","合格待入库数量",false),
        new FactDefinition("iqcFailedBaseQuantity","质检不合格数量",false),
        new FactDefinition("nRef","参考样本数",false),
        new FactDefinition("pendingSliceCount","待入库批次数",false),
        new FactDefinition("pendingReturnCount","待退回次数",false),
        new FactDefinition("itemCount","明细项数",false),
        new FactDefinition("theory","理论用量",false),
        new FactDefinition("unitWeight","单位重量（克）",false),
        new FactDefinition("actualPerUnit","实际单耗（克）",false),
        new FactDefinition("valueAtClose","结期金额",true),
        new FactDefinition("unitCost","单位成本",true),
        new FactDefinition("output","产出数量",false),
        new FactDefinition("exchangeRate","汇率",true),
        new FactDefinition("amountReceivedOriginal","已结算原币金额",true),
        new FactDefinition("amountWriteOffOriginal","冲销原币金额",true),
        new FactDefinition("prepaymentAppliedOriginal","预收已抵原币金额",true),
        new FactDefinition("amountBalanceOriginal","未结原币金额",true),
        new FactDefinition("amountBalance","未结本币金额",true),
        new FactDefinition("grossOriginal","应付原币金额",true),
        new FactDefinition("grossLocal","应付本币金额",true),
        new FactDefinition("paidOriginal","已付原币金额",true),
        new FactDefinition("paidLocal","已付本币金额",true),
        new FactDefinition("outstandingOriginal","未付原币金额",true),
        new FactDefinition("outstandingLocal","未付本币金额",true),
        new FactDefinition("overdueDays","逾期天数",false),
        new FactDefinition("claimAmountLocal","索赔本币金额",true),
        new FactDefinition("attempt","提交次数",false),
        new FactDefinition("clientBalance","客户本单币种未结金额",true),
        new FactDefinition("basisOutputQty","基准产量",false),
        new FactDefinition("analysisQty","本次分析数量",false),
        new FactDefinition("pass","本次合格数量",false),
        new FactDefinition("fail","本次不合格数量",false),
        new FactDefinition("current","本次决定数量",false),
        new FactDefinition("cumulative","当前累计数量",false),
        new FactDefinition("issuedWeight","已出库重量（千克）",false),
        new FactDefinition("documentWeight","单据重量（千克）",false),
        new FactDefinition("issueWeight","本次重量（千克）",false),
        new FactDefinition("appliedAmountOriginal","本次核销原币金额",true),
        new FactDefinition("inWeight","收入重量（千克）",false),
        new FactDefinition("outWeight","发出重量（千克）",false),
        new FactDefinition("balanceWeight","结存重量（千克）",false),
        new FactDefinition("prepared","已备数量",false),
        new FactDefinition("issued","已出库数量",false),
        new FactDefinition("stockAvailable","库存可用数量",false),
        new FactDefinition("maximum","最大可出数量",false),
        new FactDefinition("releasedWeight","放行重量（千克）",false),
        new FactDefinition("received","已接收数量",false),
        new FactDefinition("passed","合格数量",false),
        new FactDefinition("failed","不合格数量",false),
        new FactDefinition("tonnage","吨位",false),
        new FactDefinition("sortOrder","顺序号",false),
        new FactDefinition("grams","重量（克）",false),
        new FactDefinition("goodsWeight","单重（克）",false),
        new FactDefinition("weightKg","库存重量（千克）",false),
        new FactDefinition("idleDays","呆滞天数",false),
        new FactDefinition("age0_30","库龄0至30天数量",false),
        new FactDefinition("age31_90","库龄31至90天数量",false),
        new FactDefinition("age91_180","库龄91至180天数量",false),
        new FactDefinition("age181_365","库龄181至365天数量",false),
        new FactDefinition("ageOver365","库龄超过365天数量",false),
        new FactDefinition("ageUnknown","无入库记录数量",false),
        new FactDefinition("out90","近90天消耗数量",false),
        new FactDefinition("avgDailyOut90","日均消耗数量",false),
        new FactDefinition("daysOfCover","可用天数",false),
        new FactDefinition("daysSince","距上次盘点天数",false),
        new FactDefinition("qtyBase","登记基本数量",false),
        new FactDefinition("estimatedQty","称重折算数量",false),
        new FactDefinition("deviation","偏差数量",false),
        new FactDefinition("events","称重次数",false),
        new FactDefinition("flagged","异常次数",false),
        new FactDefinition("avgPct","平均偏差百分数（10=10%）",false),
        new FactDefinition("kg","差额重量（千克）",false),
        new FactDefinition("unitWeightKg","当前单重（千克）",false),
        new FactDefinition("masterUnitWeightKg","设计单重（千克）",false),
        new FactDefinition("masterDiffPct","设计差异百分数（10=10%）",false),
        new FactDefinition("sampleQty","抽样数量",false),
        new FactDefinition("sampleWeight","抽样重量（千克）",false),
        new FactDefinition("parcelQuantity","每件包装数量",false),
        new FactDefinition("targetBookLocal","应收账面本币",true));
    private PlatformColumnResourceAdapter view(String name,String label,String[] permissions,String[] prices){
        return new DisplayPlatformColumnAdapter("view_"+name,label,Set.of(permissions),Set.of(prices),current,FACTS);
    }
    @Bean PlatformColumnResourceAdapter salesDisplayColumns(){return view("sales","销售显示计算",
        new String[]{"sales_quote:view","sales_order:view","sales_shipment:view","sales_return:view","sales_report:view",
            "sales_quote_finance:view","sales_order_finance:view"},
        new String[]{"sales_order:price:view",
            "sales_quote_finance:view","sales_order_finance:view"});}
    @Bean PlatformColumnResourceAdapter purchaseDisplayColumns(){return view("purchase","采购显示计算",
        new String[]{"purchase_request:view","purchase_order:view","purchase_receipt:view","purchase_return:view","purchase_report:view","finance_order_approval:view"},
        new String[]{"purchase_order:price:view","purchase_receipt:price:view","purchase_return:price:view","finance:view:all","finance_order_approval:view"});}
    @Bean PlatformColumnResourceAdapter subcontractDisplayColumns(){return view("subcontract","委外显示计算",
        new String[]{"subcontract_order:view","subcontract_application:view","subcontract_receipt:view","subcontract_return:view","subcontract_report:view","finance_order_approval:view"},
        new String[]{"subcontract_order:price:view","subcontract_receipt:price:view","subcontract_return:price:view","finance:view:all","finance_order_approval:view"});}
    @Bean PlatformColumnResourceAdapter productionDisplayColumns(){return view("production","生产显示计算",
        new String[]{"production_plan:view","production_daily_report:view","production_material_analysis:view","production_report:view",
            "production_execution:view","workshop_material:view"},new String[]{"goods:cost:view"});}
    @Bean PlatformColumnResourceAdapter warehouseDisplayColumns(){return view("warehouse","仓库显示计算",
        new String[]{"stock_doc:view","stock:view","stock_report:view","warehouse:view","warehouse_inbound:view","warehouse_iqc_stock_in:view",
            "warehouse_purchase_receipt_history:view","warehouse_subcontract_receipt_history:view","warehouse_subcontract_outbound_history:view",
            "warehouse_subcontract_finished_return_history:view","warehouse_subcontract_material_return_history:view",
            "warehouse_subcontract_waste_history:view","warehouse_iqc_return:view","workshop_material:view"},new String[]{"goods:cost:view"});}
    @Bean PlatformColumnResourceAdapter financeDisplayColumns(){return view("finance","财务显示计算",
        new String[]{"finance_receipt:view","finance_payment:view","finance_expense:view","finance_other_income:view","finance_bank_transfer:view","ar_ap_ledger:view","finance_report:view","finance_asset:view","supplier_settlement:view","subcontract_loss_claim:view"},
        new String[]{"finance_receipt:view","finance_payment:view","finance_expense:view","finance_other_income:view","finance_bank_transfer:view","ar_ap_ledger:view","finance_report:view","finance_asset:view","supplier_settlement:view","finance:view:all"});}
    @Bean PlatformColumnResourceAdapter masterDisplayColumns(){return view("master","基础资料显示计算",
        new String[]{"goods:view","client:view","supplier:view","mould:view","warehouse:view","unit:view","color:view","currency:view","account:view"},
        new String[]{"goods:price:view","goods:cost:view","account:balance:view"});}
    @Bean PlatformColumnResourceAdapter accountStatementDisplayColumns(){
        return new DisplayPlatformColumnAdapter("view_account_statement","账户流水显示计算",
            Set.of("account:flow:view"),Set.of("account:balance:view"),current,
            List.of(new FactDefinition("inAmount","收入",true),new FactDefinition("outAmount","支出",true),
                new FactDefinition("balance","余额",true)),
            Set.of("account:view","account:balance:view","account:flow:view"));
    }
    private PlatformColumnResourceAdapter restrictedView(String name,String label,Set<String> required,String pricePermission){
        return new DisplayPlatformColumnAdapter("view_"+name,label,required,Set.of(pricePermission),current,FACTS,required);
    }
    @Bean PlatformColumnResourceAdapter arApLedgerDisplayColumns(){return restrictedView("ar_ap_ledger","往来账辅助计算",
        Set.of("ar_ap_ledger:view","finance:view:all"),"finance:view:all");}
    @Bean PlatformColumnResourceAdapter financeAssetDisplayColumns(){return restrictedView("finance_asset","资产摊销辅助计算",
        Set.of("finance_asset:view"),"finance_asset:view");}
    @Bean PlatformColumnResourceAdapter supplierSettlementDisplayColumns(){return restrictedView("supplier_settlement","供应商对账辅助计算",
        Set.of("supplier_settlement:view"),"supplier_settlement:view");}
    @Bean PlatformColumnResourceAdapter subcontractLossClaimDisplayColumns(){return restrictedView("subcontract_loss_claim","委外超耗辅助计算",
        Set.of("subcontract_loss_claim:view"),"finance:view:all");}
    @Bean PlatformColumnResourceAdapter financeOrderApprovalDisplayColumns(){return restrictedView("finance_order_approval","采购委外核价辅助计算",
        Set.of("finance_order_approval:view"),"finance_order_approval:view");}
    @Bean PlatformColumnResourceAdapter salesQuoteFinanceDisplayColumns(){return restrictedView("sales_quote_finance","报价核价辅助计算",
        Set.of("sales_quote_finance:view"),"sales_quote_finance:view");}
    @Bean PlatformColumnResourceAdapter salesOrderFinanceDisplayColumns(){return restrictedView("sales_order_finance","销售订单核价辅助计算",
        Set.of("sales_order_finance:view"),"sales_order_finance:view");}
    @Bean PlatformColumnResourceAdapter procurementIqcRejectionDisplayColumns(){return restrictedView("procurement_iqc_rejection","质检退回辅助计算",
        Set.of("procurement_iqc_rejection:view"),"procurement_iqc_rejection:amount:view");}
    @Bean PlatformColumnResourceAdapter employeeDisplayColumns(){return view("employee","人事显示计算",
        new String[]{"employee:view","department:view","profile:review","profile:edit:self"},new String[]{"employee:compensation:view"});}
    @Bean PlatformColumnResourceAdapter payrollDisplayColumns(){return view("payroll","工资显示计算",
        new String[]{"payroll:view:self","payroll:view:all"},new String[]{"payroll:view:self","payroll:view:all"});}
    @Bean PlatformColumnResourceAdapter expenseDisplayColumns(){return view("expense","报销显示计算",
        new String[]{"expense:apply","expense:approve","expense:pay"},new String[]{"expense:apply","expense:approve","expense:pay"});}
    @Bean PlatformColumnResourceAdapter qualityDisplayColumns(){return view("quality","品质显示计算",
        new String[]{"production_quality_inspection:view","procurement_iqc_rejection:view","warehouse_iqc_stock_in:view","sales_return_quality:view","stock_doc:view"},new String[]{});}
    @Bean PlatformColumnResourceAdapter visitorDisplayColumns(){return view("visitor","访客显示计算",
        new String[]{"visitor:approve","visitor:host_confirm","visitor:verify","visitor:check_in","visitor:blacklist"},new String[]{});}
    @Bean PlatformColumnResourceAdapter operationsDisplayColumns(){return view("operations","工作台显示计算",
        new String[]{"rd_task:view","suggestion:submit","suggestion:reply","notice:read","production_plan:view","production_execution:view",
            "purchase_request:view","purchase_order:view","subcontract_application:view","subcontract_order:view","sales_order:view","stock_doc:view"},new String[]{});}
    @Bean PlatformColumnResourceAdapter adminDisplayColumns(){return view("admin","系统监控显示计算",
        new String[]{"audit_log:view","server_status:view","authorization:manage","account:support"},new String[]{});}
}
